import {recognitionHistorySchema} from '@/lib/recognition-history';
import {recognitionData,exportRecognitionHistory,restoreRecognitionHistory} from '@/lib/recognition-repository';
import {videoRead,videoUpload} from '@/lib/video-storage';
import {awardGET,awardPOST} from '@/lib/awards-repository';
import {NextRequest,NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {db,rows,identity,readLeague,saveMatch,savePlayer,saveSeason} from '@/lib/repository';
import season2 from '@/data/imports/saison-2.json';
import {makeICS,eloHistory} from '@/lib/engine';
import {z} from 'zod';
import {playerSchema,seasonSchema,matchSchema} from '@/lib/validation';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest,{params}:{params:Promise<{path:string[]}>}){try{const {path}=await params;const user=await getChatGPTUser();if(path[0]==='awards')return json(await awardGET(user));if(path[0]==='videos')return videoRead(req,path[1]);if(path[0]==='photos'){if(!env.BUCKET)return json({error:'Stockage indisponible'},503);const photo=await env.BUCKET.get(path[1]);if(!photo)return json({error:'Photo introuvable'},404);return new Response(photo.body,{headers:{'Content-Type':photo.httpMetadata?.contentType??'image/jpeg','Cache-Control':'public, max-age=86400','X-Content-Type-Options':'nosniff'}})}const auth=await identity(user);if(path[0]==='recognition')return json(await recognitionData(await readLeague()));if(path[0]==='league')return json({...await readLeague(),...auth});if(path[0]==='calendar'){const data=await readLeague();const m=data.matches.find(m=>m.id===path[1]);if(!m)return json({error:'Match introuvable'},404);return new Response(makeICS(m,req.nextUrl.origin),{headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':`attachment; filename="copro-match-${m.number}.ics"`}})}if(path[0]==='export'){if(!auth.admin)return json({error:'Accès administrateur requis'},403);const data=await readLeague();const type=req.nextUrl.searchParams.get('table')??'BACKUP';if(type==='BACKUP')return new Response(JSON.stringify({...data,recognitionHistory:await exportRecognitionHistory()},null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="copro-backup.json"'}});const tables:Record<string,unknown[]>={PLAYERS:data.players,SEASONS:data.seasons,MATCHES:data.matches.map(({participants,events,...m})=>m),MATCH_STATS:data.matches.flatMap(m=>m.participants.map(p=>({match_id:m.id,player_id:p.playerId,team:p.team,...p.stats}))),PLAYER_ATTRIBUTES:data.players.map(p=>({player_id:p.id,...p.attributes})),ELO_HISTORY:Object.entries(eloHistory(data.players,data.matches)).flatMap(([playerId,h])=>h.map(x=>({player_id:playerId,...x})))};const list=tables[type];if(!list)return json({error:'Table inconnue'},400);const keys=[...new Set(list.flatMap(x=>Object.keys(x as object)))];const esc=(v:unknown)=>{let s=typeof v==='object'?JSON.stringify(v):String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return new Response('\ufeff'+[keys.join(';'),...list.map(r=>keys.map(k=>esc((r as any)[k])).join(';'))].join('\r\n'),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${type}.csv"`}})}return json({error:'Ressource introuvable'},404)}catch(e){console.error(e);return json({error:'Impossible de charger les données. Réessayez.'},503)}}
export async function POST(req:NextRequest,{params}:{params:Promise<{path:string[]}>}){try{const origin=req.headers.get('origin');if(origin!==req.nextUrl.origin)return json({error:'Origine non autorisée'},403);const user=await getChatGPTUser();if(!user)return json({error:'Connexion requise'},401);const {path}=await params;const auth=await identity(user);if(path[0]==='awards')return json(await awardPOST(await req.json(),user));if(path[0]==='bootstrap'){if(!auth.bootstrap)return json({error:'Administrateur déjà configuré'},409);await db().prepare('INSERT INTO admins(id,email) SELECT ?,? WHERE NOT EXISTS(SELECT 1 FROM admins)').bind(user.userId,user.email).run();return json({ok:true})}if(!auth.admin)return json({error:'Accès administrateur requis'},403);
if(path[0]==='videos')return videoUpload(req);
if(path[0]==='photos'){const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))return json({error:'Photo JPG, PNG ou WebP de moins de 5 Mo requise'},400);const bytes=new Uint8Array(await file.arrayBuffer());const valid=file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:file.type==='image/png'?bytes[0]===137&&bytes[1]===80:bytes[0]===82&&bytes[8]===87;if(!valid)return json({error:'Format de photo invalide'},400);if(!env.BUCKET)return json({error:'Stockage indisponible'},503);const key=crypto.randomUUID();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type}});return json({url:'/api/photos/'+key})}
if(Number(req.headers.get('content-length')??0)>3000000)return json({error:'Requête trop volumineuse'},413);const body=await req.json();if(path[0]==='players')return json({id:await savePlayer(body)});if(path[0]==='seasons'){const id=await saveSeason(body);await recognitionData(await readLeague());return json({id})}if(path[0]==='matches')return json({id:await saveMatch(body)});if(path[0]==='settings'){const settings=z.object({minRating:z.number().int().min(1).max(100),minRadar:z.number().int().min(1).max(100),minDuo:z.number().int().min(1).max(100),minPasses:z.number().int().min(1).max(10000),minAttempts:z.number().int().min(1).max(10000),ratingWeights:z.record(z.number().min(0).max(5)).refine(w=>Object.keys(w).every(k=>['finition','creation','passes','percussion','duels','defense'].includes(k))).optional()}).parse(body);await db().prepare('INSERT INTO settings(id,data) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind('thresholds',JSON.stringify(settings)).run();return json({ok:true})}if(path[0]==='season2'){if((await rows("SELECT id FROM seasons WHERE id='saison-2'")).length)return json({error:'La saison 2 est déjà importée'},409);for(const p of season2.players)await savePlayer(p);for(const s of season2.seasons)await saveSeason(s);for(const m of season2.matches)await saveMatch(m);return json({ok:true,players:season2.players.length,matches:season2.matches.length})}
if(path[0]==='import'){const data=z.object({players:z.array(playerSchema).max(500).default([]),seasons:z.array(seasonSchema).max(100).default([]),matches:z.array(matchSchema).max(500).default([]),recognitionHistory:recognitionHistorySchema.default([])}).parse(body);const before=await readLeague();if(data.recognitionHistory.some(h=>!data.seasons.some(s=>s.id===h.seasonId)&&!before.seasons.some(s=>s.id===h.seasonId)))throw Error('Saison du palmarès introuvable');let completed=0;const awards: {season:typeof data.seasons[number];version:number}[]=[];try{for(const p of data.players){await savePlayer({...p,version:before.players.some(x=>x.id===p.id)?p.version:0});completed++}for(const s of data.seasons){const version=before.seasons.some(x=>x.id===s.id)?s.version:0;await saveSeason({...s,version,winnerId:null});if(s.winnerId)awards.push({season:s,version:version+1});completed++}for(const m of data.matches){await saveMatch({...m,version:before.matches.some(x=>x.id===m.id)?m.version:0});completed++}for(const a of awards)await saveSeason({...a.season,version:a.version});await restoreRecognitionHistory(data.recognitionHistory);await recognitionData(await readLeague());}catch(e){return json({error:`Import interrompu après ${completed} enregistrements : ${e instanceof Error?e.message:'erreur'}. Les enregistrements précédents sont conservés.`},400)}return json({ok:true,completed})}return json({error:'Action inconnue'},404)}catch(e){console.error(e);const message=e instanceof z.ZodError?e.issues.map(x=>x.message).join(' · '):e instanceof Error?e.message:'Enregistrement impossible';return json({error:message.includes('SQLITE')?'Données incompatibles ou numéro de match déjà utilisé.':message},message.includes('Conflit')?409:400)}}

export async function HEAD(req:NextRequest,{params}:{params:Promise<{path:string[]}>}){const {path}=await params;if(path[0]==='videos')return videoRead(req,path[1],true);return new Response(null,{status:404})}
