import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createDatabase,type SQLConnection} from '../lib/server/sql.ts';
test('all season 2 records round-trip through the real repositories on PostgreSQL',async()=>{
 const pg=new PGlite();
 const wrap=(client:any):SQLConnection=>({query:async(s,a)=>{const r=await client.query(s,a);return {rows:r.rows,count:r.affectedRows??r.rows.length}},transaction:fn=>client.transaction((tx:any)=>fn(wrap(tx)))});
 await pg.exec(await readFile(new URL('../supabase/migrations/202609200001_league.sql',import.meta.url),'utf8'));
 const database=createDatabase(wrap(pg));
 mock.module('../lib/server/database.ts',{namedExports:{db:()=>database}});
 const {savePlayer,saveSeason,saveMatch,readLeague}=await import('../lib/repository.ts');
 const {recognitionData}=await import('../lib/recognition-repository.ts');
 const data=JSON.parse(await readFile(new URL('../data/imports/saison-2.json',import.meta.url),'utf8'));
 for(const p of data.players)await savePlayer(p);
 for(const s of data.seasons)await saveSeason(s);
 for(const m of data.matches)await saveMatch(m);
 const restored=await readLeague();
 assert.equal(restored.players.length,22);assert.equal(restored.matches.length,6);
 assert.equal(restored.matches.flatMap(m=>m.participants).reduce((n,p)=>n+(p.stats.goals??0),0),271);
 assert.equal(restored.matches.flatMap(m=>m.participants).reduce((n,p)=>n+(p.stats.assists??0),0),184);
 const newPlayer={...restored.players[0],id:'qa-new-player',name:'Nouveau joueur',version:0};
 await savePlayer(newPlayer);
 const createdPlayer=(await readLeague()).players.find(p=>p.id===newPlayer.id)!;
 assert.equal(createdPlayer.version,1);
 await savePlayer({...createdPlayer,name:'Joueur modifié'});
 await assert.rejects(savePlayer({...createdPlayer,name:'Modification périmée'}),/Conflit/);
 assert.equal((await readLeague()).players.find(p=>p.id===newPlayer.id)?.name,'Joueur modifié');
 const newSeason={...restored.seasons[0],id:'qa-new-season',name:'Nouvelle saison',winnerId:null,version:0};
 await saveSeason(newSeason);
 const createdSeason=(await readLeague()).seasons.find(s=>s.id===newSeason.id)!;
 assert.equal(createdSeason.version,1);
 await saveSeason({...createdSeason,name:'Saison modifiée'});
 await assert.rejects(saveSeason({...createdSeason,name:'Modification périmée'}),/Conflit/);
 assert.equal((await readLeague()).seasons.find(s=>s.id===newSeason.id)?.name,'Saison modifiée');
 await pg.exec("DELETE FROM player_attributes WHERE player_id='qa-new-player'; DELETE FROM players WHERE id='qa-new-player'; DELETE FROM seasons WHERE id='qa-new-season';");
 const match=restored.matches[0];await saveMatch({...match,notes:'PostgreSQL test'});
 await assert.rejects(saveMatch({...match,notes:'stale'}),/Conflit/);
 assert.equal((await readLeague()).matches.find(m=>m.id===match.id)?.notes,'PostgreSQL test');
 const awards=await recognitionData(await readLeague());assert.equal(awards.players.length,22);
 assert.equal(awards.seasons[0].awards.length,25);
 await pg.close();mock.restoreAll();
});
