'use client';
import * as m from 'motion/react-m';
import {BadgeViewer} from './animations/BadgeViewer';
import {BadgeCelebrations} from './animations/BadgeCelebrations';
import {useAnimations} from './animations/AnimationProvider';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import type {League} from '@/lib/model';
import type {RecognitionData} from '@/lib/recognition-repository';
import {awardDefinitions,badgeDefinitions} from '@/lib/recognition-definitions';
import {metricName,type Rule,type Check,type BadgeResult,type AwardResult} from '@/lib/recognition';
import {Avatar,Picker,Heading,Empty,fmt} from './league-ui';
import {RecognitionIcon} from './recognition-icon';
const Context=createContext<{recognition:RecognitionData|null;error:string}>({recognition:null,error:''});
export function RecognitionProvider({data,children}:{data:League|null;children:ReactNode}){
 const [recognition,setRecognition]=useState<RecognitionData|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!data)return;const abort=new AbortController();fetch('/api/recognition',{signal:abort.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Les distinctions sont momentanément indisponibles.');return r.json() as Promise<RecognitionData>}).then(d=>{setRecognition(d);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[data]);
 return <Context.Provider value={{recognition,error}}>{children}</Context.Provider>
}
function Pending(){const {error}=useContext(Context);return <p className={error?'error':'muted'} role={error?'alert':'status'}>{error||'Calcul des distinctions…'}</p>}
const comparator=(op?:string)=>op==='lt'?'<':op==='lte'?'≤':'≥';
function RuleText({rule}:{rule:Rule}){if('any'in rule||'of'in rule){const list='any'in rule?rule.any:rule.of;return <li><strong>{'any'in rule?'Au moins 1 critère':`Au moins ${rule.count} critères sur ${list.length}`} :</strong><ul>{list.map((r,i)=><RuleText key={i} rule={r}/>)}</ul></li>}return <li>{metricName(rule.key)} {comparator(rule.op)} {rule.percentile?'P':''}{fmt(rule.value,2)}{rule.low?' (percentile inversé)':''}</li>}
function Conditions({checks}:{checks:Check[]}){return <ul className="recognition-checks">{checks.map((c,i)=><li key={c.key+i} className={c.passed?'passed':''}><span aria-label={c.passed?'Rempli':'Non rempli'}>{c.passed?'✓':'○'}</span><span>{c.label}<small>{c.actual==null?'Donnée manquante':fmt(c.actual,2)} · objectif {comparator(c.op)} {fmt(c.target,2)}</small></span></li>)}</ul>}
function BadgeChip({badge}:{badge:BadgeResult}){return <span className={'identity-chip '+(badge.category==='Allegations'?'allegation':'')} title={badge.description+' · Badge Score '+badge.score+'/100'}><span><RecognitionIcon icon={badge.icon}/></span>{badge.name}</span>}
export function MainBadges({playerId}:{playerId:string}){const {recognition}=useContext(Context);const row=recognition?.players.find(p=>p.playerId===playerId);return row?.main.length?<div className="identity-chips" aria-label="Badges principaux">{row.main.map(b=><BadgeChip badge={b} key={b.id}/>)}</div>:null}
export function Identity({playerId}:{playerId:string}){
 const {recognition}=useContext(Context);const {reduced}=useAnimations();const [category,setCategory]=useState('Tous'),[sort,setSort]=useState('active');if(!recognition)return <Pending/>;const row=recognition.players.find(p=>p.playerId===playerId);
 return <section className="panel identity-panel"><div className="split"><div><span className="eyebrow">TES BADGES · {recognition.badgeSeasonName}</span><h2>Identity</h2></div><span className="tag">{row?.activeCount??0} badges actifs</span></div><p className="muted">Tes badges évoluent avec tes matchs. Parmi les trois badges principaux, une seule Allegation peut apparaître.</p>{row&&<BadgeCelebrations key={recognition.badgeSeasonId+':'+playerId} scope={recognition.badgeSeasonId+':'+playerId} badges={row.badges}/>}<BadgeViewer items={(row?.badges??[]).filter(b=>category==='Tous'||b.category===category).map(b=>({...b,kind:'badge' as const,status:b.active?'ACTIF · '+b.score+'/100':'VERROUILLÉ'}))}/><MainBadges playerId={playerId}/>{!row?.main.length&&<p className="muted">Aucun badge actif pour le moment.</p>}<details className="badge-collection"><summary className="button">Voir les 35 badges</summary><div className="split filterrow"><h3>Badge Collection</h3><Picker label="Trier les badges" value={sort} onChange={setSort} options={[{value:'active',label:'Actifs d’abord'},{value:'name',label:'Nom'}]}/><Picker label="Catégorie de badge" value={category} onChange={setCategory} options={['Tous','Status','Finishing',"Création / Technique",'Control','Volume','Defensive','Allegations'].map(x=>({value:x,label:x}))}/></div><p className="muted">Il faut au moins 4 matchs, ou 25 % du total du joueur qui a le plus joué si ce seuil est supérieur, arrondi au supérieur. Les percentiles comparent les joueurs de la saison et nécessitent au moins 3 joueurs.</p><div className="badge-grid">{row?.badges.filter(b=>category==='Tous'||b.category===category).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Number(b.active)-Number(a.active)||a.name.localeCompare(b.name)).map(b=><m.article layout={reduced?false:'position'} className={'badge-card '+(!b.active?'inactive ':'')+(b.category==='Allegations'?'allegation':'')} key={b.id}><div className="split"><span className="badge-icon"><RecognitionIcon icon={b.icon}/></span><span className="tag">{b.active?'ACTIF · '+b.score+'/100':'INACTIF'}</span></div><small className="eyebrow">{b.category}</small><h3>{b.name}</h3><p className="muted">{b.description}</p><Conditions checks={b.checks}/><details><summary>Règle complète</summary><ul>{badgeDefinitions.find(d=>d.id===b.id)?.rules.map((r,i)=><RuleText key={i} rule={r}/>)}</ul></details></m.article>)}</div></details></section>
}
function AwardCard({award,season,data}:{award:AwardResult;season:RecognitionData['seasons'][number];data:League}){
 const definition=awardDefinitions.find(d=>d.id===award.id);return <article className={'panel recognition-award '+(award.id==='copro-or'?'crown ':'')+(award.category==='Banter'?'banter':'')}><div className="split"><span className="award-icon"><RecognitionIcon icon={award.icon}/></span><span className="eyebrow">{award.category==='Banter'?'BANTER AWARD':'AWARD PRINCIPAL'}</span></div><h2>{award.name}</h2><p className="muted">{definition?.description??award.description}</p><p className="eyebrow">{season.seasonName} · {season.finalized?'PALMARÈS DÉFINITIF':'PROJECTION'}</p>{award.winner?<div className="award-winners">{award.winner.playerIds.map(id=><a href={'/joueurs/'+id} key={id}><Avatar player={data.players.find(p=>p.id===id)} large/><strong>{data.players.find(p=>p.id===id)?.name??award.winner!.name}</strong></a>)}<span className="award-score">{fmt(award.score,1)}<small> / 100 · score</small></span></div>:<p className="unassigned">NON ATTRIBUÉ</p>}<p className="muted">{!season.finalized&&award.winner?"En tête pour le moment. Le trophée sera attribué à la fin de la saison.":award.reason}</p><details><summary>Calcul et conditions</summary><p className="muted">Chaque stat est convertie en percentile, puis multipliée par son poids dans le calcul.</p><div className="award-formula">{award.formula.map(w=><div className="statrow" key={w.key}><span>{metricName(w.key)}{w.low?' · faible valeur favorisée':''}<small>{w.weight} %</small></span><strong>{fmt(award.winner?.values[w.key],2)}</strong></div>)}</div>{award.checks.length>0&&<Conditions checks={award.checks}/>}<ul>{definition?.ratio&&<li>Il faut au moins 5 matchs, ou 35 % du total du joueur qui a le plus joué si ce seuil est supérieur, arrondi au supérieur.</li>}{definition?.rules.map((r,i)=><RuleText key={i} rule={r}/>)}{definition?.always&&<li>Attribué dès qu’au moins un joueur a joué un match. Si des stats manquent, les poids sont ajustés entre les stats disponibles.</li>}</ul></details></article>
}
export function Awards({data}:{data:League}){const {recognition}=useContext(Context);const {reduced}=useAnimations();const [selected,setSelected]=useState(''),[category,setCategory]=useState('Tous');if(!recognition)return <Pending/>;const season=recognition.seasons.find(s=>s.seasonId===selected)||recognition.seasons.find(s=>s.seasonId===recognition.badgeSeasonId)||recognition.seasons[0];return <><Heading title="LES AWARDS." kicker="TROPHÉES &amp; PALMARÈS"><Picker label="Saison des awards" value={season?.seasonId??''} onChange={setSelected} options={recognition.seasons.map(s=>({value:s.seasonId,label:s.seasonName}))}/><Picker label="Catégorie des awards" value={category} onChange={setCategory} options={['Tous','Principaux','Banter'].map(x=>({value:x,label:x==='Principaux'?'Awards principaux':x==='Banter'?'Banter Awards':x}))}/></Heading><p className="intro muted">25 trophées, calculés à partir des stats de la saison. Les Banter Awards font aussi partie du lot.</p>{season?<><div className="recognition-status"><span className="tag">{season.finalized?'PALMARÈS FIGÉ':"CLASSEMENT PROVISOIRE"}</span><p>{season.finalized?"Le palmarès est définitif. Les trophées restent attribués même si les stats changent ensuite.":"Ces résultats sont provisoires. Les trophées seront attribués automatiquement à la fin de la saison, une seule fois."}</p></div><BadgeViewer items={season.awards.filter(a=>category==='Tous'||a.category===category).map(a=>({...a,description:awardDefinitions.find(d=>d.id===a.id)?.description??a.description,kind:'award' as const,status:(season.finalized?'PALMARÈS DÉFINITIF':'PROJECTION')+' · '+(a.winner?.name??'NON ATTRIBUÉ')}))}/><div className="recognition-grid">{season.awards.filter(a=>category==='Tous'||a.category===category).map(a=><m.div key={a.id} layout={reduced?false:'position'}><AwardCard award={a} season={season} data={data}/></m.div>)}</div></>:<Empty>Crée une première saison pour commencer à suivre les awards.</Empty>}<section className="panel recognition-method"><h3>Comment sont attribués les awards ?</h3><p className="muted">{recognition.method}</p><details><summary>Données nécessaires et limites</summary>{recognition.limits.map(l=><p key={l.metric}><strong>{l.affected.join(' · ')}</strong><br/>{l.reason}</p>)}<p>Une stat manquante reste inconnue. Si les données ne permettent pas de vérifier les seuils ou le calcul, le trophée n’est pas attribué.</p></details></section></>}
export function Palmares({playerId}:{playerId:string}){const {recognition}=useContext(Context);if(!recognition)return <Pending/>;const won=recognition.seasons.filter(s=>s.finalized).map(s=>({...s,awards:s.awards.filter(a=>a.winner?.playerIds.includes(playerId))})).filter(s=>s.awards.length);return <section className="panel recognition-palmares"><span className="eyebrow">LES TROPHÉES REMPORTÉS</span><h2>Palmarès</h2><BadgeViewer items={won.flatMap(s=>s.awards.map(a=>({...a,id:s.seasonId+':'+a.id,description:awardDefinitions.find(d=>d.id===a.id)?.description??a.description,kind:'award' as const,status:'ATTRIBUÉ · '+s.seasonName})))}/>{won.map(s=><div key={s.seasonId}><h3>{s.seasonName}</h3>{s.awards.map(a=><a className={'palmares-item '+(a.category==='Banter'?'banter':'')} href="/awards" key={a.id}><span><RecognitionIcon icon={a.icon}/></span><strong>{a.name}</strong>{a.winner!.playerIds.length>1&&<small>{a.winner!.name}</small>}</a>)}</div>)}{!won.length&&<p className="muted">Aucun trophée au palmarès pour le moment. Seuls les awards des saisons terminées ou archivées apparaissent ici.</p>}</section>}
export function SeasonHonors({seasonId}:{seasonId:string}){const {recognition}=useContext(Context);if(!recognition)return <Pending/>;const season=recognition.seasons.find(s=>s.seasonId===seasonId);const crown=season?.awards.find(a=>a.id==='copro-or');return <div className="season-honors"><span className="eyebrow">COPRO D’OR · {season?.finalized?'DÉFINITIF':'PROJECTION'}</span><h3>{crown?.winner?.name??'En attente de matchs'}</h3><a href="/awards" className="button">Voir les 25 Awards</a></div>}
