'use client';
import Link from 'next/link';
import {statHelp} from '@/lib/stat-help';
import type {Player,Match} from '@/lib/model';
import {teamName,labels,ratios,statGroups} from '@/lib/model';
import {radar,type Summary} from '@/lib/engine';
import {SourceTemplate,hudTemplates,childNodes} from './hud-source-template';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ArrowUpRight,CalendarPlus,Info} from 'lucide-react';
export {Tabs,TabsList,TabsTrigger,TabsContent};
export const fmt=(v:number|null|undefined,d=1)=>v==null?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:d}).format(v);
export const date=(v:string,full=false)=>!v?'Date non renseignée':new Date(v).toLocaleDateString('fr-FR',{timeZone:'Europe/Paris',day:'numeric',month:full?'long':'short',...(full?{weekday:'long' as const}:{} )});
export const time=(v:string)=>!v?'—':new Date(v).toLocaleTimeString('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'});
export function Picker({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string}){return <span className="hud-kit"><SourceTemplate name="kitSelect" props={{'':{value,'aria-label':label,onChange:(e:React.ChangeEvent<HTMLSelectElement>)=>onChange(e.target.value)}}} slots={{'':options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}}/></span>}
export function Avatar({player,large=false}:{player?:Player;large?:boolean}){return <span className={'avatar '+(large?'large':'')}>{player?.photo?<img src={player.photo} alt={player.name}/>:<span>{player?.name.slice(0,2).toUpperCase()??'CL'}</span>}</span>}
export function Empty({children}:{children:React.ReactNode}){return <div className="hud-kit"><SourceTemplate node={{...hudTemplates.kitEmpty,children:childNodes(hudTemplates.kitEmpty).map((n,i)=>i===1?{...n,tag:'div'}:n)}} slots={{'1':children,'2':'','3':''}} props={{'':{'data-source-template':'kitEmpty'},'3':{style:{display:'none'}}}}/></div>}
export function Heading({title,kicker,children,level='h1'}:{title:string;kicker?:string;children?:React.ReactNode;level?:'h1'|'h2'}){const Title=level;return <div className="pagehead"><div>{kicker&&<div className="eyebrow">{kicker}</div>}<Title>{title}<span className="heading-mark" aria-hidden="true">{'//'}</span></Title></div><div className="controls">{children}</div></div>}
export function StatInfo({stat}:{stat:string}){const help=statHelp(stat);return <Dialog><DialogTrigger asChild><button type="button" className="infobutton" aria-label={'Comprendre '+(labels[stat]??stat)}><Info size={14}/></button></DialogTrigger><DialogContent><DialogTitle>{labels[stat]??stat}</DialogTitle><DialogDescription>Lire cette statistique sans se tromper.</DialogDescription><div className="stathelp"><h3>DÉFINITION</h3><p>{help.definition}</p><h3>CALCUL</h3><p>{help.calculation}</p><h3>INTERPRÉTATION</h3><p>{help.interpretation}</p>{help.example&&<><h3>EXEMPLE</h3><p>{help.example}</p></>}<Link className="textbutton" href="/glossaire">Comprendre toutes les stats ↗</Link></div></DialogContent></Dialog>}
export function StatGrid({summary}:{summary:Summary}){return <div className="statgrid">{Object.entries(statGroups).map(([group,fields])=><section className="panel" key={group}><h3>{group}</h3>{Object.keys(fields).map(k=><div className="statrow" key={k}><span>{labels[k]}<StatInfo stat={k}/></span><strong>{fmt(summary.stats[k])}</strong></div>)}{Object.entries(ratios).filter(([,pair])=>pair[0] in fields).map(([k])=><div className="statrow" key={k}><span>{labels[k]}<StatInfo stat={k}/></span><strong>{fmt(summary.stats[k])}{summary.stats[k]!=null?' %':''}</strong></div>)}</section>)}</div>}
export { SourceLeaderboard as LeaderCard } from "./league-source-modules";
export function MatchRow({match:m}:{match:Match}){return <a className="matchrow" href={'/matchs/'+m.id}><div><span className="eyebrow">MATCH #{m.number}</span><p>{date(m.date)} · {time(m.date)}</p></div><strong>{teamName(m,'A')} <b>{m.status==='finished'?`${m.scoreA} — ${m.scoreB}`:m.status==='cancelled'?'ANNULÉ':'VS'}</b> {teamName(m,'B')}</strong><span className="muted">{m.status==='finished'?'Terminé':`${m.participants.length} joueurs`} <ArrowUpRight size={16}/></span></a>}
export function Calendar({match:m}:{match:Match}){const start=new Date(m.date),end=new Date(start.getTime()+m.duration*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const origin=typeof window!=='undefined'?window.location.origin:'';const detail=`Pense à arriver 10 minutes avant. ${origin}/matchs/${m.id}`;const google='https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:`Foot à 5 — Match #${m.number}`,dates:`${stamp(start)}/${stamp(end)}`,location:m.location,details:detail});const outlook='https://outlook.live.com/calendar/0/deeplink/compose?'+new URLSearchParams({subject:`Foot à 5 — Match #${m.number}`,startdt:start.toISOString(),enddt:end.toISOString(),location:m.location,body:detail});return <Dialog><DialogTrigger asChild><button className="button"><CalendarPlus size={16}/>Ajouter à mon calendrier</button></DialogTrigger><DialogContent><DialogTitle>Le prochain rendez-vous</DialogTitle><DialogDescription>{date(m.date,true)} à {time(m.date)} · {m.location}</DialogDescription><a className="button" href={google} target="_blank" rel="noreferrer">Google Calendar</a><a className="button" href={outlook} target="_blank" rel="noreferrer">Outlook</a><a className="button" href={'/api/calendar/'+m.id}>Apple Calendar / Fichier .ics</a></DialogContent></Dialog>}
export function Radar({summary,population,minimum=5}:{summary:Summary;population:Summary[];minimum?:number}){const axes=radar(summary,population,minimum);const point=(i:number,r:number)=>[150+Math.sin(i*Math.PI/3)*r,142-Math.cos(i*Math.PI/3)*r];const poly=(r:number)=>axes.map((_,i)=>point(i,r).join(',')).join(' ');return <section className="panel"><div className="split"><h3>Le jeu, sous tous les angles</h3><span className="eyebrow">RADAR</span></div><svg viewBox="0 0 300 290" className="radar" role="img" aria-label="Radar de performance à six axes">{[25,50,75,100].map(r=><polygon key={r} points={poly(r)} fill="none" stroke="var(--line)"/>)}{axes.map((a,i)=><g key={a.name}><line x1="150" y1="142" x2={point(i,100)[0]} y2={point(i,100)[1]} stroke="var(--line)"/><text x={point(i,125)[0]} y={point(i,125)[1]} fill="var(--body)" textAnchor="middle" fontSize="11">{a.name.toUpperCase()}</text></g>)}{axes.every(a=>a.value!=null)&&<polygon points={axes.map((a,i)=>point(i,a.value!).join(',')).join(' ')} fill="color-mix(in srgb, var(--kush) 19%, transparent)" stroke="var(--kush)" strokeWidth="2"/>}{axes.map((a,i)=>{if(a.value==null)return null;const [x,y]=point(i,a.value),next=axes[(i+1)%axes.length];return <g key={a.name}>{next.value!=null&&<line x1={x} y1={y} x2={point((i+1)%axes.length,next.value)[0]} y2={point((i+1)%axes.length,next.value)[1]} stroke="var(--kush)" strokeWidth="2"/>}<circle cx={x} cy={y} r="3" fill="var(--kush)"><title>{a.name} : {fmt(a.value,0)} / 100</title></circle></g>})}</svg>{axes.map(a=><details key={a.name} className="radardetail"><summary><span>{a.name}</span><strong>{fmt(a.value,0)}</strong></summary><p className="muted">{a.description}. {a.value==null?`Minimum ${minimum} matchs par joueur et 3 joueurs comparables requis.`:'Percentile relatif aux joueurs éligibles de la période.'}</p>{a.evidence.map(e=><div key={e.key} className="statrow"><span>{labels[e.key]}</span><b>{fmt(e.value)}</b></div>)}</details>)}</section>}
export function EloChart({summary:s}:{summary:Summary}){const vals=[1000,...s.history.map(h=>h.elo)];const min=Math.min(...vals)-10,max=Math.max(...vals)+10;return <section className="panel"><div className="split"><h3>La courbe ELO <StatInfo stat="elo"/></h3><strong className="accent">{s.elo}</strong></div><svg viewBox="0 0 500 150" className="elochart" role="img" aria-label={'Évolution ELO : '+vals.join(', ')}><line x1="0" y1="120" x2="500" y2="120" stroke="var(--line)"/><polyline points={vals.map((v,i)=>`${i*490/Math.max(1,vals.length-1)+5},${130-(v-min)/(max-min)*110}`).join(' ')} fill="none" stroke="var(--kush)" strokeWidth="3"/></svg><div className="split muted"><span>Départ 1 000</span><span>Record {Math.max(...vals)}</span></div></section>}
