'use client';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {youtubeId} from '@/lib/engine';
import {MAX_VIDEO_BYTES} from '@/lib/media-policy';
import {uploadMedia} from '@/lib/media-upload';

export type VideoPlayerHandle={time:()=>number;seek:(seconds:number)=>void;toggle:()=>void;step:(seconds:number)=>void;speed:(rate:number)=>void};
export function formatVideoTime(seconds:number){const whole=Math.max(0,Math.floor(Number.isFinite(seconds)?seconds:0));return `${String(Math.floor(whole/60)).padStart(2,'0')}:${String(whole%60).padStart(2,'0')}`}
export const VideoPlayer=forwardRef<VideoPlayerHandle,{src:string;initialTime?:number;className?:string;onTime?:(seconds:number)=>void}>(function VideoPlayer({src,initialTime=0,className,onTime},ref){
 const host=useRef<HTMLDivElement>(null),html=useRef<HTMLVideoElement>(null),yt=useRef<any>(null),timeRef=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null);const [time,setTime]=useState(0),[ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[rate,setRate]=useState(1),[error,setError]=useState('');const id=youtubeId(src);const local=src.startsWith('blob:')||/^\/api\/videos\/[0-9a-f-]+\.(mp4|mov|webm)$/.test(src);
 const onTimeRef=useRef(onTime);onTimeRef.current=onTime;
 const update=(value:number)=>{const next=Number.isFinite(value)?Math.max(0,value):0;timeRef.current=next;setTime(next);onTimeRef.current?.(next)};
 useEffect(()=>{setReady(false);setError('');setPlaying(false);update(0);if(!id||!host.current)return;let disposed=false;const init=()=>{const YT=(window as any).YT;if(disposed||!YT?.Player||!host.current)return false;const element=document.createElement('div');host.current.replaceChildren(element);yt.current=new YT.Player(element,{videoId:id,host:'https://www.youtube.com',playerVars:{playsinline:1,rel:0,origin:window.location.origin},events:{onReady:()=>{if(!disposed){setReady(true);if(initialTime)yt.current?.seekTo?.(initialTime,true)}},onStateChange:(event:any)=>setPlaying(event.data===1),onError:(event:any)=>{setReady(false);setError(event.data===100?'Vidéo privée, supprimée ou inaccessible à ce compte YouTube.':[101,150].includes(event.data)?'YouTube interdit la lecture intégrée de cette vidéo (restriction d’âge ou intégration désactivée).':event.data===153?'YouTube ne reconnaît pas ce lecteur intégré. Ouvrez la vidéo sur YouTube ou utilisez le fichier local.':'YouTube ne permet pas de lire cette vidéo ici. Ouvrez-la sur YouTube ou utilisez le fichier local.')}}});return true};let poll:ReturnType<typeof setInterval>|undefined;if(!init()){if(!document.querySelector('script[src="https://www.youtube.com/iframe_api"]')){const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';document.head.appendChild(script)}poll=setInterval(()=>{if(init())clearInterval(poll)},200)}timer.current=setInterval(()=>{if(yt.current?.getCurrentTime)update(Number(yt.current.getCurrentTime()))},250);return()=>{disposed=true;if(poll)clearInterval(poll);if(timer.current)clearInterval(timer.current);timer.current=null;yt.current?.destroy?.();yt.current=null}},[src]);
 const api:VideoPlayerHandle={time:()=>id?Number(yt.current?.getCurrentTime?.()??timeRef.current):Number(html.current?.currentTime??timeRef.current),seek:(seconds)=>{const next=Math.max(0,seconds);if(id)yt.current?.seekTo?.(next,true);else if(html.current)html.current.currentTime=next;update(next)},toggle:()=>{if(id){const state=yt.current?.getPlayerState?.();if(state===1)yt.current?.pauseVideo?.();else yt.current?.playVideo?.()}else if(html.current){if(html.current.paused)void html.current.play().catch(()=>setError('Lecture impossible.'));else html.current.pause()}},step:(seconds)=>{api.seek(api.time()+seconds)},speed:(next)=>{if(![.5,1,1.5,2].includes(next))return;if(id)yt.current?.setPlaybackRate?.(next);else if(html.current)html.current.playbackRate=next;setRate(next)}};
 useImperativeHandle(ref,()=>api,[id]);
 const onKey=(event:React.KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.closest('input,textarea,select,button,[contenteditable="true"]'))return;if(event.code==='Space'){event.stopPropagation();event.preventDefault();api.toggle()}else if(event.code==='ArrowLeft'){event.stopPropagation();event.preventDefault();api.step(-1)}else if(event.code==='ArrowRight'){event.stopPropagation();event.preventDefault();api.step(1)}};
 return <div className={className??'panel formstack'} tabIndex={0} onKeyDown={onKey} aria-label="Lecteur vidéo, espace pour lecture ou pause, flèches pour avancer ou reculer"><div className="youtube" ref={host} style={{display:id?'block':'none'}}/>{local&&<video ref={html} src={src} controls playsInline preload="metadata" style={{width:'100%',maxHeight:520}} onLoadedMetadata={()=>{setReady(true);if(initialTime&&html.current)html.current.currentTime=initialTime}} onTimeUpdate={e=>update(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setError('La vidéo ne peut pas être lue dans ce navigateur. Le fichier MOV peut nécessiter une conversion en MP4.')}/ >}{!id&&!local&&<p className="muted">Ajoutez une vidéo YouTube ou importez un fichier pour analyser le match.</p>}<div className="actions"><button type="button" className="button" disabled={!ready} onClick={()=>api.step(-5)}>−5 s</button><button type="button" className="button" disabled={!ready} onClick={()=>api.step(-1)}>−1 s</button><button type="button" className="button primary" disabled={!ready} onClick={()=>api.toggle()}>{playing?'Pause':'Lecture'}</button><button type="button" className="button" disabled={!ready} onClick={()=>api.step(1)}>+1 s</button><button type="button" className="button" disabled={!ready} onClick={()=>api.step(5)}>+5 s</button><strong className="accent" aria-live="off">{formatVideoTime(time)}</strong><label>Vitesse <select aria-label="Vitesse de lecture" value={rate} onChange={e=>api.speed(Number(e.target.value))}>{[.5,1,1.5,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label></div>{id&&<p className="muted">Vidéo privée ou limitée par âge ? <a className="textbutton" target="_blank" rel="noopener noreferrer" href={'https://www.youtube.com/watch?v='+id+'&t='+Math.floor(time)+'s'}>Ouvrir sur YouTube à {formatVideoTime(time)}</a>. Pour annoter avec un temps synchronisé, utilisez le fichier local.</p>}{error&&<p className="error" role="alert">{error}</p>}</div>
});
export function VideoSource({value,onChange,onLocal}:{value:string;onChange:(url:string)=>void;onLocal?:(file:File)=>void}){const [tab,setTab]=useState<'youtube'|'file'>(value.startsWith('/api/videos/')?'file':'youtube'),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),xhr=useRef<AbortController|null>(null);
 const upload=async(file:File)=>{setError('');if(file.size>MAX_VIDEO_BYTES){setError('La vidéo dépasse 50 Mo.');return}if(!/\.(mp4|mov|webm)$/i.test(file.name)){setError('Choisissez un fichier MP4, MOV ou WebM.');return}const controller=new AbortController();xhr.current=controller;setBusy(true);setProgress(0);try{const url=await uploadMedia('videos',file,{signal:controller.signal,onProgress:setProgress});setProgress(100);onChange(url)}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);else setProgress(null)}finally{setBusy(false);xhr.current=null}};
 return <div className="panel formstack"><h3>Ajouter une vidéo</h3><div className="actions"><button type="button" className={tab==='youtube'?'button primary':'button'} onClick={()=>setTab('youtube')}>YouTube</button><button type="button" className={tab==='file'?'button primary':'button'} onClick={()=>setTab('file')}>Importer depuis l’ordinateur</button></div>{tab==='youtube'?<label className="field"><span>URL YouTube</span><input type="url" value={value.startsWith('/api/videos/')?'':value} placeholder="https://www.youtube.com/watch?v=…" onChange={e=>onChange(e.target.value)}/></label>:<><label className="field"><span>MP4, MOV ou WebM · 50 Mo maximum</span><input type="file" accept=".mp4,.mov,.webm,video/mp4,video/quicktime,video/webm" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></label>{busy&&<><progress value={progress??0} max="100" style={{width:'100%'}}/><span>{progress??0} %</span><button type="button" className="button" onClick={()=>xhr.current?.abort()}>Annuler l’envoi</button></>}{value.startsWith('/api/videos/')&&<p className="success">Vidéo importée et prête à lire.</p>}</>}<p className="muted">Les vidéos restent dans le stockage objet. Pour les longs matchs, utilisez YouTube ou un fichier compressé. MOV : lecture selon les codecs du navigateur ; conversion automatique non disponible.</p>{onLocal&&<label className="local-video-choice"><strong>Lire un fichier de mon ordinateur</strong><span>Sans upload · pas de limite de taille imposée · MP4, MOV, WebM</span><input type="file" accept=".mp4,.mov,.webm" onChange={e=>{const f=e.target.files?.[0];if(f)onLocal(f)}}/><small>Le fichier reste sur cet appareil. Après rechargement, sélectionnez-le à nouveau ; les annotations restent enregistrées.</small></label>}{error&&<p role="alert" className="error">{error}</p>}</div>
}
