'use client';
import {useState,type ReactNode} from 'react';
import Link from 'next/link';
import type {Match,Season,Player} from '@/lib/model';
import {labels,ratios,teamName} from '@/lib/model';
import {metric,type Summary} from '@/lib/engine';
import {eventLabel,isGoal} from '@/lib/actions';
import {positionedEvents,defensiveActions} from '@/lib/events';
import {SourceTemplate,hudTemplates,sourceAt,childNodes} from './hud-source-template';
import {Picker,Empty,fmt,date,time,Calendar} from './league-ui';
type Slots=Record<string,ReactNode>;
type Props=Record<string,Record<string,unknown>>;
const stamp=(s:number|null)=>s==null?'NON HORODATÉ':`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
export function SourceMatchHeader({match:m,season,admin,summaries}:{match:Match;season?:Season;admin:boolean;summaries:Summary[]}){
 const mvp=summaries.find(s=>s.player.id===m.mvpId),slots:Slots={'0.0.0':`${season?.name??'MATCH'} · JOURNÉE ${m.number} · ${m.status==='finished'?'TERMINÉ':m.status==='cancelled'?'ANNULÉ':'À VENIR'}`,'0.1.0.0':teamName(m,'A').slice(0,2).toUpperCase(),'0.1.0.1.0':teamName(m,'A'),'0.1.0.1.1':'ÉQUIPE A','0.1.1':m.status==='finished'?<><SourceTemplate node={sourceAt(hudTemplates.matchTop,'0.1.1.0')} slots={{'':fmt(m.scoreA,0)}}/><SourceTemplate node={sourceAt(hudTemplates.matchTop,'0.1.1.1')}/>{fmt(m.scoreB,0)}</>:'VS','0.1.2.0.0':teamName(m,'B'),'0.1.2.0.1':'ÉQUIPE B','0.1.2.1':teamName(m,'B').slice(0,2).toUpperCase(),'1.2':mvp?<Link href={'/joueurs/'+mvp.player.id}>{mvp.player.name}</Link>:'NON ATTRIBUÉ','1.3':mvp?teamName(m,m.participants.find(p=>p.playerId===mvp.player.id)?.team??''):'Aucun MVP enregistré'};
 [date(m.date,true),time(m.date),`${m.duration} min`,m.location||'À préciser',m.number].forEach((v,i)=>slots[`0.2.${i}.1`]=v);
 ['goals','assists','defensiveActions'].forEach((key,i)=>slots[`1.4.${i}`]=<>{fmt(mvp?.stats[key],0)}<SourceTemplate node={sourceAt(hudTemplates.matchTop,`1.4.${i}.0`)}/></>);
 return <section className="source-match-dashboard"><div className="mp"><SourceTemplate name="matchTop" slots={slots} props={{'0.1.1':{style:{whiteSpace:'nowrap'}},'0.0.1':{as:'a',href:'/admin?match='+m.id,style:{display:admin?'inline-flex':'none'}}}}/><div className="actions filterrow">{m.status==='scheduled'&&<Calendar match={m}/>}<Link className="button" href="/glossaire">Comprendre les stats <span className="stat-tip-mark" aria-hidden="true">i</span></Link>{admin&&<><Link className="button" href={'/admin?match='+m.id+'&step=video'}>Modifier la timeline</Link><Link className="button" href={'/admin?match='+m.id+'&step=result'}>Modifier toutes les stats</Link></>}</div>{m.notes&&<details className="importnote"><summary>À propos des données de ce match</summary><p>{m.notes}</p></details>}</div></section>;
}
export function SourceMatchDashboard({match:m,players,summaries,onSelect,onReplay,beforeDetails}:{match:Match;players:Player[];summaries:Summary[];onSelect:(id:string)=>void;onReplay:(seconds:number)=>void;beforeDetails?:ReactNode}){
 const [heatScope,setHeatScope]=useState('all'),[heatPlayer,setHeatPlayer]=useState('all'),[order,setOrder]=useState('rating');
 const name=(id:string)=>players.find(p=>p.id===id)?.name??'Joueur inconnu',rows=summaries.filter(s=>m.participants.some(p=>p.playerId===s.player.id));
 const events=[...m.events].sort((a,b)=>(a.timestamp??Infinity)-(b.timestamp??Infinity)),goals=events.filter(isGoal),timed=events.filter(e=>e.timestamp!=null),seconds=Math.max(m.duration*60,...timed.map(e=>e.timestamp!)),ticks=childNodes(sourceAt(hudTemplates.matchTimeline,'1.0'));
 const timeline:Slots={'0.1':`0 → ${stamp(seconds)} · ACTIONS ANNOTÉES · BUTS A AU-DESSUS, B EN DESSOUS`};
 timeline['1.0']=<><SourceTemplate node={ticks[0]}/>{Array.from({length:11},(_,i)=><span key={i}><SourceTemplate node={ticks[1]} props={{'':{style:{left:`${i*10}%`}}}}/><SourceTemplate node={ticks[2]} slots={{'':`${fmt(seconds*i/600,1)}′`}} props={{'':{style:{left:`${i*10}%`}}}}/></span>)}{timed.filter(e=>isGoal(e)||['FOUL','FOUL_COMMITTED','TACKLE','TACKLE_WON','INTERCEPTION','RECOVERY','BLOCK','CLEARANCE','SAVE','DUEL','DEFENSIVE_ACTION'].includes(e.type)).map((e,i)=>isGoal(e)?<SourceTemplate node={sourceAt(hudTemplates.matchTimeline,`1.0.${e.team==='B'?26:25}`)} key={e.id} slots={{'0':<>{name(e.playerId).toUpperCase()}<SourceTemplate node={sourceAt(hudTemplates.matchTimeline,'1.0.25.0.0')} slots={{'':`${stamp(e.timestamp)} · BUT ANNOTÉ`}}/></>}} props={{'':{role:m.video?'button':undefined,tabIndex:m.video?0:undefined,onClick:()=>m.video&&onReplay(e.timestamp!),onKeyDown:(event:React.KeyboardEvent)=>{if(m.video&&(event.key==='Enter'||event.key===' ')){event.preventDefault();onReplay(e.timestamp!)}},style:{left:`${e.timestamp!/seconds*100}%`,'--m':e.timestamp!/60,cursor:m.video?'pointer':'default',zIndex:i+1}}}}/>:defensiveActions.has(e.type)||e.type==='FOUL'||e.type==='FOUL_COMMITTED'?<SourceTemplate node={ticks[24]} key={e.id} props={{'':{title:`${stamp(e.timestamp)} · ${eventLabel(e)} · ${name(e.playerId)}`,style:{left:`${e.timestamp!/seconds*100}%`}}}}/>:null)}</>;
 const sum=(side:string,key:string):number|null=>{const team=m.participants.filter(p=>p.team===side);if(ratios[key]){const [n,d]=ratios[key],known=team.filter(p=>p.stats[n]!=null&&p.stats[d]!=null),denom=known.reduce((v,p)=>v+p.stats[d]!,0);return known.length&&denom?known.reduce((v,p)=>v+p.stats[n]!,0)/denom*100:null;}const values=team.flatMap(p=>p.stats[key]==null?[]:[p.stats[key]!]);return values.length?values.reduce((n,v)=>n+v,0):null;};
 const summary:Slots={'0.1.0':m.status==='finished'?`Match #${m.number} : ${teamName(m,'A')} ${fmt(m.scoreA,0)} – ${fmt(m.scoreB,0)} ${teamName(m,'B')}. ${goals.length} buts annotés dans la timeline. Les chiffres ci-contre proviennent des statistiques renseignées.`:'Les résultats apparaîtront après la saisie du match.','1.0.1':`${teamName(m,'A')} vs ${teamName(m,'B')}`,'1.1.0.0':teamName(m,'A'),'1.1.0.1':teamName(m,'B')},summaryProps:Props={};
 const moments=goals.slice(0,5);for(let i=0;i<5;i++){summary[`0.1.${i+2}.0`]=moments[i]?stamp(moments[i].timestamp):'';summary[`0.1.${i+2}.1`]=moments[i]?`But de ${name(moments[i].playerId)}${moments[i].relatedPlayerId?' · passe de '+name(moments[i].relatedPlayerId!):''}`:'';summaryProps[`0.1.${i+2}`]={style:{display:moments[i]?'flex':'none'}};}if(!moments.length)summary['0.1.1']='AUCUN BUT ANNOTÉ';
 ['possession','shots','shotsOnTarget','passesAttempted','passPct','tackles','interceptions','duelsWon','saves','fouls'].forEach((key,i)=>{const a=sum('A',key),b=sum('B',key),base=`1.1.${i+1}`;summary[`${base}.0`]=fmt(a,key==='passPct'?1:0)+(a!=null&&key==='passPct'?' %':'');summary[`${base}.2`]=fmt(b,key==='passPct'?1:0)+(b!=null&&key==='passPct'?' %':'');summaryProps[`${base}.1.1.0`]={style:{width:`${a==null||b==null?0:a/(a+b||1)*100}%`}};summaryProps[`${base}.1.1.1`]={style:{width:`${a==null||b==null?0:b/(a+b||1)*100}%`}};});
 const leaders:Slots={};['goals','assists','shots','saves','tackles','interceptions','duelsWon','defensiveActions'].forEach((key,i)=>{const ranked=rows.filter(s=>metric(s,key)!=null).sort((a,b)=>metric(b,key)!-metric(a,key)!),card=sourceAt(hudTemplates.matchLeaders,`1.${i}`);leaders[`1.${i}`]=<><SourceTemplate node={sourceAt(card,'0')} slots={{'0':labels[key].toUpperCase()}}/>{ranked[0]?<SourceTemplate node={{...sourceAt(card,'1'),tag:'a'}} slots={{'0':ranked[0].player.name.slice(0,2).toUpperCase(),'1':ranked[0].player.name,'2':fmt(metric(ranked[0],key),0)}} props={{'':{href:'/joueurs/'+ranked[0].player.id}}}/>:<p className="muted">NON OBSERVÉ</p>}{ranked.slice(1,3).map((s,j)=><SourceTemplate key={s.player.id} node={{...sourceAt(card,'2'),tag:'a'}} slots={{'0':`${j+2} · ${s.player.name}`,'1':fmt(metric(s,key),0)}} props={{'':{href:'/joueurs/'+s.player.id}}}/>)}</>;});
 const heat=sourceAt(hudTemplates.matchHeatmap,'1.4.0'),heatNodes=childNodes(heat),allPoints=positionedEvents([m]),points=allPoints.filter(e=>(heatScope==='all'||e.team===heatScope)&&(heatPlayer==='all'||e.playerId===heatPlayer)),heatSlots:Slots={'0.1':'POSITIONS ANNOTÉES · ÉQUIPE A → · ÉQUIPE B ←','1.3.0':<><Picker label="Équipe de la heatmap" value={heatScope} onChange={setHeatScope} options={[{value:'all',label:'Tous'},{value:'A',label:teamName(m,'A')},{value:'B',label:teamName(m,'B')}]}/><Picker label="Joueur de la heatmap" value={heatPlayer} onChange={setHeatPlayer} options={[{value:'all',label:'Tous les joueurs'},...rows.map(s=>({value:s.player.id,label:s.player.name}))]}/></>,'1.4.0':<>{heatNodes.slice(0,17).map((n,i)=><SourceTemplate node={n} key={i}/>)}{points.map(e=><g key={e.id} className={'hg '+(e.team==='B'?'t-b':'t-v')} style={{mixBlendMode:'screen'}}><title>{name(e.playerId)} · {eventLabel(e)}</title><SourceTemplate node={sourceAt(heat,'17.0')} props={{'':{cx:e.team==='B'?400-e.position!.x*4:e.position!.x*4,cy:e.team==='B'?200-e.position!.y*2:e.position!.y*2,fill:`url(#${e.team==='B'?'gb':'gv'})`,r:18}}}/></g>)}</>};
 const table=sourceAt(hudTemplates.matchTable,'1'),tr=sourceAt(table,'1'),columns=['goals','assists','shots','shotsOnTarget','saves','tackles','interceptions','blocks','duelsWon','fouls','defensiveActions'];
 const tableSlots:Slots={'1':<><SourceTemplate node={sourceAt(table,'0')}/>{[...rows].sort((a,b)=>(metric(b,order)??-Infinity)-(metric(a,order)??-Infinity)).map((s,i)=>{const cell:Slots={'0':String(i+1).padStart(2,'0'),'1.0':s.player.name.slice(0,2).toUpperCase(),'1.1':<>{s.player.name}{s.player.id===m.mvpId&&<SourceTemplate node={sourceAt(tr,'1.1.0')}/>}<SourceTemplate node={sourceAt(tr,'1.1.1')} slots={{'':`${teamName(m,m.participants.find(p=>p.playerId===s.player.id)?.team??'')} · NOTE ${fmt(s.stats.rating,2)}`}}/></>},cp:Props={'':{className:'pr2 in'+(s.player.id===m.mvpId?' mv':''),role:'button',tabIndex:0,onClick:()=>onSelect(s.player.id),onKeyDown:(e:React.KeyboardEvent)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(s.player.id)}},style:{'--i':i,cursor:'pointer'}}};columns.forEach((key,j)=>{const v=metric(s,key),max=Math.max(...rows.flatMap(p=>metric(p,key)==null?[]:[metric(p,key)!]));cell[String(j+2)]=fmt(v,0);cp[String(j+2)]={className:v==null||v===0?'z':v===max?'mx':''};});return <SourceTemplate node={tr} key={s.player.id} slots={cell} props={cp}/>})}</>};
 const detail=sourceAt(hudTemplates.matchDetails,'1.5'),eventRows:Slots={'1.5':events.length?events.map((e,i)=>{const kind=isGoal(e)?'but':e.type==='FOUL'||e.type==='FOUL_COMMITTED'?'faute':['TACKLE','INTERCEPTION','RECOVERY','BLOCK','CLEARANCE','SAVE','DUEL','TACKLE_WON','INTERCEPTION_WON','DEFENSIVE_ACTION'].includes(e.type)?'def':'other',node=sourceAt(detail,kind==='but'?'2':kind==='faute'?'7':'1');return <SourceTemplate node={node} key={e.id} slots={{'0':stamp(e.timestamp),'1':kind==='but'?'●':kind==='faute'?'◇':'◆','2':<>{eventLabel(e)} · {name(e.playerId)}{e.relatedPlayerId&&<SourceTemplate node={sourceAt(detail,'2.2.0')} slots={{'':` → ${name(e.relatedPlayerId)}`}}/>}</>,'3':m.video&&e.timestamp!=null?<button className="textbutton" onClick={()=>onReplay(e.timestamp!)}>REPLAY ↗</button>:''}} props={{'':{className:`ev2 k-${kind} ${e.team==='B'?'B':'V'} in`,style:{'--i':Math.min(i,12)}}}}/>}):<Empty>Aucune action annotée. Les statistiques historiques restent disponibles au-dessus.</Empty>};
 return <><section className="source-match-dashboard"><div className="mp"><SourceTemplate name="matchTimeline" slots={timeline}/>{events.some(e=>e.timestamp==null)&&<p className="muted">{events.filter(e=>e.timestamp==null).length} actions sans horodatage restent visibles dans le détail.</p>}<SourceTemplate name="matchSummary" slots={summary} props={summaryProps}/><p className="muted">Les sommes peuvent être partielles. La possession n’est pas mesurée ; elle reste inconnue.</p><SourceTemplate name="matchLeaders" slots={leaders}/><SourceTemplate name="matchHeatmap" slots={heatSlots} props={{'1.0':{style:{display:'none'}},'1.1':{style:{display:'none'}},'1.2':{style:{display:'none'}}}}/>{!points.length&&<p className="muted">Aucune position annotée : aucune zone d’activité n’est inventée.</p>}<div className="controls filterrow"><Picker label="Trier les statistiques du match" value={order} onChange={setOrder} options={[{value:'rating',label:'Note'},{value:'goals',label:'Buts'},{value:'assists',label:'Passes décisives'},{value:'defensiveActions',label:'Actions défensives'}]}/></div><SourceTemplate name="matchTable" slots={tableSlots}/></div></section>{beforeDetails}<section className="source-match-dashboard"><div className="mp"><SourceTemplate name="matchDetails" slots={eventRows}/></div></section></>;
}
