'use client';
import { useState, type MouseEvent } from 'react';
import type { Match } from '@/lib/model';
import { actionDefinitions, actionLabels, type Point } from '@/lib/actions';
import { SourceTemplate, hudTemplates, sourceAt, childNodes } from './hud-source-template';
import { SourceCheckbox } from './league-kit';
type Stage = 'actor' | 'action' | 'outcome' | 'details' | 'player' | 'position';
export function ActionWizard({ match, actor, type, outcome, tags, mate, opponent, stamp, tracking, name, onActor, onType, onOutcome, onTags, onMate, onOpponent, onStamp, onTracking, onFreeze, onCommit }: {
  match: Match; actor: string; type: string; outcome: string; tags: string[]; mate: string; opponent: string; stamp: string; tracking: boolean; name: (id: string) => string;
  onActor: (id: string) => void; onType: (key: string) => void; onOutcome: (key: string) => void; onTags: (tags: string[]) => void; onMate: (id: string) => void; onOpponent: (id: string) => void; onStamp: (value: string) => void; onTracking: (value: boolean) => void; onFreeze: () => void; onCommit: (position: Point | null) => boolean;
}) {
  const [stage, setStage] = useState<Stage>('actor'), [combine, setCombine] = useState(false), [x,setX]=useState(''),[y,setY]=useState('');
  const definition = actionDefinitions[type] ?? {label:type,outcomes:[],tags:[]};
  const side = match.participants.find(p => p.playerId === actor)?.team;
  const mateNeeded = type === 'PASS', mateOptional = type === 'SHOT' && outcome === 'GOAL';
  const opponentNeeded = ['DRIBBLE', 'DUEL', 'TACKLE', 'FOUL'].includes(type) || type === 'SHOT' && outcome === 'BLOCKED';
  const optionalOpponent = ['BLOCK', 'SAVE', 'INTERCEPTION'].includes(type);
  const relevantTags = definition.tags.filter(tag => !['KEY_PASS', 'ASSIST'].includes(tag));
  const nextPlayer = () => setStage(mateNeeded || mateOptional || opponentNeeded || optionalOpponent ? 'player' : 'position');
  const stages: [Stage, string, string][] = [['actor', 'AUTEUR', name(actor)], ['action', 'ACTION', definition.label], ['outcome', 'RÉSULTAT', actionLabels[outcome] ?? '—'], ['details', type==='PASS'?'TYPE DE PASSE':'PRÉCISION', tags.map(tag => actionLabels[tag]).join(' · ') || 'À choisir'], ['player', mateNeeded || mateOptional ? 'RECEVEUR / PASSEUR' : 'ADVERSAIRE', name(mate || opponent) || 'À choisir'], ['position', 'POSITION', 'Dernière étape']];
  const index = stages.findIndex(([key]) => key === stage);
  const heading: Record<Stage, string> = { actor: 'Qui fait l’action ?', action: 'Quelle action ?', outcome: 'Quel résultat ?', details: type === 'PASS' ? 'Quel type de passe ?' : 'Quelle précision ?', player: mateNeeded ? 'Qui reçoit la passe ?' : mateOptional ? 'Qui fait la passe décisive ?' : 'Quel adversaire ?', position: 'Position finale · un clic enregistre' };
  const commit=(point:Point|null)=>{if(onCommit(point)){setStage(type==='PASS'&&outcome==='COMPLETED'?'action':'actor');setX('');setY('');setCombine(false);onTags([]);onOutcome('')}};
  const place=(event:MouseEvent<HTMLDivElement>)=>{const rect=event.currentTarget.getBoundingClientRect();commit({x:Math.round(Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100))),y:Math.round(Math.max(0,Math.min(100,(event.clientY-rect.top)/rect.height*100)))})};
  const option=(label:string,key:string,choose:()=>void,active=false)=><SourceTemplate key={key} node={sourceAt(hudTemplates.wizardQuestion,'0.2.1')} slots={{'':label}} props={{'':{as:'button',role:'button','aria-checked':undefined,type:'button',htmlFor:undefined,onClick:choose,'aria-pressed':active,className:'op'+(active?' selected':'')}}}/>;
  const options=stage==='actor'?match.participants.filter(p=>p.team).map(p=>option(name(p.playerId),p.playerId,()=>{onFreeze();onActor(p.playerId);setStage('action')}))
    :stage==='action'?Object.entries(actionDefinitions).map(([key,d])=>option(d.label,key,()=>{onType(key);setCombine(false);setStage(d.outcomes.length?'outcome':d.tags.length?'details':['BLOCK','INTERCEPTION'].includes(key)?'player':'position')}))
    :stage==='outcome'?definition.outcomes.map(key=>option(actionLabels[key],key,()=>{onOutcome(key);setStage(relevantTags.length?'details':type==='PASS'||['DRIBBLE','DUEL','TACKLE','FOUL','SAVE'].includes(type)||type==='SHOT'&&['GOAL','BLOCKED'].includes(key)?'player':'position')}))
    :stage==='details'?[option(type==='PASS'?'Normale':'Sans précision','normal',()=>{onTags([]);nextPlayer()}),...relevantTags.map(tag=>option(actionLabels[tag],tag,()=>{onTags(combine?(tags.includes(tag)?tags.filter(x=>x!==tag):[...tags,tag]):[tag]);if(!combine)nextPlayer()},tags.includes(tag))),option('Type inconnu','unknown',()=>{onTags([]);nextPlayer()})]
    :stage==='player'?match.participants.filter(p=>p.playerId!==actor&&(mateNeeded||mateOptional?p.team===side:p.team&&p.team!==side)).map(p=>option(name(p.playerId),p.playerId,()=>{if(mateNeeded||mateOptional)onMate(p.playerId);else onOpponent(p.playerId);setStage('position')})):[];
  return <section className="source-action-wizard"><div className="an">
    <SourceTemplate name="wizardState" slots={{'0':`BROUILLON LOCAL · ${match.events.length} ACTIONS`}} props={{'1':{hidden:true},'2':{hidden:true}}}/>
    <SourceTemplate name="wizardTime" slots={{'0':<label>TEMPS DU MATCH<input aria-label="Temps de l’action guidée" value={stamp} onChange={e=>onStamp(e.target.value)}/></label>,'1':'TEMPS FIGÉ','3':'UNE QUESTION À LA FOIS','4':'Figer le temps de la vidéo'}} props={{'4':{as:'button',type:'button',onClick:onFreeze}}}/>
    <SourceTemplate name="wizardSteps" slots={{'':stages.map(([key,label,value],i)=><SourceTemplate key={key} node={childNodes(hudTemplates.wizardSteps)[i]} slots={{'':<>{i<index?'✓ ':''}{label}<b>{i<=index?value:'Ensuite'}</b></>}} props={{'':{as:'button',type:'button',className:i<index?'done':i===index?'cur':'nx',disabled:i>index,onClick:()=>setStage(key)}}}/>)}}/>
    <SourceTemplate name="wizardQuestion" slots={{'0.0':<>{heading[stage]}<span className="rq">{stage==='details'||stage==='position'||stage==='player'&&(mateOptional||optionalOpponent)?'FACULTATIF':'OBLIGATOIRE'}</span></>,'0.1':stage==='position'?'Placez le point réel de l’auteur, ou gardez une position inconnue.':'Un clic sur une réponse fait avancer à l’étape suivante.','0.2':options,'0.3':stage==='details'?<><label><SourceCheckbox checked={combine} onCheckedChange={setCombine}/>COMBINER PLUSIEURS CRITÈRES</label>{combine&&<button type="button" className="bt g" onClick={nextPlayer}>Continuer →</button>}</>:stage==='player'&&!mateNeeded&&!opponentNeeded?<button className="bt" type="button" onClick={()=>{onMate('');onOpponent('');setStage('position')}}>Non renseigné · continuer</button>:null,'0.4':type==='PASS'?'Passe clé et passe décisive se déduisent du lien avec un tir ou un but.':null,'1.1.1':name(actor),'1.2.1':stamp||'Temps inconnu','1.3.1':definition.label,'1.4.1':actionLabels[outcome]??'—','1.5.1':tags.map(t=>actionLabels[t]).join(' · ')||'—','1.6.1':name(mate||opponent)||'—','1.7.1':'—'}} props={{'0.3':{hidden:stage!=='details'&&!(stage==='player'&&!mateNeeded&&!opponentNeeded)},'0.4':{hidden:type!=='PASS'}}}/>
    {stage==='position'&&<><label className="checklabel"><SourceCheckbox checked={tracking} onCheckedChange={onTracking}/> Recalculer les catégories annotées à partir de la timeline (remplace leurs valeurs manuelles).</label>
      <SourceTemplate name="wizardPosition" slots={{'0.1':`SENS D’ATTAQUE ${side==='B'?'←':'→'} BUT ADVERSE`,'1.0.0':`${name(actor)} · ${definition.label} ${actionLabels[outcome]??''}${mate?' → '+name(mate):''}`,'1.0.1':'Position réelle de l’auteur au moment de l’action. Pour une passe : le point de départ.','1.2.0':'COORDONNÉES DU TERRAIN','1.2.1.0':<label>X<input aria-label="Coordonnée X" type="number" min={0} max={100} value={x} onChange={e=>setX(e.target.value)}/></label>,'1.2.1.1':<label>Y<input aria-label="Coordonnée Y" type="number" min={0} max={100} value={y} onChange={e=>setY(e.target.value)}/></label>,'1.2.1.2':'CONFIRMER'}} props={{'0':{onClick:place,role:'img','aria-label':'Terrain : cliquez pour placer et enregistrer l’auteur'},'0.0.1':{hidden:true},'0.2':{hidden:true},'0.3':{hidden:true},'0.4':{hidden:true},'0.5':{hidden:true},'0.6':{hidden:true},'1.1':{hidden:true},'1.2.1.2':{as:'button',type:'button',disabled:x===''||y===''||!Number.isFinite(+x)||!Number.isFinite(+y)||+x<0||+x>100||+y<0||+y>100,onClick:()=>commit({x:+x,y:+y})},'1.3':{as:'button',type:'button',onClick:()=>commit(null)}}}/></>}
    {!match.participants.some(p=>p.team)&&<p className="note">Ajoutez les participants et leurs équipes avant d’annoter ce match.</p>}
  </div></section>;
}
