'use client';
import {useId,useRef,useState} from 'react';
import type {Match,Settings} from '@/lib/model';
import {labels} from '@/lib/model';
import type {Summary} from '@/lib/engine';
import {richFacts} from '@/lib/insights';
import {positionedEvents,offensiveActions,defensiveActions} from '@/lib/events';
import {playStyles} from '@/lib/performance';
import {Picker,fmt,Empty} from './league-ui';
export function FactsCarousel({summaries,matches,settings}:{summaries:Summary[];matches:Match[];settings:Settings}){const scroll=useRef<HTMLDivElement>(null);const facts=richFacts(summaries,matches,settings);return <section className="factssection"><div className="sectionhead"><div><span className="eyebrow accent">AU VESTIAIRE</span><h2>Il fallait le savoir.</h2></div><div className="controls"><button className="button" aria-label="Facts précédents" onClick={()=>scroll.current?.scrollBy({left:-340,behavior:'smooth'})}>←</button><button className="button" aria-label="Facts suivants" onClick={()=>scroll.current?.scrollBy({left:340,behavior:'smooth'})}>→</button></div></div><div className="factcarousel" ref={scroll}>{facts.map((f,i)=><a className="fact" key={f.text} href={f.matchId?'/matchs/'+f.matchId:'/joueurs/'+f.playerId}><span className="eyebrow">{String(i+1).padStart(2,'0')} / {f.category}</span><p>{f.text}</p><span className="accent">Voir de plus près ↗</span></a>)}</div>{!facts.length&&<Empty>Quelques matchs de plus pour faire parler les chiffres.</Empty>}</section>}
export function PlayStyles({playerId,matches}:{playerId:string;matches:Match[]}){const styles=playStyles(playerId,matches);return <section className="panel playstyles"><span className="eyebrow accent">PLAYSTYLES</span><h2>{styles[0]?.name??'Un style à découvrir'}</h2>{!styles.length?<p className="muted">Au moins 3 matchs renseignés et 3 joueurs comparables. Aucun style attribué au hasard.</p>:styles.map((s,i)=><details key={s.name} open={i===0}><summary>{i===0?'Principal':'Secondaire'} · {s.name} <b>{s.score} % de compatibilité</b></summary><p>Repère pédagogique : {s.reference}. Une référence de style, pas une équivalence de niveau.</p><h4>Pourquoi ce PlayStyle ?</h4>{s.evidence.map(e=><div className="statrow" key={e.key}><span>{labels[e.key]} / match</span><b>{fmt(e.value)} · percentile {Math.round(e.percentile)}</b></div>)}<p className="muted">Moyenne sur les 20 derniers matchs renseignés : le style principal est conservé si l’écart de compatibilité reste inférieur à 8 points.</p></details>)}</section>}
export function RatingExplanation({match,playerId}:{match:Match;playerId:string}){const p=match.participants.find(p=>p.playerId===playerId);return <details className="panel ratingexplanation"><summary>Pourquoi {fmt(p?.final_rating??p?.stats.rating)} ?</summary><p>Base 6,0 · note entre 3,0 et 10,0. Comparaison des familles renseignées avec les performances du groupe.</p>{p?.ratingExplanation?.map(s=><p key={s}>{s}</p>)}<p className="muted">Automatique : {fmt(p?.auto_rating)} · Override : {fmt(p?.admin_rating)} · Finale : {fmt(p?.final_rating)}</p></details>}
// Pitch lines, stripe geometry and radial gradients from frame 03251b8d.
export function Heatmaps({matches,playerId,playerName}:{matches:Match[];playerId?:string;playerName?:string}){
 const [mode,setMode]=useState('all'),[scope,setScope]=useState('player');
 const id=useId().replaceAll(':',''),green=id+'-green',white=id+'-white';
 const all=positionedEvents(matches).filter(e=>!playerId||(scope==='player'?e.playerId===playerId:matches.find(m=>m.id===e.matchId)?.participants.find(p=>p.playerId===playerId)?.team===e.team));
 const points=all.filter(e=>mode==='attack'?offensiveActions.has(e.type):mode==='defense'?defensiveActions.has(e.type):mode==='shots'?['GOAL','SHOT','SHOT_ON_TARGET','SHOT_OFF_TARGET','SHOT_BLOCKED'].includes(e.type):mode==='passes'?['PASS','PASS_COMPLETED','PASS_FAILED','KEY_PASS','LONG_PASS','LONG_PASS_COMPLETED','CROSS','CROSS_COMPLETED'].includes(e.type)&&!!e.metadata.endPosition:true);
 const min=mode==='shots'?3:5;
 return <div className="ds-individual"><section className="card hm source-heatmap"><div className="hmbar"><b>HEATMAP{playerName?' · '+playerName.toUpperCase():''}</b>{playerId&&<div className="tabs"><button type="button" aria-pressed={scope==='player'} onClick={()=>setScope('player')}>JOUEUR</button><button type="button" aria-pressed={scope==='team'} onClick={()=>setScope('team')}>SON ÉQUIPE</button></div>}</div><div className="source-heatmap-controls"><Picker label="Carte des actions" value={mode} onChange={setMode} options={[{value:'all',label:'Heatmap générale'},{value:'attack',label:'Offensive'},{value:'defense',label:'Défensive'},{value:'shots',label:'Shot map'},{value:'passes',label:'Passing map'}]}/><small>{points.length} actions positionnées</small></div>{points.length<min?<Empty>Carte disponible à partir de {min} actions positionnées ({points.length}/{min}).</Empty>:<div className="pw"><svg viewBox="0 0 400 200" width="1200" height="600" className="pt w" style={{display:'block',width:'100%',height:'auto'}} role="img" aria-label={`${mode} : ${points.length} actions`}><defs><radialGradient id={green}><stop offset="0" stopColor="#8BE36B" stopOpacity=".85"/><stop offset=".6" stopColor="#56B947" stopOpacity=".35"/><stop offset="1" stopColor="#56B947" stopOpacity="0"/></radialGradient><radialGradient id={white}><stop offset="0" stopColor="#E9ECE6" stopOpacity=".8"/><stop offset=".6" stopColor="#AEB8B2" stopOpacity=".3"/><stop offset="1" stopColor="#AEB8B2" stopOpacity="0"/></radialGradient></defs><rect x="0" y="0" width="400" height="200" fill="#0E120E"/>{[0,50,100,150,200,250,300,350].map((x,i)=><rect key={x} x={x} y="0" width="25" height="200" fill={i%2?'#101510':'#0E120E'}/>)}<rect x="4" y="4" width="392" height="192" stroke="#2A322A" strokeWidth="1" fill="none"/><line x1="200" y1="4" x2="200" y2="196" stroke="#2A322A" strokeWidth="1" fill="none"/><circle cx="200" cy="100" r="26" stroke="#2A322A" strokeWidth="1" fill="none"/><rect x="4" y="62" width="34" height="76" stroke="#2A322A" strokeWidth="1" fill="none"/><rect x="362" y="62" width="34" height="76" stroke="#2A322A" strokeWidth="1" fill="none"/><rect x="4" y="82" width="12" height="36" stroke="#2A322A" strokeWidth="1" fill="none"/><rect x="384" y="82" width="12" height="36" stroke="#2A322A" strokeWidth="1" fill="none"/>{points.map(e=>{
 const p=e.position!,end=e.metadata.endPosition as {x:number;y:number}|undefined,failed=e.type==='PASS_FAILED'||e.type==='PASS'&&e.metadata.outcome==='FAILED',goal=e.type==='GOAL'||e.type==='SHOT'&&e.metadata.outcome==='GOAL';
 return <g key={e.matchId+e.id} style={{mixBlendMode:'screen'}}><title>{e.type} · X {p.x}, Y {p.y}</title>{mode==='passes'&&end&&<line x1={p.x*4} y1={p.y*2} x2={end.x*4} y2={end.y*2} stroke={failed?'#8E978C':'#56B947'} strokeDasharray={failed?'4 3':undefined} strokeWidth="1.5"/>}<circle cx={p.x*4} cy={p.y*2} r={mode==='shots'||mode==='passes'?4:18} fill={mode==='shots'||mode==='passes'?goal?'#E9ECE6':'#56B947':`url(#${e.team==='B'?white:green})`} opacity={mode==='shots'||mode==='passes'?.8:1}/>{mode==='passes'&&end&&<circle cx={end.x*4} cy={end.y*2} r="2" fill="#E9ECE6"/>}</g>;
 })}</svg></div>}<div className="lg"><span>PEU</span><span className="bar"/><span>BEAUCOUP</span></div><p className="source-heatmap-note">X : notre but → but adverse. Y : gauche → droite. Actions non annotées non extrapolées.</p></section></div>;
}
