'use client';
import {useEffect,useRef,useState} from 'react';
import type {League,Match,MatchEvent} from '@/lib/model';
import {teamName,eventMap} from '@/lib/model';
import {coordinates,projectEvents,zone,eventKeys} from '@/lib/events';
import {actionDefinitions as definitions,actionLabels,eventLabel,isV2,secondaryAssistCredits,type Point,type Scene} from '@/lib/actions';
import {VideoPlayer,VideoSource,type VideoPlayerHandle} from './league-video';
const clock=(s:number|null)=>s==null?'':`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
export function Analyzer({match:m,data,onChange,onSave,busy}:{match:Match;data:League;onChange:(m:Match)=>void;onSave?:(m:Match)=>void;busy?:boolean}){
const [focus,setFocus]=useState(false),[localVideo,setLocalVideo]=useState(''),[localName,setLocalName]=useState(''),[context,setContext]=useState(false),[role,setRole]=useState<'actor'|'mate'|'opponent'>('actor'),[drawer,setDrawer]=useState(false),[legacy,setLegacy]=useState(false),[view,setView]=useState('builder'),[actor,setActor]=useState(m.participants[0]?.playerId??''),[mate,setMate]=useState(''),[opponent,setOpponent]=useState(''),[type,setType]=useState('SHOT'),[outcome,setOutcome]=useState('GOAL'),[tags,setTags]=useState<string[]>([]),[stamp,setStamp]=useState('00:00'),[manual,setManual]=useState(false),[editing,setEditing]=useState<string|null>(null),[sequence,setSequence]=useState(()=>crypto.randomUUID()),[scene,setScene]=useState<Scene>(()=>([...m.events].reverse().find(e=>e.metadata.scene)?.metadata.scene as Scene)??{players:{},ball:null}),[selected,setSelected]=useState(m.participants[0]?.playerId??''),[end,setEnd]=useState<Point|null>(null),[linked,setLinked]=useState(''),[complete,setComplete]=useState(false),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[tracking,setTracking]=useState(false),[past,setPast]=useState<{match:Match;scene:Scene}[]>([]),[future,setFuture]=useState<{match:Match;scene:Scene}[]>([]);
useEffect(()=>()=>{if(localVideo)URL.revokeObjectURL(localVideo)},[localVideo]);
const video=useRef<VideoPlayerHandle>(null),root=useRef<HTMLDivElement>(null);const participant=m.participants.find(p=>p.playerId===actor),side=participant?.team??'A',definition=legacy?{label:type.replaceAll('_',' '),outcomes:[],tags:[]}:definitions[type];
const name=(id:string)=>data.players.find(p=>p.id===id)?.name??id;
const secondaryCredits=secondaryAssistCredits(m.events);
const point=scene.players[actor]??scene.ball;const normalized=point?(side==='B'?{x:100-point.x,y:100-point.y}:point):null;
function remember(next:Match,nextScene=scene){setPast(p=>[...p.slice(-49),{match:structuredClone(m),scene:structuredClone(scene)}]);setFuture([]);setScene(nextScene);onChange(next)}
function undo(){const prev=past.at(-1);if(!prev)return;setFuture(p=>[...p,{match:structuredClone(m),scene:structuredClone(scene)}]);setPast(p=>p.slice(0,-1));setScene(prev.scene);onChange({...prev.match,video:m.video});setEditing(null)}
function redo(){const next=future.at(-1);if(!next)return;setPast(p=>[...p,{match:structuredClone(m),scene:structuredClone(scene)}]);setFuture(p=>p.slice(0,-1));setScene(next.scene);onChange({...next.match,video:m.video});setEditing(null)}
function chooseType(v:string){setContext(true);setRole(v==='PASS'?'mate':['DRIBBLE','DUEL','TACKLE','FOUL','SAVE','BLOCK'].includes(v)?'opponent':'actor');setLegacy(false);setType(v);setOutcome(definitions[v]?.outcomes[0]??'');setTags([]);setLinked('');setEnd(null);if(!editing&&!manual&&(localVideo||m.video))setStamp(clock(video.current?.time()??0))}
function chooseActor(id:string){setContext(true);setRole('actor');setDrawer(false);setActor(id);setSelected(id);setMate('');setOpponent('');setLinked('')}
function pickPlayer(id:string){const p=m.participants.find(p=>p.playerId===id);if(role==='mate'&&p?.team===side&&id!==actor){setMate(id);setRole('actor');setContext(true);return}if(role==='opponent'&&p?.team&&p.team!==side){setOpponent(id);setRole('actor');setContext(true);return}chooseActor(id)}
function place(p:Point,id=selected){if(!id)return;setContext(true);const next=id==='ball'?{...scene,ball:p}:id==='target'?scene:{...scene,players:{...scene.players,[id]:p}};if(id==='target')setEnd(side==='B'?{x:100-p.x,y:100-p.y}:p);else{setPast(a=>[...a.slice(-49),{match:structuredClone(m),scene:structuredClone(scene)}]);setFuture([]);setScene(next)}}
function remove(id:string){const next=m.events.filter(e=>e.id!==id).map(e=>e.metadata.linkedEventId===id?{...e,metadata:{...e.metadata,linkedEventId:null}}:e);remember(projectEvents({...m,events:next}));if(editing===id)setEditing(null)}
function submit(){setMessage('');if(!participant?.team)return setMessage('Sélectionnez un joueur affecté à une équipe.');const effective=!manual&&!editing&&(localVideo||m.video)?clock(video.current?.time()??0):stamp;if(!/^\d{1,4}:[0-5]\d$/.test(effective))return setMessage('Temps attendu : mm:ss (jusqu’à 120:00 et au-delà).');if(!legacy&&(['DRIBBLE','DUEL','TACKLE','FOUL'].includes(type)||(type==='SHOT'&&outcome==='BLOCKED'))&&!opponent)return setMessage('Sélectionnez l’adversaire.');if(!legacy&&type==='PASS'&&!mate)return setMessage('Sélectionnez le receveur.');if(type==='PASS'&&outcome==='FAILED'&&tags.includes('ASSIST'))return setMessage('Une passe ratée ne peut être décisive.');const [min,sec]=effective.split(':').map(Number);const old=m.events.find(e=>e.id===editing);const target=scene.players[mate];const targetPoint=target?(side==='B'?{x:100-target.x,y:100-target.y}:target):end;
const e:MatchEvent={id:editing??crypto.randomUUID(),playerId:actor,team:participant.team,type,timestamp:min*60+sec,relatedPlayerId:legacy||type==='PASS'||(type==='SHOT'&&outcome==='GOAL')?mate||null:null,metadata:legacy?{...old?.metadata,position:normalized,endPosition:end,shotPosition:undefined,zone:undefined}:{schemaVersion:2,atomic:true,sequenceId:sequence,outcome:outcome||null,tags,opponentPlayerId:opponent||null,linkedEventId:linked||null,position:normalized,endPosition:type==='PASS'?targetPoint:null,scene:structuredClone(scene),createdAt:old?.metadata.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString()}};
const candidateEvents=editing?m.events.map(x=>x.id===editing?e:x):[...m.events,e];const newKeys=[...eventKeys(e),...(secondaryAssistCredits(candidateEvents).length?['secondaryAssists']:[])].filter(k=>!m.trackedKeys.includes(k));if(!tracking&&newKeys.some(k=>m.participants.some(p=>(p.stats[k]??0)>0)))return setMessage('Activez « Recalculer les catégories annotées » : ces catégories contiennent déjà des statistiques manuelles.');
let events=editing?m.events.map(x=>x.id===editing?e:x):[...m.events,e];if(old&&!isV2(old)&&!legacy&&!old.metadata.atomic&&old.timestamp!=null){const groups=[['SHOT','SHOT_ON_TARGET','SHOT_OFF_TARGET','SHOT_BLOCKED','GOAL'],['PASS_ATTEMPT','PASS_COMPLETED','PASS_FAILED'],['DRIBBLE_ATTEMPT','DRIBBLE_COMPLETED','DRIBBLE_FAILED'],['DUEL','DUEL_WON','DUEL_LOST']];const group=groups.find(g=>g.includes(old.type));if(group)events=events.filter(x=>x.id===e.id||x.metadata.atomic||x.playerId!==old.playerId||x.timestamp!==old.timestamp||!group.includes(x.type))}events=events.map(x=>{const id=x.metadata.linkedEventId;if(!id)return x;const target=events.find(y=>y.id===id);const valid=target&&(x.type==='SHOT'?x.metadata.outcome==='GOAL'&&target.type==='PASS'&&target.metadata.outcome==='COMPLETED'&&target.playerId===x.relatedPlayerId&&target.relatedPlayerId===x.playerId:['SAVE','BLOCK'].includes(x.type)&&target.type==='SHOT'&&target.playerId===x.metadata.opponentPlayerId&&target.metadata.outcome===(x.type==='SAVE'?'ON_TARGET':'BLOCKED'));return valid?x:{...x,metadata:{...x.metadata,linkedEventId:null}}});remember(projectEvents({...m,events}));setEditing(null);if(legacy){setLegacy(false);setType('SHOT');setOutcome('GOAL')}setManual(false);setStamp(effective);setContext(false);setMessage('Action enregistrée dans le brouillon. Enregistrez le match pour publier.');}
function edit(e:MatchEvent){setContext(true);if(e.timestamp!=null)video.current?.seek(e.timestamp);setEditing(e.id);setActor(e.playerId);setSelected(e.playerId);setMate(e.relatedPlayerId??'');setOpponent(String(e.metadata.opponentPlayerId??''));setStamp(clock(e.timestamp));setManual(true);setLinked(String(e.metadata.linkedEventId??''));setSequence(String(e.metadata.sequenceId??sequence));setEnd((e.metadata.endPosition as Point)??null);if(e.metadata.scene)setScene(structuredClone(e.metadata.scene as Scene));else {const p=coordinates(e.metadata);setScene({players:p?{[e.playerId]:e.team==='B'?{x:100-p.x,y:100-p.y}:p}:{},ball:null})}setLegacy(!isV2(e));if(isV2(e)){setType(e.type);setOutcome(String(e.metadata.outcome??''));setTags((e.metadata.tags as string[])??[])}else {setType(e.type);setOutcome('');setTags([]);setMessage('Action historique conservée : corrigez son temps, son joueur ou sa position. La palette permet de choisir une nouvelle action.')}setView('builder')}
useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(!root.current?.contains(document.activeElement)&&document.activeElement!==document.body)return;const target=e.target as HTMLElement;if(e.defaultPrevented)return;if(e.key==='Enter'&&target.closest('button'))return;if(target.matches('input,textarea,select')||target.isContentEditable)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(e.key===' '){e.preventDefault();video.current?.toggle()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();video.current?.step((e.key==='ArrowLeft'?-1:1)*(e.shiftKey?5:1))}else if(e.key==='Enter'){e.preventDefault();submit()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(editing)remove(editing);else if(selected==='ball')setScene({...scene,ball:null});else{const players={...scene.players};delete players[selected];setScene({...scene,players})}}else {const action=Object.keys(definitions).find(k=>definitions[k].shortcut===e.key.toLowerCase());if(action){e.preventDefault();chooseType(action)}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)});
function playerButton(id:string,role:'actor'|'mate'|'opponent'='actor'){const p=data.players.find(p=>p.id===id),active=(role==='actor'?actor:role==='mate'?mate:opponent)===id;return <button type="button" key={id} className={'seq-player '+(active?'active':'')} draggable={role==='actor'} onDragStart={e=>{e.dataTransfer.setData('text/plain',id);chooseActor(id)}} onClick={()=>role==='actor'?pickPlayer(id):role==='mate'?setMate(active?'':id):setOpponent(active?'':id)}>{p?.photo?<img src={p.photo} alt=""/>:<span className="seq-avatar">{p?.name.slice(0,2)}</span>}<span>{p?.name}</span></button>}
const linkedOptions=m.events.filter(e=>e.id!==editing&&(type==='SHOT'&&outcome==='GOAL'?e.type==='PASS'&&e.playerId===mate&&e.relatedPlayerId===actor&&e.metadata.outcome==='COMPLETED':['SAVE','BLOCK'].includes(type)?e.type==='SHOT'&&e.playerId===opponent&&e.metadata.outcome===(type==='SAVE'?'ON_TARGET':'BLOCKED'):false));
return <div className={'analyzer sequence-workspace '+(focus?'seq-focus':'')} ref={root}>
<div className="split"><div><p className="eyebrow">LE MATCH, ACTION PAR ACTION</p><h2>Jouez la scène. Les stats suivent.</h2></div><div className="seq-options"><span className="tag">{m.events.length} actions</span><button type="button" className="button" onClick={()=>setFocus(!focus)}>{focus?'Quitter le plein écran':'Agrandir le terrain'}</button>{focus&&onSave&&<button type="button" className="button primary" disabled={busy} onClick={()=>onSave(m)}>Enregistrer le match</button>}</div></div>
<div className="seq-media"><details className="seq-video-source" open={!m.video&&!localVideo}><summary>Vidéo du match · YouTube ou fichier ordinateur</summary><VideoSource value={m.video} onChange={video=>onChange({...m,video})} onLocal={file=>{setLocalVideo(URL.createObjectURL(file));setLocalName(file.name)}}/></details>
{localVideo&&<div className="split"><p className="accent">Lecture sur cet appareil · {localName}</p><button type="button" className="textbutton" onClick={()=>{setLocalVideo('');setLocalName('')}}>Revenir à YouTube / vidéo enregistrée</button></div>}
<VideoPlayer ref={video} src={localVideo||m.video} onTime={seconds=>{if(!manual&&!editing)setStamp(clock(seconds))}}/></div>
<div className="seq-toolbar"><button type="button" className={'button '+(view==='builder'?'primary':'')} onClick={()=>setView('builder')}>Terrain interactif</button><button type="button" className={'button '+(view==='timeline'?'primary':'')} onClick={()=>setView('timeline')}>Timeline classique</button><button type="button" className="button" disabled={!past.length} onClick={undo}>↶ Annuler</button><button type="button" className="button" disabled={!future.length} onClick={redo}>↷ Refaire</button></div>
{view==='builder'&&<><div className="seq-toolbar"><span className="tag">Séquence {sequence.slice(0,6)}</span><button type="button" className="textbutton" onClick={()=>{setSequence(crypto.randomUUID());setEditing(null);setManual(false)}}>Nouvelle séquence</button><button type="button" className="textbutton" onClick={()=>{const prev=[...m.events].reverse().find(e=>e.metadata.scene);if(prev)setScene(structuredClone(prev.metadata.scene as Scene))}}>Dupliquer la scène précédente</button><button type="button" className="button" onClick={()=>{setSelected('ball');setContext(false)}}>⚽ Ballon</button><button type="button" className="textbutton" disabled={!scene.players[actor]} onClick={()=>setScene({...scene,ball:{x:Math.min(100,scene.players[actor].x+3),y:Math.min(100,scene.players[actor].y+4)}})}>Ballon au joueur</button></div>
<div className="seq-instruction"><strong>{role==='mate'?'Cliquez le receveur sur le terrain.':role==='opponent'?'Cliquez l’adversaire sur le terrain.':selected==='target'?'Cliquez l’arrivée de la passe.':selected==='ball'?'Cliquez pour placer le ballon.':'Cliquez un joueur pour créer son action.'}</strong><span>Les positions restent en place après validation.</span></div>
<button type="button" className="button seq-mobile-players" onClick={()=>setDrawer(!drawer)}>{drawer?'Fermer les joueurs':'Choisir un joueur'}</button>
<div className={'seq-board '+(drawer?'players-open':'')}>
<aside className="seq-roster team-a"><h3>{teamName(m,'A')}</h3>{m.participants.filter(p=>p.team==='A').map(p=>playerButton(p.playerId))}</aside>
<div className="seq-field-shell"><div className="seq-pitch" role="application" aria-label="Terrain interactif" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const r=e.currentTarget.getBoundingClientRect();place({x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))},e.dataTransfer.getData('text/plain'))}} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();place({x:Math.round((e.clientX-r.left)/r.width*100),y:Math.round((e.clientY-r.top)/r.height*100)})}}>
<button type="button" aria-label="But côté gauche" className="seq-goal left" onClick={e=>{e.stopPropagation();if(side==='B'){chooseType('SHOT');setOutcome('GOAL')}else setMessage('Sélectionnez un joueur de l’équipe B pour marquer dans ce but.')}}/><span className="seq-center"/><button type="button" aria-label="But côté droit" className="seq-goal right" onClick={e=>{e.stopPropagation();if(side==='A'){chooseType('SHOT');setOutcome('GOAL')}else setMessage('Sélectionnez un joueur de l’équipe A pour marquer dans ce but.')}}/><span className="seq-direction">A attaque → · ← B attaque</span>
{Object.entries(scene.players).map(([id,p])=><button type="button" key={id} aria-label={name(id)+' sur le terrain'} className={'seq-token '+(m.participants.find(p=>p.playerId===id)?.team==='B'?'away ':'')+(actor===id?'selected':'')+((mate===id||opponent===id)?' involved':'')} style={{left:p.x+'%',top:p.y+'%'}} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',id);setContext(false)}} onClick={e=>{e.stopPropagation();pickPlayer(id)}}>{name(id).slice(0,2)}<small>{name(id)}</small></button>)}
{scene.ball&&<button type="button" className="seq-ball" style={{left:scene.ball.x+'%',top:scene.ball.y+'%'}} draggable onDragStart={e=>e.dataTransfer.setData('text/plain','ball')} onClick={e=>{e.stopPropagation();setSelected('ball');setContext(false)}}>⚽</button>}
{type==='PASS'&&normalized&&(scene.players[mate]||end)&&<svg className="seq-path" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1={point!.x} y1={point!.y} x2={(scene.players[mate]??(side==='B'?{x:100-end!.x,y:100-end!.y}:end!)).x} y2={(scene.players[mate]??(side==='B'?{x:100-end!.x,y:100-end!.y}:end!)).y} stroke="#fcfcfc" strokeWidth=".6" strokeDasharray="2 1"/></svg>}
{end&&<span className="seq-destination" style={{left:(side==='B'?100-end.x:end.x)+'%',top:(side==='B'?100-end.y:end.y)+'%'}}>×</span>}
</div>
<div className="seq-field-dock"><div className="split"><button type="button" className="textbutton" onClick={()=>{setContext(!context);setRole('actor')}}>{name(actor)} · {context?'Réduire':'Créer une action'}</button><label>Temps <input aria-label="Temps de l’action" value={stamp} onChange={e=>{setStamp(e.target.value);setManual(true)}}/></label></div>
<div className="seq-palette">{Object.entries(definitions).filter(([k])=>k!=='TOUCH'||complete).map(([k,d])=><button type="button" key={k} className={type===k&&context?'active':''} onClick={()=>chooseType(k)}>{d.label}<kbd>{d.shortcut?.toUpperCase()}</kbd></button>)}</div>
{context&&<div className="seq-context"><div className="split"><strong>{editing?'Modifier · ':''}{definition.label} · {name(actor)}</strong><button type="button" className="textbutton" onClick={()=>{setRole('actor');setContext(false)}}>Fermer</button></div>
<div className="seq-options">{definition.outcomes.map(o=><button type="button" className={'button '+(outcome===o?'primary':'')} key={o} onClick={()=>{setOutcome(o);if(type==='SHOT'&&o==='BLOCKED')setRole('opponent')}}>{type==='DUEL'?(o==='WON'?name(actor):opponent?name(opponent):'Adversaire'):actionLabels[o]}</button>)}</div>
<div className="seq-options">{(legacy||type==='PASS'||type==='SHOT'&&outcome==='GOAL')&&<button type="button" className={'button '+(role==='mate'?'primary':'')} onClick={()=>setRole('mate')}>{type==='PASS'?'Receveur':'Passeur'} : {mate?name(mate):type==='PASS'?'cliquer un partenaire':'aucun (facultatif)'}</button>}{(['DRIBBLE','DUEL','TACKLE','INTERCEPTION','BLOCK','FOUL','SAVE'].includes(type)||type==='SHOT'&&outcome==='BLOCKED')&&<button type="button" className={'button '+(role==='opponent'?'primary':'')} onClick={()=>setRole('opponent')}>Adversaire : {opponent?name(opponent):'cliquer un joueur'}</button>}{type==='PASS'&&<button type="button" className="textbutton" onClick={()=>{setSelected('target');setContext(false)}}>Placer l’arrivée ↗</button>}{(mate||opponent)&&<button type="button" className="textbutton" onClick={()=>{setMate('');setOpponent('');setLinked('')}}>Retirer le lien joueur</button>}</div>
{role!=='actor'&&<div className="seq-options seq-candidates">{m.participants.filter(p=>role==='mate'?p.team===side&&p.playerId!==actor:p.team&&p.team!==side).map(p=><button type="button" className="seq-player" key={p.playerId} onClick={()=>pickPlayer(p.playerId)}>{name(p.playerId)}</button>)}</div>}
{definition.tags.length>0&&<details><summary>Précisions {tags.length?'· '+tags.length:''}</summary><div className="seq-options">{definition.tags.map(t=><button type="button" key={t} className={'button '+(tags.includes(t)?'primary':'')} onClick={()=>setTags(tags.includes(t)?tags.filter(x=>x!==t):[...tags,t])}>{actionLabels[t]}</button>)}</div></details>}
{linkedOptions.length>0&&<label>Action liée<select value={linked} onChange={e=>setLinked(e.target.value)}><option value="">Aucune</option>{linkedOptions.map(e=><option key={e.id} value={e.id}>{clock(e.timestamp)} · {eventLabel(e)} · {name(e.playerId)}</option>)}</select></label>}
<div className="split"><span className="muted">{normalized?`${zone(normalized).lane} · ≈ ${zone(normalized).distanceToGoal} m du but`:'Position facultative'}</span><button type="button" className="button primary" onClick={submit}>{editing?'Modifier l’action':'Valider → action suivante'} ↵</button></div>
{editing&&<button type="button" className="textbutton" onClick={()=>{setEditing(null);setManual(false);setContext(false);setLegacy(false);setType('SHOT');setOutcome('GOAL')}}>Annuler la modification</button>}
</div>}
</div></div>
<aside className="seq-roster team-b"><h3>{teamName(m,'B')}</h3>{m.participants.filter(p=>p.team==='B').map(p=>playerButton(p.playerId))}</aside></div>
<details><summary>Options d’analyse et raccourcis</summary><label className="checklabel"><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/>Analyse complète · activer les touches</label><label className="checklabel"><input type="checkbox" checked={tracking} onChange={e=>setTracking(e.target.checked)}/>Recalculer les catégories annotées à partir de la timeline (remplace leurs valeurs manuelles).</label><p>Espace : lecture · ← / → : 1 s · Maj + flèche : 5 s · P S D U T I R F : action · Entrée : valider · Suppr : sélection · Cmd/Ctrl Z : annuler · Maj Cmd/Ctrl Z : refaire.</p><p>X 0 : son but · X 100 : but adverse · Y 0 : gauche · Y 100 : droite. Surface estimée : les 6 derniers mètres devant le but.</p><button type="button" className="textbutton" onClick={()=>{const players={...scene.players};delete players[actor];setScene({...scene,players,ball:null});setEnd(null)}}>Effacer la position du joueur</button></details></>}
<p className="muted">Secondary Assist automatique : deux passes réussies suivies d’un but avec passeur décisif, dans la même séquence continue. A → B → C marque : A reçoit la Secondary Assist.</p><p role="status">{message}</p><div className="split"><h3>Timeline</h3><input aria-label="Rechercher un événement" placeholder="Joueur, action, séquence…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" className="button primary" onClick={()=>{setView('builder');setContext(true);setEditing(null)}}>Ajouter une action</button></div><div className="eventlist">{[...m.events].filter(e=>(name(e.playerId)+' '+eventLabel(e)+' '+String(e.metadata.sequenceId??'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.timestamp??0)-(b.timestamp??0)).map(e=><div className="eventrow" key={e.id}><button type="button" className="textbutton" disabled={e.timestamp==null} onClick={()=>video.current?.seek(e.timestamp!)}>{clock(e.timestamp)||'Temps inconnu'}</button><span>{name(e.playerId)}{e.relatedPlayerId?' → '+name(e.relatedPlayerId):''}<small>{teamName(m,e.team)}{e.metadata.opponentPlayerId?' · vs '+name(String(e.metadata.opponentPlayerId)):''}</small></span><span>{eventLabel(e)}{secondaryCredits.filter(c=>c.goalId===e.id).map(c=><small key={c.goalId}>Secondary Assist · {name(c.playerId)}</small>)}</span><button type="button" className="textbutton" onClick={()=>edit(e)}>Modifier</button><button type="button" className="textbutton" onClick={()=>remove(e.id)}>Supprimer</button></div>)}</div></div>}
