'use client';
import {useState,type ReactNode} from 'react';
import type {Match,Settings} from '@/lib/model';
import {labels} from '@/lib/model';
import {aggregate,duos,metric,type Summary} from '@/lib/engine';
import {pairedProduction,linkedAssists} from '@/lib/duo-analytics';
import {playerDomains,profilePercentile,leagueDomainAverages} from '@/lib/player-analytics';
import {LeagueAverageShape} from './league-player-source';
import {divisionFor} from '@/lib/divisions';
import {Picker,Empty,fmt,date} from './league-ui';
import {SourceTemplate,hudTemplates,sourceAt,childNodes} from './hud-source-template';

type Slots=Record<string,ReactNode>;
type Props=Record<string,Record<string,unknown>>;
const upper=(s:Summary)=>s.player.name.toUpperCase();
const delta=(a:number|null,b:number|null)=>a==null||b==null?'—':`${a-b>0?'+':''}${fmt(a-b,2)}`;
const mean=(values:(number|null)[])=>{const known=values.filter((v):v is number=>v!=null);return known.length?known.reduce((s,v)=>s+v,0)/known.length:null};
function notes(slots:Slots,base:string,values:string[]){values.forEach((v,i)=>slots[`${base}.${i}.1`]=v)}
function heading(name:keyof typeof hudTemplates){return <SourceTemplate name={name}/>}
function pairNames(a:Summary,b:Summary,population:Summary[],duo=false){
 const slots:Slots={'0':a.player.name.slice(0,2).toUpperCase(),'1.0':a.player.name,'1.1.0':divisionFor(a.player.id,population)?.name.toUpperCase()??'—','3':b.player.name.slice(0,2).toUpperCase(),'4.0':b.player.name,'4.1.0':divisionFor(b.player.id,population)?.name.toUpperCase()??'—','4.1.1':`ELO ${b.elo}`};
 return <SourceTemplate name={duo?'duoNames':'compareNames'} slots={slots}/>;
}
function sourceRadar(a:Summary,b:Summary,population:Summary[],matches:Match[]) {
 const da=playerDomains(a,population,1,matches),db=playerDomains(b,population,1,matches),svg=sourceAt(hudTemplates.compareProfiles,'0.1'),children=childNodes(svg);
 const point=(i:number,v:number)=>[220+Math.sin(i*2*Math.PI/7)*118*v/100,165-Math.cos(i*2*Math.PI/7)*118*v/100];
 return <>{children.slice(0,18).map((n,i)=><SourceTemplate node={n} key={i}/>)}<LeagueAverageShape node={children[18]} averages={leagueDomainAverages(population,1,matches)} point={point}/>{[[db,'#E9ECE6',19,20],[da,'#56B947',27,28]].map(([domains,color,polygon,circle],group)=>{const ds=domains as typeof da;return <g key={group}>{ds.every(d=>d.value!=null)&&<SourceTemplate node={children[polygon as number]} props={{'':{points:ds.map((d,i)=>point(i,d.value!).join(',')).join(' ')}}}/>} {ds.map((d,i)=>{if(d.value==null)return null;const [x,y]=point(i,d.value),next=ds[(i+1)%ds.length];return <g key={d.name}>{next.value!=null&&!ds.every(d=>d.value!=null)&&<line x1={x} y1={y} x2={point((i+1)%7,next.value)[0]} y2={point((i+1)%7,next.value)[1]} stroke={color as string} strokeWidth="2"/>}<SourceTemplate node={children[(circle as number)+i]} slots={{'0':`${group===0?b.player.name:a.player.name} · ${d.name} : ${fmt(d.value,0)}/100`}} props={{'':{cx:x,cy:y}}}/></g>})}</g>})}</>;
}
function ratingPlot(a:Summary,b:Summary) {
 const games=[...new Map([...a.form,...b.form].map(f=>[f.match.id,f.match])).values()].sort((a,b)=>a.date.localeCompare(b.date)||a.number-b.number),svg=sourceAt(hudTemplates.compareRatings,'0.1'),ns=childNodes(svg);
 const vals=[...a.form,...b.form].map(f=>f.participant.stats.rating),low=Math.min(6,...vals.flatMap(v=>v==null?[]:[v])),high=Math.max(9,...vals.flatMap(v=>v==null?[]:[v]));
 const x=(i:number)=>48+i*576/Math.max(1,games.length-1),y=(v:number)=>220-(v-low)/(high-low||1)*174.9,avg=mean(vals);
 return <>{ns.slice(0,8).map((n,i)=><SourceTemplate node={n} key={i} slots={i%2?{'':fmt(low+(high-low)*Math.floor(i/2)/3,1)}:{}}/>)}{avg!=null&&<><SourceTemplate node={ns[8]} props={{'':{y1:y(avg),y2:y(avg)}}}/><SourceTemplate node={ns[9]} slots={{'':`MOY. ${fmt(avg,1)}`}} props={{'':{y:y(avg)+3}}}/></>}{games.map((m,i)=><SourceTemplate node={ns[10]} key={m.id} slots={{'':`M${m.number}`}} props={{'':{x:x(i)}}}/>)}{[a,b].map((s,team)=>{const points=games.map((m,i)=>({i,value:s.form.find(f=>f.match.id===m.id)?.participant.stats.rating??null}));let previous=false;const path=points.map(p=>{if(p.value==null){previous=false;return ''}const command=previous?'L':'M';previous=true;return`${command}${x(p.i)} ${y(p.value)}`}).join(' ');return <g key={s.player.id}><SourceTemplate node={ns[team===0?16:24]} props={{'':{d:path,pathLength:1}}}/>{points.filter((p):p is {i:number;value:number}=>p.value!=null).map(p=><SourceTemplate node={ns[team===0?17:25]} key={p.i} slots={{'2.1':`${s.player.name} · M${games[p.i].number}`,'2.2':fmt(p.value,2)}} props={{'':{transform:`translate(${x(p.i)-48},${y(p.value)-(team===0?155.9:115.1)})`}}}/>)}</g>})}</>;
}

export function PlayerCompare({summary:a,population,settings,matches}:{summary:Summary;population:Summary[];settings:Settings;matches:Match[]}) {
 const [selected,setSelected]=useState(''),[mode,setMode]=useState('average');
 const b=population.find(s=>s.player.id===selected)??population.find(s=>s.player.id!==a.player.id&&s.appearances>0);
 if(!b)return <Empty>Deux joueurs sont nécessaires pour comparer les performances.</Empty>;
 const da=playerDomains(a,population,1,matches),db=playerDomains(b,population,1,matches),differences=da.flatMap((d,i)=>d.value==null||db[i].value==null?[]:[{name:d.name,value:d.value-db[i].value}]);
 const ranked=[...differences].sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)),closest=ranked.at(-1),largest=ranked[0];
 const domains:Slots={'0.1.1':`■ ${upper(a)}`,'0.1.2':`□ ${upper(b)}`},dp:Props={};
 da.forEach((d,i)=>{const base=`0.${i+2}`,v=db[i].value;domains[`${base}.1.1`]=fmt(d.value,0);domains[`${base}.2.1`]=fmt(v,0);domains[`${base}.3`]=d.value==null||v==null?'—':d.value===v?'ÉGALITÉ':`${d.value>v?upper(a):upper(b)} +${fmt(Math.abs(d.value-v),0)}`;dp[`${base}.1.0.0`]={style:{width:`${d.value??0}%`}};dp[`${base}.2.0.0`]={style:{width:`${v??0}%`}};});
 notes(domains,'0.9',[largest?`Le plus grand écart est en ${largest.name} : ${fmt(Math.abs(largest.value),0)} points.`:'Pas assez de scores comparables.', 'Les deux joueurs utilisent les mêmes matchs de référence et les sept domaines du profil.',`Lecture provisoire avant ${settings.minRadar} matchs. Les observations manquantes restent inconnues.`]);
 const profiles:Slots={'0.0.1':`${upper(a)} VS ${upper(b)}`,'0.1':sourceRadar(a,b,population,matches),'0.2.0':'┄ MOYENNE LIGUE','1.1.0.0':upper(b),'1.1.0.1':`${b.player.name} : ${db.filter(d=>d.value!=null).map(d=>`${d.name} ${fmt(d.value,0)}`).join(' · ')||'scores à observer'}.`,'1.1.1.0':upper(a),'1.1.1.1':`${a.player.name} : ${da.filter(d=>d.value!=null).map(d=>`${d.name} ${fmt(d.value,0)}`).join(' · ')||'scores à observer'}.`,'1.1.2.1':largest?`${largest.name} : ${largest.value>0?a.player.name:b.player.name} devant de ${fmt(Math.abs(largest.value),0)} points.`:'Aucun domaine comparable.','1.1.3.1':closest?`${closest.name} : ${fmt(Math.abs(closest.value),0)} points d’écart.`:'Aucun domaine comparable.'};
 for(const side of [0,1]){profiles[`0.3.${side}.0`]=`${upper(side===0?a:b)} DEVANT`;const candidates=differences.filter(d=>side===0?d.value>0:d.value<0).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value));profiles[`0.3.${side}`]=<><SourceTemplate node={sourceAt(hudTemplates.compareProfiles,`0.3.${side}.0`)} slots={{'':`${upper(side===0?a:b)} DEVANT`}}/>{candidates.length?candidates.map(d=><SourceTemplate key={d.name} node={sourceAt(hudTemplates.compareProfiles,'0.3.0.1')} slots={{'0':d.name,'1':`+${fmt(Math.abs(d.value),0)}`}}/>):<p className="muted">Aucun avantage observé.</p>}</>;}
 const ratings:Slots={'0.0.1':`${upper(a)} VS ${upper(b)} · ${Math.max(a.appearances,b.appearances)} MATCHS`,'0.1':ratingPlot(a,b),'1.0.1':`${upper(a)} · ${upper(b)}`,'1.1.1':upper(a),'1.1.2':upper(b)};
 notes(ratings,'0.2',[`Rating moyen : ${fmt(a.stats.rating,2)} pour ${a.player.name}, ${fmt(b.stats.rating,2)} pour ${b.player.name}.`,'Chaque point est une note enregistrée. Les interruptions indiquent une note absente.','Comparer plusieurs matchs avant de conclure à une tendance.']);
 [a,b].forEach((s,i)=>{const vals=s.form.flatMap(f=>f.participant.stats.rating==null?[]:[f.participant.stats.rating]);[s.stats.rating,profilePercentile(s,population,'ratingStd'),vals.length?Math.max(...vals):null,vals.length?Math.min(...vals):null].forEach((v,j)=>ratings[`1.${j+2}.${i+1}`]=fmt(v,j===1?0:2));});
 const raw:Slots={},groups=[[[1,'keyPasses'],[2,'secondaryAssists'],[3,'lineBreakingPasses'],[4,'chancesCreated']],[[7,'passPct'],[8,'passesAttempted'],[9,'passPressurePct']],[[12,'interceptions'],[13,'recoveries'],[14,'defensiveDuelPct']],[[17,'duelsAttempted'],[18,'duelPct'],[19,'offensiveDuelPct']]] as const;
 [0,6,11,16].forEach(i=>{raw[`0.1.5.${i}.1`]=upper(a);raw[`0.1.5.${i}.2`]=upper(b)});
 groups.flat().forEach(([i,key])=>{raw[`0.1.5.${i}.0`]=(labels[key]??({lineBreakingPasses:'Passes cassant les lignes',passPressurePct:'Passes sous pression %',defensiveDuelPct:'Duels défensifs %',offensiveDuelPct:'Duels offensifs %'} as Record<string,string>)[key]??key)+(mode==='average'&&!key.endsWith('Pct')?' / match observé':'');const va=metric(a,key,mode==='average'),vb=metric(b,key,mode==='average');raw[`0.1.5.${i}.1`]=fmt(va,2);raw[`0.1.5.${i}.2`]=fmt(vb,2);raw[`0.1.5.${i}.3`]=va==null||vb==null?'—':va===vb?'ÉGALITÉ':`${va>vb?upper(a):upper(b)} +${fmt(Math.abs(va-vb),2)}`;});
 [5,10,15,20].forEach(i=>raw[`0.1.5.${i}`]='Les mesures absentes restent inconnues. Même saison et même période pour les deux joueurs.');
 const strengths:Slots={};[da,db].forEach((ds,side)=>{const known=ds.filter((d):d is typeof d&{value:number}=>d.value!=null).sort((a,b)=>b.value-a.value);strengths[`0.1.${side}.0`]=`${upper(side===0?a:b)} · FORCES`;strengths[`0.1.${side}.2`]=`${upper(side===0?a:b)} · À TRAVAILLER`;strengths[`0.1.${side}.1`]=known.slice(0,3).map(d=><SourceTemplate node={sourceAt(hudTemplates.compareStrengths,'0.1.0.1.0')} key={d.name} slots={{'':`• ${d.name} · top ${fmt(100-d.value,0)} %`}}/>);strengths[`0.1.${side}.3`]=known.slice(-2).reverse().map(d=><SourceTemplate node={sourceAt(hudTemplates.compareStrengths,'0.1.0.3.0')} key={d.name} slots={{'':`• ${d.name} · ${fmt(d.value,0)}/100`}}/>)});
 return <section className="source-compare"><div className="controls"><Picker label="Joueur à comparer" value={b.player.id} onChange={setSelected} options={population.filter(s=>s.player.id!==a.player.id).map(s=>({value:s.player.id,label:s.player.name}))}/><Picker label="Mode de comparaison" value={mode} onChange={setMode} options={[{value:'average',label:'Par match observé'},{value:'total',label:'Total'}]}/></div>{pairNames(a,b,population)}{heading('compareHeading3')}<SourceTemplate name="compareDomains" slots={domains} props={dp}/>{heading('compareHeading5')}<SourceTemplate name="compareProfiles" slots={profiles}/>{heading('compareHeading7')}<SourceTemplate name="compareRatings" slots={ratings}/>{heading('compareHeading9')}<SourceTemplate name="compareStats" slots={raw}/>{heading('compareHeading11')}<SourceTemplate name="compareStrengths" slots={strengths}/></section>;
}

export function PlayerDuo({summary:a,population,matches,minimum}:{summary:Summary;population:Summary[];matches:Match[];minimum:number}) {
 const [selected,setSelected]=useState('');const pairs=duos(population,matches,1).filter(p=>p.a.id===a.player.id||p.b.id===a.player.id),partner=(p:typeof pairs[number])=>p.a.id===a.player.id?p.b.id:p.a.id;
 const pair=pairs.find(p=>partner(p)===selected)??pairs[0],b=population.find(s=>s.player.id===(pair?partner(pair):''));
 if(!pair||!b)return <Empty>Aucun match partagé dans la même équipe sur cette période.</Empty>;
 const games=matches.filter(m=>m.status==='finished'&&m.participants.some(p=>p.playerId===a.player.id&&p.team&&m.participants.some(q=>q.playerId===b.player.id&&q.team===p.team)));
 const common=aggregate([a.player,b.player],games),sa=common.find(s=>s.player.id===a.player.id)!,sb=common.find(s=>s.player.id===b.player.id)!;
 const apart=(s:Summary)=>aggregate([s.player],matches.filter(m=>!games.some(g=>g.id===m.id)))[0],aa=apart(a),ab=apart(b);
 const paired=(key:string)=>pairedProduction(games,a.player.id,b.player.id,key);
 const sharedRating=paired('rating').average,sharedMean=sharedRating==null?null:sharedRating/2,separateMean=mean([aa.stats.rating,ab.stats.rating]),combinedGoals=paired('goals').total,goalRate=paired('goals').average;
 const kpis:Slots={'0.1.0':games.length,'0.1.1':games.length<minimum?'PROVISOIRE':'OBSERVÉ','0.2':`${pair.wins} victoires · ${games.length-pair.wins} nuls ou défaites`,'1.1.0':`${fmt(pair.winRate)} %`,'1.1.1':'—','1.2':`Séparés : ${fmt(mean([aa.stats.winRate,ab.stats.winRate]))} % de victoires`,'2.0':'BUTS DU DUO / MATCH','2.1.0':fmt(goalRate,2),'2.1.1':'—','2.2':`${fmt(combinedGoals,0)} buts observés ensemble`,'3.1.0':fmt(sharedMean,2),'3.1.1':delta(sharedMean,separateMean),'3.2':'Moyenne des deux ratings observés ensemble'};
 const production:Slots={'1.0.1':`${upper(a)} · ${upper(b)}`},pp:Props={};
 const keys=['goals','assists','secondaryAssists','keyPasses','recoveries'],values=keys.map(k=>paired(k).total),max=Math.max(1,...values.flatMap(v=>v==null?[]:[v]));
 keys.forEach((key,i)=>{const base=`0.1.${i+4}`,value=paired(key).total;production[`${base}.2.0`]=fmt(value,0);production[`${base}.2.1`]=fmt(paired(key).average,2);production[`${base}.2.2`]='—';pp[`${base}.1.0`]={style:{width:`${value==null?0:value/max*100}%`}};});
 notes(production,'0.2',[`Production des deux joueurs dans ${games.length} matchs partagés.`,'Chaque moyenne utilise les matchs où cette mesure est renseignée pour les deux joueurs ; les matchs incomplets sont exclus.','Le calcul par 60 minutes reste inconnu sans temps de jeu individuel observé.']);
 ['goals','assists','keyPasses','recoveries'].forEach((key,i)=>{const {a:va,total}=paired(key),share=total?va!/total*100:null;production[`1.1.${i}.0.1.0`]=`${upper(a)} ${share==null?'—':fmt(share)+' %'}`;production[`1.1.${i}.0.1.1`]=`${upper(b)} ${share==null?'—':fmt(100-share)+' %'}`;pp[`1.1.${i}.1.0`]={style:{width:`${share??0}%`}};pp[`1.1.${i}.1.1`]={style:{width:`${share==null?0:100-share}%`}}});
 notes(production,'1.2',['Répartition des contributions observées pendant leurs matchs ensemble.','Les totaux et moyennes utilisent uniquement les matchs où la mesure est renseignée pour les deux joueurs.','Une absence de données ne vaut pas zéro.']);
 const separate:Slots={};[[sa,aa,b],[sb,ab,a]].forEach(([withPlayer,withoutPlayer,other],side)=>{separate[`0.1.${side}.0.0`]=`${upper(withPlayer)} AVEC / SANS ${upper(other)}`;const measures=side===0?['rating','goals','assists','creation']:['rating','goals','creation'];measures.forEach((key,i)=>{const va=key==='creation'?null:metric(withPlayer,key,true),vb=key==='creation'?null:metric(withoutPlayer,key,true);separate[`0.1.${side}.${i+1}.1`]=fmt(va,2);separate[`0.1.${side}.${i+1}.2`]=fmt(vb,2);separate[`0.1.${side}.${i+1}.3`]=delta(va,vb)});});separate['0.2.1']=`Rating moyen ensemble : ${fmt(sharedMean,2)} ; séparés : ${fmt(separateMean,2)}. ${games.length} matchs communs. Les scores de Création par sous-groupe restent inconnus, faute de référence comparable stable.`;
 const relation:Slots={},rp:Props={};
 [[a,b],[b,a]].forEach(([from,to],side)=>{relation[`0.1.${side}.0`]=`${from.player.name} → ${to.player.name}`;for(const [row,type]of [[1,'assist'],[2,'secondary']] as const){const count=linkedAssists(games,from.player.id,to.player.id,type==='secondary');relation[`0.1.${side}.${row}.1`]=fmt(count,0)}relation[`0.1.${side}.3.1`]='—';relation[`0.1.${side}.4.1`]='—';relation[`0.1.${side}.3.0`]='Passes clés vers ce joueur';});
 notes(relation,'0.2',['Les liens directs utilisent les buts avec passeur renseigné dans la timeline.','Les connexions non annotées restent inconnues ; le total peut être partiel.','Compléter les destinataires des actions pour lire les connexions.']);
 relation['1.1.0.2']='—';rp['1.1.0.1']={style:{strokeDasharray:'0 1',strokeDashoffset:0}};for(let i=0;i<4;i++){relation[`1.1.1.${i}.2`]='—';rp[`1.1.1.${i}.1.0`]={style:{width:'0%'}};}
 notes(relation,'1.2',['Le composant Chemistry est intégré ; aucun score synthétique n’est inventé.','La formule de Chemistry et ses pondérations ne sont pas définies dans les règles enregistrées.','Les résultats, productions et notes observés restent disponibles dans les autres blocs.']);
 const insights:Slots={'0.0.1':`OBSERVÉ · ${games.length} MATCHS`,'0.1.0.0':'MATCHS PARTAGÉS','0.1.0.1':`${a.player.name} et ${b.player.name} ont joué ${games.length} matchs dans la même équipe.`,'0.1.1.1':`Rating moyen : ${fmt(sharedMean,2)} ; ${fmt(pair.winRate)} % de victoires.`,'0.1.2.0':'MATURITÉ DE LA LECTURE','0.1.2.1':games.length<minimum?`Lecture provisoire avant ${minimum} matchs ensemble.`:`Seuil de ${minimum} matchs ensemble atteint.`,'0.1.3.1':'Consulte les matchs partagés pour retrouver les actions et les statistiques du duo.'};
 return <section className="source-duo"><div className="controls"><Picker label="Partenaire du duo" value={b.player.id} onChange={setSelected} options={pairs.map(p=>({value:partner(p),label:p.a.id===a.player.id?p.b.name:p.a.name}))}/><span className="eyebrow">{games.length<minimum?'LECTURE PROVISOIRE · ':''}{games.length} MATCHS COMMUNS</span></div>{pairNames(a,b,population,true)}{heading('duoHeading3')}<SourceTemplate name="duoKpis" slots={kpis}/>{heading('duoHeading5')}<SourceTemplate name="duoProduction" slots={production} props={pp}/>{heading('duoHeading7')}<SourceTemplate name="duoSeparate" slots={separate}/>{heading('duoHeading9')}<SourceTemplate name="duoRelation" slots={relation} props={rp}/>{heading('duoHeading11')}<SourceTemplate name="duoInsights" slots={insights}/><section className="hud-kit"><h3>Leurs matchs ensemble</h3>{games.map(m=><a className="matchrow" href={'/matchs/'+m.id} key={m.id}><span>{date(m.date)}</span><strong>Match #{m.number}</strong><strong>{m.scoreA} – {m.scoreB}</strong></a>)}</section></section>;
}
