'use client';
import { useState, type ReactNode } from 'react';
import type { League, Match } from '@/lib/model';
import { labels } from '@/lib/model';
import type { Summary } from '@/lib/engine';
import { divisionFor, divisions } from '@/lib/divisions';
import { playerDomains, profileValue, profilePercentile, recentRatings, averageContributions, matchDomainHistory } from '@/lib/player-analytics';
import { SourceTemplate, hudTemplates, sourceAt, childNodes, type SourceNode } from './hud-source-template';
import { fmt } from './league-ui';
const extraLabels: Record<string,string> = { secondaryAssists:'Passes décisives secondaires', ratingStd:'Écart-type des notes', keyPassShotPct:'Passes clés menant à un tir', passPressurePct:'Réussite sous pression', lineBreakingPasses:'Passes cassant les lignes', receivedLastThird:'Passes reçues dans le dernier tiers', forwardCarries:'Conduites vers l’avant', successfulTackles:'Tacles réussis', offensiveDuelPct:'Duels offensifs gagnés', unmarkedPassPct:'Passes vers un coéquipier démarqué' };
const label = (key:string) => extraLabels[key] ?? labels[key] ?? key;
const measureLabel = (key:string) => label(key)+(!key.endsWith('Pct')&&!['conversion','winRate','appearances','ratingStd','rating'].includes(key)?' / match':'');
const level = (v:number|null) => v == null ? 'NON OBSERVÉ' : v >= 85 ? 'TRÈS FORT' : v >= 65 ? 'FORT' : v >= 45 ? 'CORRECT' : 'À DÉVELOPPER';
const signed = (v:number|null) => v == null ? '—' : `${v > 0 ? '+' : ''}${fmt(v,2)}`;
function notes(node:SourceNode, texts:string[]) { return childNodes(node).map((child,i)=><SourceTemplate node={child} key={i} slots={{'1':texts[i] ?? ''}}/>); }
export function SourcePlayerHeader({summary,population,controls}:{summary:Summary;population:Summary[];controls:ReactNode}) {
 const division=divisionFor(summary.player.id,population);
 return <div className="ds-profile-page"><SourceTemplate name="header" slots={{'0':controls,'1.0':summary.player.photo?<img src={summary.player.photo} alt=""/>:summary.player.name.slice(0,2).toUpperCase(),'1.1.0':summary.player.name,'1.1.1.0':division?.name.toUpperCase()??'DIVISION À VENIR','1.1.1.1':`ELO ${summary.elo}`,'1.1.1.2':`${summary.appearances} MATCHS`}}/></div>;
}
export function SourcePlayerOverview({ summary:s, population, divisionPopulation, matches, data }: { summary:Summary; population:Summary[]; divisionPopulation:Summary[]; matches:Match[]; data:League }) {
 const [selected,setSelected]=useState(1);
 const domains=playerDomains(s,population,data.settings.minRadar,matches), division=divisionFor(s.player.id,divisionPopulation), recent=recentRatings(s);
 const known=domains.filter((d):d is typeof d & {value:number}=>d.value!=null).sort((a,b)=>b.value-a.value), collective=domains[6].value;
 const mean=known.length ? known.reduce((sum,d)=>sum+d.value,0)/known.length : null;
 const explain=(i:number)=>domains[i].value==null ? (i===3?'Les passes et conduites vers l’avant ne sont pas encore relevées.':`Au moins ${data.settings.minRadar} matchs et des données comparables sont nécessaires.`) : `Score ${fmt(domains[i].value,0)}/100, calculé sur les données observées de la période.`;
 const percentRating=profilePercentile(s,population,'rating');
 const kpiSlots:Record<string,ReactNode>={'0.1.0':fmt(s.stats.rating,2),'0.1.1':signed(recent.delta),'0.2':percentRating==null?'Pas assez de notes comparables':`Percentile ${fmt(percentRating,0)} dans la ligue`,'1.1':division?.name.toUpperCase()??'—','1.3':`ELO ${s.elo} · rang relatif dans la ligue`,'2.0':'RATING · 5 DERNIERS','2.1.0':fmt(recent.current,2),'2.1.1':signed(recent.delta),'2.2':recent.previous==null?'Pas de période précédente comparable':`Période précédente : ${fmt(recent.previous,2)} / 10`,'3.1.0':fmt(collective,0),'3.1.1':'/ 100','3.2':collective==null?'Données insuffisantes':'Résultats d’équipe · score relatif'};
 const insightSlots:Record<string,ReactNode>={};
 const insights=[['POINT FORT',known[0]?.name??'À découvrir',known[0]?`Le domaine le plus haut est ${known[0].name} : ${fmt(known[0].value,0)}/100.`:'Les scores apparaîtront quand assez de matchs auront été observés.'],['À DÉVELOPPER',known.at(-1)?.name??'À découvrir',known.length?`Le domaine le moins haut est ${known.at(-1)!.name} : ${fmt(known.at(-1)!.value,0)}/100.`:'Consulte les statistiques renseignées ci-dessous.'],['LECTURE','Des données observées','Un tiret signifie que la mesure est absente. Une valeur zéro signifie qu’elle a été observée.'],['TENDANCE',signed(recent.delta),recent.previous==null?'Il faut deux périodes de matchs notés pour mesurer l’évolution.':`Rating moyen des 5 derniers matchs : ${fmt(recent.current,2)} / 10.`]];
 insights.forEach((row,i)=>row.forEach((value,j)=>insightSlots[`${i}.${j}`]=value));
 const domainSlots:Record<string,ReactNode>={}, domainProps:Record<string,Record<string,unknown>>={};
 domains.forEach((d,i)=>{
  domainProps[String(i)]={checked:selected===i,defaultChecked:undefined,onChange:()=>setSelected(i)};
  domainSlots[`8.1.${i}.1`]=explain(i);domainSlots[`8.1.${i}.2`]=fmt(d.value,0);domainSlots[`8.1.${i}.3`]=level(d.value);
  domainSlots[`8.${i+2}.0.0`]=`${d.name.toUpperCase()} — ${fmt(d.value,0)} / 100`;domainSlots[`8.${i+2}.0.1`]=level(d.value);domainSlots[`8.${i+2}.1`]=explain(i);
  domainSlots[`8.${i+2}.3`]=d.keys.map(key=><li key={key}>{measureLabel(key)} : {fmt(profileValue(s,key),key==='ratingStd'?2:1)}</li>);
  domainSlots[`8.${i+2}.4`]=d.value==null?'Compléter les observations pour lire ce domaine.':'Ouvre les matchs pour retrouver le détail des actions et les statistiques.';
 });
 const radarChildren=childNodes(sourceAt(hudTemplates.domains,'7.1'));
 const point=(i:number,value:number)=>{const angle=-Math.PI/2+i*Math.PI*2/7;return [220+Math.cos(angle)*118*value/100,165+Math.sin(angle)*118*value/100];};
 domainSlots['7.1']=<>{radarChildren.slice(0,19).map((n,i)=><SourceTemplate node={n} key={i}/>)}{domains.map((d,i)=>{if(d.value==null)return null;const [x,y]=point(i,d.value),next=domains[(i+1)%7];return <g key={d.name}>{next.value!=null&&<line x1={x} y1={y} x2={point((i+1)%7,next.value)[0]} y2={point((i+1)%7,next.value)[1]} stroke="#8BE36B" strokeWidth="2"/>}<SourceTemplate node={radarChildren[20+i]} slots={{'0':`${d.name} : ${fmt(d.value,0)}/100`}} props={{'':{cx:x,cy:y,onClick:()=>setSelected(i),role:'button',tabIndex:0,'aria-label':`${d.name} : ${fmt(d.value,0)}`,onKeyDown:(e:React.KeyboardEvent)=>{if(e.key==='Enter'||e.key===' ')setSelected(i)}}}}/></g>;})}</>;
 domainSlots['7.3']=notes(sourceAt(hudTemplates.domains,'7.3'),[known.length?`${known.length} domaines disposent d’un score comparable.`:'Les statistiques sont visibles même quand les scores ne sont pas encore calculables.','La référence 50 correspond au milieu du groupe. Les mesures absentes ne sont pas des zéros.',`Sélectionne un domaine pour consulter ses mesures. ${data.settings.minRadar} matchs minimum pour le radar.`]);
 const row=sourceAt(hudTemplates.domains,'9.0.1.0');
 domainSlots['9.0.1']=domains.flatMap((d,i)=>d.keys.map(key=>{const value=profileValue(s,key),rank=profilePercentile(s,population,key);return <SourceTemplate node={row} key={key} slots={{'0':measureLabel(key),'1':`${fmt(value,key==='ratingStd'?2:1)}${value!=null&&(key.endsWith('Pct')||key==='conversion'||key==='winRate')?' %':''}`,'2.1':value==null?'NON OBSERVÉ':rank==null?'Pas assez de données comparables':`Percentile ${fmt(rank,0)} dans la ligue`,'3':rank==null?'—':rank>55?'▲':rank<45?'▼':'—'}} props={{'':{className:`sx sx${i} prow`},'2.0.0':{style:{width:`${rank??0}%`}}}}/>;}));
 const strengthSlots:Record<string,ReactNode>={'1.0.1':mean==null?'DONNÉES INSUFFISANTES':`MOYENNE DES DOMAINES : ${fmt(mean,0)}`};
 for(const side of [0,1]) strengthSlots[`${side}.1`]=known.length?(side===0?known.slice(0,3):[...known].reverse().filter(d=>d.value<(mean??0)).slice(0,3)).map((d,i)=><SourceTemplate key={d.name} node={sourceAt(hudTemplates.strengths,`${side}.1.0`)} slots={{'0':String(i+1).padStart(2,'0'),'1.0':d.name,'1.1':explain(domains.indexOf(d)),'2':side===0?`TOP ${fmt(100-d.value,0)} %`:signed(d.value-(mean??0))}}/>):<p className="muted">Pas assez de matchs comparables sur cette période.</p>;
 const chronological=[...s.form].reverse(), rated=chronological.flatMap(f=>f.participant.stats.rating==null?[]:[f.participant.stats.rating]), leagueRatings=population.flatMap(p=>p.form.flatMap(f=>f.participant.stats.rating==null?[]:[f.participant.stats.rating]));
 const leagueMean=leagueRatings.length?leagueRatings.reduce((a,b)=>a+b,0)/leagueRatings.length:null;
 const low=Math.min(6,Math.floor(Math.min(...rated,leagueMean??6))),high=Math.max(9,Math.ceil(Math.max(...rated,leagueMean??9))),y=(value:number)=>220-(value-low)/(high-low)*204,x=(i:number)=>chronological.length<=1?336:48+i*576/(chronological.length-1);
 const chart=childNodes(sourceAt(hudTemplates.evolution,'0.1'));let path='',connected=false;
 chronological.forEach((f,i)=>{const r=f.participant.stats.rating;if(r==null){connected=false;return;}path+=`${connected?'L':'M'}${x(i)},${y(r)} `;connected=true;});
 const evolutionSlots:Record<string,ReactNode>={};
 evolutionSlots['0.1']=<>{chart.slice(0,8).map((n,i)=><SourceTemplate node={n} key={i} slots={i%2?{'':fmt(low+(high-low)*Math.floor(i/2)/3,1)}:{}}/>)}{leagueMean!=null&&<><SourceTemplate node={chart[8]} props={{'':{y1:y(leagueMean),y2:y(leagueMean)}}}/><SourceTemplate node={chart[9]} slots={{'':`LIGUE ${fmt(leagueMean,1)}`}} props={{'':{y:y(leagueMean)-6}}}/></>}<SourceTemplate node={chart[16]} props={{'':{d:path,pathLength:1,style:{strokeDasharray:1,strokeDashoffset:0}}}}/>{chronological.map((f,i)=><g key={f.match.id}><SourceTemplate node={chart[10]} slots={{'':`M${f.match.number}`}} props={{'':{x:x(i)}}}/>{f.participant.stats.rating!=null&&<SourceTemplate node={chart[17]} slots={{'2.1':`${s.player.name} · M${f.match.number}`,'2.2':fmt(f.participant.stats.rating,2)}} props={{'':{transform:`translate(${x(i)-48},${y(f.participant.stats.rating)-145.2})`}}}/>}</g>)}</>;
 evolutionSlots['0.2']=notes(sourceAt(hudTemplates.evolution,'0.2'),[`${rated.length} matchs notés sur ${s.appearances} matchs joués.`,leagueMean==null?'Pas de moyenne de ligue disponible.':`Moyenne des notes observées dans la ligue : ${fmt(leagueMean,2)} / 10.`,'Survole un point pour lire la note. Une note absente laisse une interruption dans la courbe.']);
 const composition=averageContributions(s,data), familyNames:Record<string,string>={finition:'FINITION',creation:'CRÉATION',passes:'PASSES',percussion:'PERCUSSION',duels:'DUELS',defense:'DÉFENSE'};
 const contributions=composition?[...composition.values.map(v=>({name:familyNames[v.name],value:v.value})),{name:'PERTES',value:composition.penalty},{name:'BORNES / ARRONDI',value:composition.correction},{name:'AJUSTEMENT ADMIN',value:composition.override}]:Object.values(familyNames).map(name=>({name,value:null}));
 evolutionSlots['1.1']=<><SourceTemplate node={sourceAt(hudTemplates.evolution,'1.1.0')} slots={{'0':'BASE 6,00','1':`= ${fmt(composition?.rating,2)}`}}/>{contributions.map(c=><SourceTemplate key={c.name} node={sourceAt(hudTemplates.evolution,'1.1.1')} slots={{'0':c.name,'2':signed(c.value)}} props={{'1.0':{style:{width:`${Math.min(100,Math.abs(c.value??0)/4*100)}%`,background:(c.value??0)<0?'#E5484D':'#56B947'}}}}/>)}</>;
 evolutionSlots['1.2']=notes(sourceAt(hudTemplates.evolution,'1.2'),[composition?`Décomposition moyenne de ${composition.count} matchs calculables sur ${rated.length} matchs notés.`:'Pas assez de mesures comparables pour décomposer les notes.','La note conserve le calcul actuel : base 6, bonus de performance, pertes de balle et ajustements administrateur.','Les familles absentes ne contribuent pas au calcul.']);
 const scatter=childNodes(sourceAt(hudTemplates.analysis,'0.1')), scatterRows=population.flatMap(p=>{const volume=profileValue(p,'passesAttempted'),efficiency=profileValue(p,'passPct');return volume!=null&&efficiency!=null?[{s:p,volume,efficiency}]:[];}),maxVolume=Math.max(1,...scatterRows.map(p=>p.volume)),sx=(v:number)=>40+500*v/maxVolume,sy=(v:number)=>260-250*v/100;
 const analysisSlots:Record<string,ReactNode>={'0.0.1':`PASSES · ${scatterRows.length} JOUEURS`};
 analysisSlots['0.1']=<>{scatter.slice(0,6).map((n,i)=><SourceTemplate node={n} key={i}/>)}{scatterRows.map(p=><SourceTemplate node={scatter[6]} key={p.s.player.id} slots={{'1.0':`${p.s.player.name} · ${fmt(p.volume,1)} passes / match · ${fmt(p.efficiency,1)} %`}} props={{'0':{cx:sx(p.volume),cy:sy(p.efficiency)},'1':{cx:sx(p.volume),cy:sy(p.efficiency),r:p.s.player.id===s.player.id?7:4,fill:p.s.player.id===s.player.id?'#8BE36B':'#8E978C'}}}/>)}{scatter.slice(31,35).map((n,i)=><SourceTemplate node={n} key={i}/>)}<SourceTemplate node={scatter[35]} slots={{'':'VOLUME · PASSES TENTÉES / MATCH →'}}/><SourceTemplate node={scatter[36]} slots={{'':'EFFICACITÉ · % DE PASSES RÉUSSIES'}}/></>;
 analysisSlots['0.2']=notes(sourceAt(hudTemplates.analysis,'0.2'),[`Volume : ${fmt(profileValue(s,'passesAttempted'),1)} passes tentées par match observé.`,`Réussite : ${fmt(profileValue(s,'passPct'),1)} %. ${scatterRows.some(p=>p.s.player.id===s.player.id)?`Le point vert représente ${s.player.name}.`:'Pas assez de mesures pour placer le joueur.'}`,'Les joueurs sans tentatives et réussites renseignées ne sont pas placés sur le graphique.']);
 const history=matchDomainHistory(s,data.players),heat=childNodes(sourceAt(hudTemplates.analysis,'1.1'));
 analysisSlots['1.1']=<><SourceTemplate node={heat[0]}/>{history.map(h=><SourceTemplate key={h.match.id} node={heat[1]} slots={{'':`M${h.match.number}`}}/>)}{domains.map((d,i)=><FragmentRow key={d.name}><SourceTemplate node={heat[7]} slots={{'':d.name.toUpperCase()}}/>{history.map(h=><SourceTemplate key={h.match.id} node={heat[8]} slots={{'':fmt(h.domains[i].value,0)}} props={{'':{title:`${d.name} · Match ${h.match.number} : ${fmt(h.domains[i].value,0)}`,style:{background:h.domains[i].value==null?'#1C211C':`rgba(86,185,71,${.08+h.domains[i].value!*.008})`,color:h.domains[i].value==null?'#8E978C':'#E9ECE6'}}}}/>)}</FragmentRow>)}</>;
 analysisSlots['1.2']=notes(sourceAt(hudTemplates.analysis,'1.2'),['Chaque colonne correspond à un match joué sur la période.','Les scores par match comparent uniquement les participants de ce match.','Un tiret indique des mesures absentes ou un groupe insuffisant pour comparer.']);
 const divisionSlots:Record<string,ReactNode>={};
 divisionSlots['0.1']=[...divisions].reverse().map(d=><SourceTemplate node={sourceAt(hudTemplates.division,'0.1.0')} key={d.id} slots={{'0':d.name.toUpperCase(),'1':`PERCENTILE ELO ≥ ${d.minimum}`,'2':division?.id===d.id?`TOI · ${s.elo}`:''}} props={{'':{style:{background:division?.id===d.id?'#12290F':undefined}},'0':{style:{color:division?.id===d.id?'#8BE36B':'#8E978C'}}}}/>);
 divisionSlots['0.2']=notes(sourceAt(hudTemplates.division,'0.2'),[division?`Division actuelle : ${division.name}.`:'La division nécessite au moins deux joueurs ayant joué.',`ELO actuel : ${s.elo}.`,'Les divisions actuelles utilisent le rang ELO relatif dans la ligue.']);
 const finished=matches.filter(m=>m.status==='finished').length,attendance=finished?100*s.appearances/finished:null;
 const collectiveRows=[{name:'PRÉSENCE',value:attendance,text:attendance==null?'—':`${s.appearances}/${finished}`},{name:'ÉCART-TYPE NOTES',value:profilePercentile(s,population,'ratingStd'),text:fmt(profileValue(s,'ratingStd'),2)},{name:'VICTOIRES ÉQUIPE',value:s.stats.winRate??null,text:`${fmt(s.stats.winRate,0)} %`},{name:'PASSES VERS COÉQUIPIERS',value:null,text:'—'}];
 divisionSlots['1.0.1']=`${fmt(collective,0)} / 100`;
 divisionSlots['1.1']=collectiveRows.map(c=><SourceTemplate node={sourceAt(hudTemplates.division,'1.1.0')} key={c.name} slots={{'0':c.name,'2':c.text}} props={{'1.0':{style:{width:`${c.value??0}%`}},'1.1':{style:{display:'none'}}}}/>);
 divisionSlots['1.2']=notes(sourceAt(hudTemplates.division,'1.2'),['Le score collectif combine les résultats d’équipe : 60 % taux de victoire, 40 % nombre de victoires, comparés à la ligue.','La présence et la régularité sont présentées séparément.','Les passes vers les coéquipiers démarqués ne sont pas encore relevées.']);
 return <div className="ds-profile-page source-player-overview"><SourceTemplate name="kpis" slots={kpiSlots} props={{'1.2.0':{style:{width:division?`${division.minimum}%`:'0%'}}}}/><SourceTemplate name="insightsHeading"/><SourceTemplate name="insights" slots={insightSlots}/><SourceTemplate name="domainsHeading"/><SourceTemplate name="domains" slots={domainSlots} props={domainProps}/><SourceTemplate name="strengthsHeading"/><SourceTemplate name="strengths" slots={strengthSlots}/><SourceTemplate name="evolutionHeading"/><SourceTemplate name="evolution" slots={evolutionSlots}/><SourceTemplate name="analysisHeading"/><SourceTemplate name="analysis" slots={analysisSlots} props={{'1.1':{style:{gridTemplateColumns:`110px repeat(${Math.max(1,history.length)}, minmax(30px,1fr))`,overflowX:'auto'}}}}/><SourceTemplate name="divisionHeading"/><SourceTemplate name="division" slots={divisionSlots}/></div>;
}
function FragmentRow({children}:{children:ReactNode}){return <>{children}</>;}
