'use client';
import {useRef,useState} from 'react';
import type {Match,Settings} from '@/lib/model';
import {labels} from '@/lib/model';
import type {Summary} from '@/lib/engine';
import {richFacts} from '@/lib/insights';
import {positionedEvents,offensiveActions,defensiveActions} from '@/lib/events';
import {playStyles} from '@/lib/performance';
import {Picker,fmt,Empty} from './league-ui';
export function FactsCarousel({summaries,matches,settings}:{summaries:Summary[];matches:Match[];settings:Settings}){const scroll=useRef<HTMLDivElement>(null);const facts=richFacts(summaries,matches,settings);return <section className="factssection"><div className="sectionhead"><div><span className="eyebrow accent">AU VESTIAIRE</span><h2>Il fallait le savoir.</h2></div><div className="controls"><button className="button" aria-label="Facts précédents" onClick={()=>scroll.current?.scrollBy({left:-340,behavior:'smooth'})}>←</button><button className="button" aria-label="Facts suivants" onClick={()=>scroll.current?.scrollBy({left:340,behavior:'smooth'})}>→</button></div></div><div className="factcarousel" ref={scroll}>{facts.map((f,i)=><a className="fact" key={f.text} href={f.matchId?'/matchs/'+f.matchId:'/joueurs/'+f.playerId}><span className="eyebrow">{String(i+1).padStart(2,'0')} / {f.category}</span><p>{f.text}</p><span className="accent">Voir de plus près ↗</span></a>)}</div>{!facts.length&&<Empty>Quelques matchs de plus pour faire parler les chiffres.</Empty>}</section>}
export function PlayStyles({playerId,matches}:{playerId:string;matches:Match[]}){const styles=playStyles(playerId,matches);return <section className="panel playstyles"><span className="eyebrow accent">PLAYSTYLES</span><h2>{styles[0]?.name??'Un style à découvrir'}</h2>{!styles.length?<p className="muted">Au moins 3 matchs renseignés et 3 joueurs comparables. Aucun style attribué au hasard.</p>:styles.map((s,i)=><details key={s.name} open={i===0}><summary>{i===0?'Principal':'Secondaire'} · {s.name} <b>{s.score} % de compatibilité</b></summary><p>Repère pédagogique : {s.reference}. Une référence de style, pas une équivalence de niveau.</p><h4>Pourquoi ce PlayStyle ?</h4>{s.evidence.map(e=><div className="statrow" key={e.key}><span>{labels[e.key]} / match</span><b>{fmt(e.value)} · percentile {Math.round(e.percentile)}</b></div>)}<p className="muted">Moyenne sur les 20 derniers matchs renseignés : le style principal est conservé si l’écart de compatibilité reste inférieur à 8 points.</p></details>)}</section>}
export function RatingExplanation({match,playerId}:{match:Match;playerId:string}){const p=match.participants.find(p=>p.playerId===playerId);return <details className="panel ratingexplanation"><summary>Pourquoi {fmt(p?.final_rating??p?.stats.rating)} ?</summary><p>Base 6,0 · note entre 3,0 et 10,0. Comparaison des familles renseignées avec les performances du groupe.</p>{p?.ratingExplanation?.map(s=><p key={s}>{s}</p>)}<p className="muted">Automatique : {fmt(p?.auto_rating)} · Override : {fmt(p?.admin_rating)} · Finale : {fmt(p?.final_rating)}</p></details>}
export function Heatmaps({matches,playerId}:{matches:Match[];playerId?:string}){const [mode,setMode]=useState('all');const all=positionedEvents(matches,playerId);const points=all.filter(e=>mode==='attack'?offensiveActions.has(e.type):mode==='defense'?defensiveActions.has(e.type):mode==='shots'?['GOAL','SHOT','SHOT_ON_TARGET','SHOT_OFF_TARGET','SHOT_BLOCKED'].includes(e.type):mode==='passes'?['PASS','PASS_COMPLETED','PASS_FAILED','KEY_PASS','LONG_PASS','LONG_PASS_COMPLETED','CROSS','CROSS_COMPLETED'].includes(e.type)&&!!e.metadata.endPosition:true);const min=mode==='shots'?3:5;return <section className="panel heatmaps"><div className="split"><h2>Le terrain raconte aussi.</h2><Picker label="Carte des actions" value={mode} onChange={setMode} options={[{value:'all',label:'Heatmap générale'},{value:'attack',label:'Offensive'},{value:'defense',label:'Défensive'},{value:'shots',label:'Shot map'},{value:'passes',label:'Passing map'}]}/></div><p className="muted">{points.length} actions positionnées sur la période sélectionnée. Les actions non annotées ne sont pas extrapolées.</p>{points.length<min?<Empty>Carte disponible à partir de {min} actions positionnées ({points.length}/{min}).</Empty>:<svg className="heatpitch" viewBox="0 0 200 400" role="img" aria-label={`${mode} : ${points.length} actions`}><rect x="1" y="1" width="198" height="398" fill="#151f19" stroke="#86918a"/><line x1="0" y1="200" x2="200" y2="200" stroke="#86918a"/><circle cx="100" cy="200" r="32" fill="none" stroke="#86918a"/><rect x="50" y="0" width="100" height="60" fill="none" stroke="#86918a"/><rect x="50" y="340" width="100" height="60" fill="none" stroke="#86918a"/>{points.map(e=>{const p=e.position!,end=e.metadata.endPosition as {x:number;y:number}|undefined;return <g key={e.matchId+e.id}><title>{e.type} · X {p.x}, Y {p.y}</title>{mode==='passes'&&end&&<line x1={p.y*2} y1={p.x*4} x2={end.y*2} y2={end.x*4} stroke={(e.type==='PASS_FAILED'||e.type==='PASS'&&e.metadata.outcome==='FAILED')?'#bbb':'#44cf6c'} strokeDasharray={(e.type==='PASS_FAILED'||e.type==='PASS'&&e.metadata.outcome==='FAILED')?'4 3':undefined} strokeWidth="1.5"/>}<circle cx={p.y*2} cy={p.x*4} r={mode==='shots'||mode==='passes'?4:18} fill={(e.type==='GOAL'||e.type==='SHOT'&&e.metadata.outcome==='GOAL')?'#fcfcfc':'#44cf6c'} opacity={mode==='shots'||mode==='passes'?.8:.13}/>{mode==='passes'&&end&&<circle cx={end.y*2} cy={end.x*4} r="2" fill="#fcfcfc"/>}</g>})}<text x="100" y="18" textAnchor="middle" fill="#fcfcfc" fontSize="7">NOTRE BUT</text><text x="100" y="390" textAnchor="middle" fill="#fcfcfc" fontSize="7">BUT ADVERSE ↓</text></svg>}<p className="muted">Orientation relative à l’équipe du joueur. X : notre but → but adverse. Y : gauche → droite. Blanc : but / arrivée de passe.</p></section>}
