'use client';
// Markup and SVG geometry from frames 92e7d472, 27c82ce1 and 03251b8d.
import Link from 'next/link';
import { useState, type CSSProperties } from 'react';
import type { Summary } from '@/lib/engine';
import { metric, radar } from '@/lib/engine';
import type { Match, Season } from '@/lib/model';
import { teamName, labels, statGroups, ratios } from '@/lib/model';
import { Empty, StatInfo, fmt, date, time, Calendar } from './league-ui';

const initials = (name: string) => name.slice(0, 2).toUpperCase();
export function SourceLeaderboard({ title, stat, summaries, perMatch = false, all = false }: { title: string; stat: string; summaries: Summary[]; perMatch?: boolean; all?: boolean }) {
  const [expanded, setExpanded] = useState(all);
  const rows = summaries.filter(s => metric(s, stat, perMatch) != null).sort((a, b) => metric(b, stat, perMatch)! - metric(a, stat, perMatch)!);
  const first = rows[0], max = Math.max(0, ...rows.map(s => metric(s, stat, perMatch)!));
  const value = (s: Summary) => fmt(metric(s, stat, perMatch), stat === 'rating' ? 2 : 1);
  return <section className="ds-rank"><div className="pn ca"><h3>{title}</h3><span className="info"><StatInfo stat={stat}/></span>{first ? <><Link href={'/joueurs/' + first.player.id} className="lead ki" style={{ '--i': 0 } as CSSProperties}><span className="cc">{initials(first.player.name)}</span><div className="nm"><small>EN TÊTE</small><b>{first.player.name}</b></div><div className="val">{value(first)}</div></Link>{rows.slice(1, expanded ? undefined : 10).map((s, i) => <Link href={'/joueurs/' + s.player.id} className="ra ki" key={s.player.id} style={{ '--i': (i + 1) / 2 } as CSSProperties}><span className="rk">{rows.filter(x => metric(x, stat, perMatch)! > metric(s, stat, perMatch)!).length + 1}</span><span className="cc">{initials(s.player.name)}</span><span className="nm">{s.player.name}</span><span className="v">{value(s)}</span><i className="bar kb" style={{ '--w': `${max ? Math.max(0, metric(s, stat, perMatch)!) / max * 100 : 0}%` } as CSSProperties}/></Link>)}{rows.length > 10 && !all && <div style={{ padding: '16px 4px 0' }}><button className="vf textbutton" onClick={() => setExpanded(!expanded)}>{expanded ? 'RÉDUIRE' : 'VOIR TOUT'} ↗</button></div>}</> : <Empty>Pas encore assez de données.</Empty>}</div></section>;
}
export function SourceStatRings({ summary, population }: { summary: Summary; population: Summary[] }) {
  const keys = ['defensiveActions', 'interceptions', 'goals', 'saves', 'shotsOnTarget', 'appearances', 'duelsWon', 'wins', 'assists', 'tackles'];
  return <section className="ds-rank"><div className="ph2"><span className="cc">{initials(summary.player.name)}</span><b>{summary.player.name}</b><span>FICHE JOUEUR · 10 STATS</span></div><div className="gf">{keys.map((key, i) => {
    const values = population.filter(s => s.appearances > 0).map(s => metric(s, key)).filter((v): v is number => v != null);
    const value = metric(summary, key), max = Math.max(0, ...values), rank = value == null || !summary.appearances || !values.length ? null : values.filter(v => v > value).length + 1;
    const color = rank === 1 ? '#8BE36B' : rank != null && rank <= 3 ? '#E2B54A' : '#56B947';
    return <div className="pn cf kpop" key={key} style={{ '--i': i / 2 } as CSSProperties}><div className="rw"><svg viewBox="0 0 110 110" aria-hidden="true"><circle className="bg" cx="55" cy="55" r="48"/><circle className="fg" cx="55" cy="55" r="48" style={{ stroke: color, '--to': 302 * (1 - (value == null || !max ? 0 : Math.min(1, value / max))), '--i': i / 2 } as CSSProperties}/></svg><div className="ct"><b>{fmt(value, 0)}</b><small>/ {values.length ? fmt(max, 0) : '—'} MAX</small></div></div><h4>{labels[key]} <StatInfo stat={key}/></h4><span className="pill" style={{ borderColor: color, color }}>{rank == null ? 'NON OBSERVÉ' : `RANG ${rank} / ${values.length}`}</span></div>;
  })}</div></section>;
}
export function SourceMatchHeading({ match: m, season, admin, mvpName }: { match: Match; season?: Season; admin: boolean; mvpName?: string }) {
  return <div className="ds-match"><div className="cd in match-heading" style={{ padding: '26px 32px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}><span className="mono" style={{ fontSize: 11, letterSpacing: '.24em', color: '#8E978C' }}>{season?.name} · MATCH {m.number} · {m.status === 'finished' ? 'TERMINÉ' : m.status === 'cancelled' ? 'ANNULÉ' : 'À VENIR'}</span>{admin && <Link className="button" href={'/admin?match=' + m.id}>MODIFIER LE MATCH</Link>}</div><div className="match-heading-teams" style={{ display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', gap: 20, margin: '14px 0 22px' }}><div className="match-heading-team" style={{ display: 'flex', alignItems: 'center', gap: 18 }}><TeamCrest name={teamName(m, 'A')}/><div><div className="bs" style={{ fontSize: 44, fontWeight: 800, lineHeight: 1 }}>{teamName(m, 'A')}</div><div className="mono" style={{ fontSize: 10, letterSpacing: '.2em', color: '#8E978C', marginTop: 4 }}>ÉQUIPE A</div></div></div><div className="bs match-heading-score" style={{ fontSize: 150, fontWeight: 900, lineHeight: .9, letterSpacing: '.02em' }}>{m.status === 'finished' ? <><span className="tv">{m.scoreA}</span><span style={{ color: '#4B544A', margin: '0 14px' }}>–</span>{m.scoreB}</> : 'VS'}</div><div className="match-heading-team" style={{ display: 'flex', alignItems: 'center', gap: 18, justifyContent: 'flex-end', textAlign: 'right' }}><div><div className="bs" style={{ fontSize: 44, fontWeight: 800, lineHeight: 1 }}>{teamName(m, 'B')}</div><div className="mono" style={{ fontSize: 10, letterSpacing: '.2em', color: '#8E978C', marginTop: 4 }}>ÉQUIPE B</div></div><TeamCrest name={teamName(m, 'B')} white/></div></div><div className="meta">{[['DATE', date(m.date, true)], ['HEURE', time(m.date)], ['DURÉE', `${m.duration} min`], ['LIEU', m.location || 'À préciser'], ['JOURNÉE', m.number]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="actions filterrow">{mvpName && <Link className="textbutton accent" href={'/joueurs/' + m.mvpId}>★ MVP · {mvpName}</Link>}{m.status === 'scheduled' && <Calendar match={m}/>}<Link className="button" href="/glossaire">Comprendre les stats ⓘ</Link>{admin && <Link className="button" href={'/admin?match=' + m.id + '&step=video'}>Modifier la timeline</Link>}</div>{m.notes && <details className="importnote"><summary>À propos des données de ce match</summary><p>{m.notes}</p></details>}</div></div>;
}
function TeamCrest({ name, white = false }: { name: string; white?: boolean }) {
  return <div style={{ width: 64, height: 64, border: `2px solid ${white ? '#AEB8B2' : '#8BE36B'}`, display: 'flex', alignItems: 'center', justifyContent: 'center', font: "900 26px 'Big Shoulders Display'", color: white ? '#E9ECE6' : '#8BE36B', clipPath: 'polygon(0 0,calc(100% - 14px) 0,100% 14px,100% 100%,14px 100%,0 calc(100% - 14px))', background: white ? '#1C211C' : '#12290F', flexShrink: 0 }}>{initials(name)}</div>;
}
export function SourceIndividualHero({ summary: s, match: m, population, seasonSummary }: { summary: Summary; match: Match; population: Summary[]; seasonSummary?: Summary }) {
  const rating = s.stats.rating, rank = rating == null ? null : population.filter(x => x.stats.rating != null && x.stats.rating > rating).length + 1;
  const side = m.participants.find(p => p.playerId === s.player.id)?.team, color = side === 'B' ? '#E9ECE6' : '#8BE36B';
  const average = seasonSummary?.stats.rating, delta = rating != null && average != null ? rating - average : null;
  return <div className="ds-individual"><div className="hero" style={{ '--tm': color } as CSSProperties}><div className="gh">{s.player.name.toUpperCase()}</div><div className="nm"><div className="tg">{teamName(m, side ?? '')} · MATCH {m.number}</div><h2>{s.player.name}</h2><div className="sub"><span className="g">{rank == null ? 'NON OBSERVÉ' : `${rank} / ${population.length} DU MATCH`}</span><span>{delta == null ? 'MOY. NON OBSERVÉE' : `VS MOY. ${delta > 0 ? '+' : ''}${fmt(delta, 1)}`}</span></div></div><div className="ring"><svg viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="80" fill="none" stroke="#1C211C" strokeWidth="12"/><circle className="v" cx="100" cy="100" r="80" fill="none" stroke={color} strokeWidth="12" strokeDashoffset={503 * (1 - Math.min(10, Math.max(0, rating ?? 0)) / 10)}/></svg><b style={{ color }}>{fmt(rating, 1)}<small>NOTE DU MATCH</small></b></div><div className="kfs">{[['goals', 'BUTS'], ['assists', 'PASSES DÉC.'], ['recoveries', 'RÉCUPÉRATIONS']].map(([key, label]) => <div key={key}>{fmt(s.stats[key], 0)}<span>{label}</span></div>)}</div></div></div>;
}

export function SourceStatsTiles({ summary, population = [] }: { summary: Summary; population?: Summary[] }) {
  const [group, setGroup] = useState('Tous');
  const groups = Object.entries(statGroups);
  const keys = [...groups.flatMap(([, fields]) => Object.keys(fields)), ...Object.keys(ratios)];
  return <section className="ds-individual"><div className="fbar"><b>STATISTIQUES COMPLÈTES</b><div className="actions">{['Tous', ...groups.map(([name]) => name)].map(name => <button key={name} className={'button ' + (name === group ? 'primary' : '')} onClick={() => setGroup(name)}>{name}</button>)}</div></div><div className="B">{keys.filter(key => group === 'Tous' || key in (statGroups[group] ?? {}) || (ratios[key] && ratios[key][0] in (statGroups[group] ?? {}))).map((key, i) => {
    const value = summary.stats[key], rows = population.filter(s => s.stats[key] != null), max = Math.max(0, ...rows.map(s => s.stats[key]!)), best = rows.find(s => s.stats[key] === max), mean = rows.length ? rows.reduce((n, s) => n + s.stats[key]!, 0) / rows.length : null;
    const rank = value == null || !rows.length ? null : rows.filter(s => s.stats[key]! > value).length + 1;
    const ratio = key in ratios, label = labels[key], delta = value != null && mean != null ? value - mean : null;
    const category = key.includes('pass') || key.includes('Pass') || ['assists', 'secondaryAssists', 'xa', 'chancesCreated'].includes(key) ? 'g-pas' : ['tackles', 'interceptions', 'recoveries', 'blocks', 'clearances', 'duelsWon', 'fouls', 'saves', 'highRecoveries'].includes(key) ? 'g-def' : ['touches', 'boxTouches', 'turnovers', 'foulsWon'].includes(key) ? 'g-bal' : 'g-att';
    return <div className={'card tile ' + category + (rank === 1 ? ' top' : '')} key={key} style={{ '--i': i, '--fs': ratio ? '34px' : '44px' } as CSSProperties}><small>{label} <StatInfo stat={key}/></small><b>{fmt(value, ratio ? 1 : ['xg', 'xgot', 'xa', 'xgConceded', 'rating'].includes(key) ? 2 : 0)}{ratio && value != null ? ' %' : ''}</b><div className="bar"><div style={{ width: `${max && value != null ? Math.max(0, value) / max * 100 : 0}%` }}/>{mean != null && max > 0 && <i style={{ left: `${mean / max * 100}%` }}/>}</div><div className="ft"><span>{rank == null ? 'NON OBSERVÉ' : `${rank}/${rows.length}`}</span><span>{mean == null ? '—' : `MOY. ${fmt(mean, 1)}`}</span></div><div className="hv"><small>{label}</small><div><span>MEILLEUR</span><strong>{rows.length ? fmt(max, ratio ? 1 : 0) : '—'}</strong><span>{best ? best.player.name.toUpperCase() : 'NON OBSERVÉ'}</span></div><div className="d" style={{ color: delta != null && delta < 0 ? '#E5484D' : '#8BE36B' }}>{delta == null ? 'DONNÉE NON OBSERVÉE' : `${delta > 0 ? '+' : ''}${fmt(delta, 1)} VS MOY.`}</div></div></div>;
  })}</div></section>;
}

export function SourceMatchRadar({ summary, population }: { summary: Summary; population: Summary[] }) {
  const keys = ['goals', 'assists', 'shotsOnTarget', 'passesCompleted', 'duelsWon', 'recoveries'];
  const names = ['BUTS', 'PASSES DÉC.', 'TIRS CADRÉS', 'PASSES RÉUSSIES', 'DUELS', 'RÉCUP.'];
  const positions = [[205, 31, 52], [339, 108, 130], [339, 264, 284], [205, 341, 362], [71, 264, 285], [71, 108, 130]];
  const ends = [[205, 65], [313.3, 127.5], [313.3, 252.5], [205, 315], [96.7, 252.5], [96.7, 127.5]];
  const grid = ['205.0,158.8 232.1,174.4 232.1,205.6 205.0,221.2 177.9,205.6 177.9,174.4', '205.0,127.5 259.1,158.8 259.1,221.2 205.0,252.5 150.9,221.3 150.9,158.8', '205.0,96.2 286.2,143.1 286.2,236.9 205.0,283.8 123.8,236.9 123.8,143.1', '205.0,65.0 313.3,127.5 313.3,252.5 205.0,315.0 96.7,252.5 96.7,127.5'];
  const maxima = keys.map(key => Math.max(0, ...population.flatMap(s => s.stats[key] == null ? [] : [s.stats[key]!])));
  const point = (value: number, i: number) => `${(205 + (ends[i][0] - 205) * (maxima[i] ? value / maxima[i] : 0)).toFixed(1)},${(190 + (ends[i][1] - 190) * (maxima[i] ? value / maxima[i] : 0)).toFixed(1)}`;
  const means = keys.map(key => { const vals = population.flatMap(s => s.stats[key] == null ? [] : [s.stats[key]!]); return vals.length ? vals.reduce((n, v) => n + v, 0) / vals.length : null; });
  return <div className="ds-individual"><div className="card rd"><div className="hd"><b>PROFIL</b><small>6 AXES · 100 % = LE MEILLEUR DU MATCH</small></div><svg viewBox="0 0 410 380" width="410" height="380" style={{ display: 'block', maxWidth: '100%', height: 'auto' }} role="img" aria-label={'Profil du match de ' + summary.player.name}>{grid.map(points => <polygon key={points} points={points} fill="none" stroke="#2A322A"/>)}{ends.map(([x, y], i) => <line key={i} x1="205" y1="190" x2={x} y2={y} stroke="#2A322A"/>)}{means.every(v => v != null) && <polygon points={means.map((v, i) => point(v!, i)).join(' ')} fill="none" stroke="#E9ECE6" strokeDasharray="4 4" opacity=".7"/>}{keys.every(key => summary.stats[key] != null) && <polygon className="poly" points={keys.map((key, i) => point(summary.stats[key]!, i)).join(' ')} fill="rgba(86,185,71,.28)" stroke="#8BE36B" strokeWidth="2.5"/>}{positions.map(([x, y, valueY], i) => <g key={keys[i]}><text x={x} y={y} fill="#C5CBC1" fontFamily="JetBrains Mono" fontSize="10" textAnchor="middle">{names[i]}</text><text x={x} y={valueY} fill="#8BE36B" fontFamily="Big Shoulders Display" fontWeight="900" fontSize="22" textAnchor="middle">{fmt(summary.stats[keys[i]], 0)}</text></g>)}</svg><div className="lg"><span><i/>{summary.player.name.toUpperCase()}</span><span><i className="d"/>MOYENNE</span></div></div></div>;
}

/** Paired domain bars copied from frame 08524bd4. */
export function SourceCompareDomains({ a, b, population, minimum }: { a: Summary; b: Summary; population: Summary[]; minimum: number }) {
  const domainsA = radar(a, population, minimum), domainsB = radar(b, population, minimum);
  return <section className="source-profile-panel"><div className="source-profile-panel-heading"><span>COMPARAISON DOMAINE PAR DOMAINE</span><small>6 DOMAINES · SCORE /100</small></div><div className="source-domain-row source-domain-heading"><span/><span className="accent">■ {a.player.name.toUpperCase()}</span><span>□ {b.player.name.toUpperCase()}</span><span>ÉCART</span></div>{domainsA.map((domain, i) => {
    const other = domainsB[i], delta = domain.value != null && other.value != null ? domain.value - other.value : null;
    return <div className="source-domain-row" key={domain.name}><span className="source-domain-name">{domain.name.toUpperCase()}</span><div className="source-domain-score"><div><i className="fill" style={{ width: `${domain.value ?? 0}%` }}/></div><strong>{fmt(domain.value, 0)}</strong></div><div className="source-domain-score white"><div><i className="fill" style={{ width: `${other.value ?? 0}%` }}/></div><strong>{fmt(other.value, 0)}</strong></div><span className={delta != null && delta > 0 ? 'accent' : ''}>{delta == null ? '—' : `${delta > 0 ? '+' : ''}${fmt(delta, 0)}`}</span></div>;
  })}</section>;
}
