'use client';
// Interactive question layout from source frame efe76521. The existing analyzer
// owns action validation, projection, history and saving.
import { useState } from 'react';
import type { Match } from '@/lib/model';
import { actionDefinitions, actionLabels } from '@/lib/actions';
type Stage = 'actor' | 'action' | 'outcome' | 'details' | 'player' | 'review';
export function ActionWizard({ match, actor, type, outcome, tags, mate, opponent, stamp, tracking, name, onActor, onType, onOutcome, onTags, onMate, onOpponent, onStamp, onTracking, onFreeze, onCommit }: {
  match: Match; actor: string; type: string; outcome: string; tags: string[]; mate: string; opponent: string; stamp: string; tracking: boolean; name: (id: string) => string;
  onActor: (id: string) => void; onType: (key: string) => void; onOutcome: (key: string) => void; onTags: (tags: string[]) => void; onMate: (id: string) => void; onOpponent: (id: string) => void; onStamp: (value: string) => void; onTracking: (value: boolean) => void; onFreeze: () => void; onCommit: () => boolean;
}) {
  const [stage, setStage] = useState<Stage>('actor');
  const definition = actionDefinitions[type] ?? {label:type,outcomes:[],tags:[]};
  const side = match.participants.find(p => p.playerId === actor)?.team;
  const mateNeeded = type === 'PASS', mateOptional = type === 'SHOT' && outcome === 'GOAL';
  const opponentNeeded = ['DRIBBLE', 'DUEL', 'TACKLE', 'FOUL'].includes(type) || type === 'SHOT' && outcome === 'BLOCKED';
  const optionalOpponent = ['BLOCK', 'SAVE', 'INTERCEPTION'].includes(type);
  const relevantTags = definition.tags.filter(tag => !['KEY_PASS', 'ASSIST'].includes(tag));
  const nextPlayer = () => setStage(mateNeeded || mateOptional || opponentNeeded || optionalOpponent ? 'player' : 'review');
  const stages: [Stage, string, string][] = [['actor', 'AUTEUR', name(actor)], ['action', 'ACTION', definition.label], ['outcome', 'RÉSULTAT', actionLabels[outcome] ?? '—'], ['details', 'PRÉCISIONS', tags.map(tag => actionLabels[tag]).join(' · ') || 'À choisir'], ['player', mateNeeded || mateOptional ? 'RECEVEUR / PASSEUR' : 'ADVERSAIRE', name(mate || opponent) || 'À choisir'], ['review', 'VALIDATION', 'Brouillon']];
  const stageIndex = stages.findIndex(([key]) => key === stage);
  const heading: Record<Stage, string> = { actor: 'Qui fait l’action ?', action: 'Quelle action ?', outcome: 'Quel résultat ?', details: type === 'PASS' ? 'Quel type de passe ?' : 'Quelle précision ?', player: mateNeeded ? 'Qui reçoit la passe ?' : mateOptional ? 'Qui fait la passe décisive ?' : 'Quel adversaire ?', review: 'Valider cette action' };
  return <section className="ds-analyzer"><div className="stat"><span className="pill on">BROUILLON · {match.events.length} ACTIONS</span></div><div className="card tbar"><div className="tm"><div><small>TEMPS DU MATCH</small><input aria-label="Temps de l’action guidée" value={stamp} onChange={e => onStamp(e.target.value)}/></div></div><button className="bt" type="button" onClick={onFreeze}>Figer le temps de la vidéo</button><div className="sep"/><div className="frz">UNE QUESTION À LA FOIS</div></div><div className="stepper">{stages.map(([key, label, value], i) => <div className={i < stageIndex ? 'done' : i === stageIndex ? 'cur' : 'nx'} key={key}>{i < stageIndex ? '✓ ' : ''}{label}<b>{i <= stageIndex ? value : 'Ensuite'}</b></div>)}</div><div className="ctx">{stage !== 'actor' && <><div className="chip"><small>AUTEUR</small>{name(actor)}</div><button type="button" className="bt" onClick={() => setStage('actor')}>⟲ Changer le joueur</button></>}{stageIndex > 1 && <><div className="chip"><small>ACTION</small>{definition.label} {actionLabels[outcome]}</div><button type="button" className="bt" onClick={() => setStage('action')}>⟲ Changer d’action</button></>}</div><div className="card q"><h4>{heading[stage]}<span className="rq">{stage === 'details' || stage === 'player' && (mateOptional || optionalOpponent) ? 'FACULTATIF' : 'OBLIGATOIRE'}</span></h4><p className="d">{stage === 'details' ? 'Les données inconnues restent inconnues. Plusieurs précisions peuvent être combinées.' : 'Choisissez une réponse pour passer à la question suivante.'}</p><div className="opts">
  {stage === 'actor' && match.participants.filter(p => p.team).map(p => <button type="button" className="op" key={p.playerId} onClick={() => { onFreeze(); onActor(p.playerId); setStage('action'); }}>{name(p.playerId)}</button>)}
  {stage === 'action' && Object.entries(actionDefinitions).map(([key, d]) => <button type="button" className="op" key={key} onClick={() => { onType(key); setStage(d.outcomes.length ? 'outcome' : d.tags.length ? 'details' : ['BLOCK', 'INTERCEPTION'].includes(key) ? 'player' : 'review'); }}>{d.label}</button>)}
  {stage === 'outcome' && definition.outcomes.map(key => <button type="button" className="op" key={key} onClick={() => { onOutcome(key); if (relevantTags.length) setStage('details'); else setStage(type === 'PASS' || ['DRIBBLE', 'DUEL', 'TACKLE', 'FOUL', 'SAVE'].includes(type) || type === 'SHOT' && ['GOAL', 'BLOCKED'].includes(key) ? 'player' : 'review'); }}>{actionLabels[key]}</button>)}
  {stage === 'details' && relevantTags.map(tag => <button type="button" className="op" aria-pressed={tags.includes(tag)} key={tag} onClick={() => onTags(tags.includes(tag) ? tags.filter(x => x !== tag) : [...tags, tag])}>{actionLabels[tag]}</button>)}
  {stage === 'player' && match.participants.filter(p => p.playerId !== actor && (mateNeeded || mateOptional ? p.team === side : p.team && p.team !== side)).map(p => <button type="button" className="op" key={p.playerId} onClick={() => { if(mateNeeded || mateOptional) onMate(p.playerId); else onOpponent(p.playerId); setStage('review'); }}>{name(p.playerId)}</button>)}
  </div>{stage === 'details' && <div className="actions filterrow"><button className="bt g" type="button" onClick={nextPlayer}>Continuer</button><button className="bt" type="button" onClick={() => { onTags([]); nextPlayer(); }}>Type inconnu</button></div>}{stage === 'player' && !mateNeeded && !opponentNeeded && <button className="bt filterrow" type="button" onClick={() => { onMate(''); onOpponent(''); setStage('review'); }}>Non renseigné · continuer</button>}{stage === 'review' && <><p className="note">{stamp} · {name(actor)} · {definition.label} {actionLabels[outcome]}{mate ? ' → ' + name(mate) : ''}{opponent ? ' · vs ' + name(opponent) : ''}. Les statistiques sont calculées à partir des actions annotées.</p><label className="checklabel"><input type="checkbox" checked={tracking} onChange={e => onTracking(e.target.checked)}/>Recalculer les catégories annotées à partir de la timeline (remplace leurs valeurs manuelles).</label><button className="bt g" type="button" onClick={() => { if (onCommit()) setStage('actor'); }}>Valider → action suivante</button></>}{!match.participants.some(p => p.team) && <p className="note">Ajoutez les participants et leurs équipes avant d’annoter ce match.</p>}</div></section>;
}
