'use client';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import type {League} from '@/lib/model';
import type {RecognitionData} from '@/lib/recognition-repository';
import {awardDefinitions,badgeDefinitions} from '@/lib/recognition-definitions';
import {metricName,type Rule,type Check,type BadgeResult,type AwardResult} from '@/lib/recognition';
import {Avatar,Picker,Heading,Empty,fmt} from './league-ui';
const Context=createContext<{recognition:RecognitionData|null;error:string}>({recognition:null,error:''});
export function RecognitionProvider({data,children}:{data:League|null;children:ReactNode}){
 const [recognition,setRecognition]=useState<RecognitionData|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!data)return;const abort=new AbortController();fetch('/api/recognition',{signal:abort.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Les distinctions sont momentanément indisponibles.');return r.json() as Promise<RecognitionData>}).then(d=>{setRecognition(d);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[data]);
 return <Context.Provider value={{recognition,error}}>{children}</Context.Provider>
}
function Pending(){const {error}=useContext(Context);return <p className={error?'error':'muted'} role={error?'alert':'status'}>{error||'Calcul des distinctions…'}</p>}
const comparator=(op?:string)=>op==='lt'?'<':op==='lte'?'≤':'≥';
function RuleText({rule}:{rule:Rule}){if('any'in rule||'of'in rule){const list='any'in rule?rule.any:rule.of;return <li><strong>{'any'in rule?'Au moins 1 critère':`Au moins ${rule.count} critères sur ${list.length}`} :</strong><ul>{list.map((r,i)=><RuleText key={i} rule={r}/>)}</ul></li>}return <li>{metricName(rule.key)} {comparator(rule.op)} {rule.percentile?'P':''}{fmt(rule.value,2)}{rule.low?' (percentile inversé)':''}</li>}
function Conditions({checks}:{checks:Check[]}){return <ul className="recognition-checks">{checks.map((c,i)=><li key={c.key+i} className={c.passed?'passed':''}><span aria-label={c.passed?'Rempli':'Non rempli'}>{c.passed?'✓':'○'}</span><span>{c.label}<small>{c.actual==null?'Donnée manquante':fmt(c.actual,2)} · objectif {comparator(c.op)} {fmt(c.target,2)}</small></span></li>)}</ul>}
function BadgeChip({badge}:{badge:BadgeResult}){return <span className={'identity-chip '+(badge.category==='Allegations'?'allegation':'')} title={badge.description+' · Badge Score '+badge.score+'/100'}><span>{badge.icon}</span>{badge.name}</span>}
export function MainBadges({playerId}:{playerId:string}){const {recognition}=useContext(Context);const row=recognition?.players.find(p=>p.playerId===playerId);return row?.main.length?<div className="identity-chips" aria-label="Badges principaux">{row.main.map(b=><BadgeChip badge={b} key={b.id}/>)}</div>:null}
export function Identity({playerId}:{playerId:string}){
 const {recognition}=useContext(Context);const [category,setCategory]=useState('Tous');if(!recognition)return <Pending/>;const row=recognition.players.find(p=>p.playerId===playerId);
 return <section className="panel identity-panel"><div className="split"><div><span className="eyebrow">L’IDENTITÉ STATISTIQUE · {recognition.badgeSeasonName}</span><h2>Identity</h2></div><span className="tag">{row?.activeCount??0} badges actifs</span></div><p className="muted">Une combinaison qui évolue avec vos matchs. Au maximum une Allegation parmi les trois badges principaux.</p><MainBadges playerId={playerId}/>{!row?.main.length&&<p className="muted">Aucun badge actif pour le moment.</p>}<details className="badge-collection"><summary className="button">Explorer la Badge Collection · 35 badges</summary><div className="split filterrow"><h3>Badge Collection</h3><Picker label="Catégorie de badge" value={category} onChange={setCategory} options={['Tous','Status','Finishing','Creation / Technique','Control','Volume','Defensive','Allegations'].map(x=>({value:x,label:x}))}/></div><p className="muted">Minimum max(4, 25 % du maximum de matchs joués), arrondi au supérieur. Les conditions en percentile comparent les joueurs de cette saison ; au moins 3 joueurs sont nécessaires.</p><div className="badge-grid">{row?.badges.filter(b=>category==='Tous'||b.category===category).map(b=><article className={'badge-card '+(!b.active?'inactive ':'')+(b.category==='Allegations'?'allegation':'')} key={b.id}><div className="split"><span className="badge-icon">{b.icon}</span><span className="tag">{b.active?'ACTIF · '+b.score+'/100':'INACTIF'}</span></div><small className="eyebrow">{b.category}</small><h3>{b.name}</h3><p className="muted">{b.description}</p><Conditions checks={b.checks}/><details><summary>Règle complète</summary><ul>{badgeDefinitions.find(d=>d.id===b.id)?.rules.map((r,i)=><RuleText key={i} rule={r}/>)}</ul></details></article>)}</div></details></section>
}
function AwardCard({award,season,data}:{award:AwardResult;season:RecognitionData['seasons'][number];data:League}){
 const definition=awardDefinitions.find(d=>d.id===award.id);return <article className={'panel recognition-award '+(award.id==='copro-or'?'crown ':'')+(award.category==='Banter'?'banter':'')}><div className="split"><span className="award-icon">{award.icon}</span><span className="eyebrow">{award.category==='Banter'?'BANTER AWARD':'AWARD PRINCIPAL'}</span></div><h2>{award.name}</h2><p className="muted">{award.description}</p><p className="eyebrow">{season.seasonName} · {season.finalized?'PALMARÈS DÉFINITIF':'PROJECTION'}</p>{award.winner?<div className="award-winners">{award.winner.playerIds.map(id=><a href={'/joueurs/'+id} key={id}><Avatar player={data.players.find(p=>p.id===id)} large/><strong>{data.players.find(p=>p.id===id)?.name??award.winner!.name}</strong></a>)}<span className="award-score">{fmt(award.score,1)}<small> / 100 · score</small></span></div>:<p className="unassigned">NON ATTRIBUÉ</p>}<p className="muted">{!season.finalized&&award.winner?'En tête actuellement · le trophée sera attribué à la clôture.':award.reason}</p><details><summary>Calcul et conditions</summary><p className="muted">Chaque composante est normalisée en percentile avant pondération.</p><div className="award-formula">{award.formula.map(w=><div className="statrow" key={w.key}><span>{metricName(w.key)}{w.low?' · faible valeur favorisée':''}<small>{w.weight} %</small></span><strong>{fmt(award.winner?.values[w.key],2)}</strong></div>)}</div>{award.checks.length>0&&<Conditions checks={award.checks}/>}<ul>{definition?.ratio&&<li>Minimum max(5, 35 % du maximum de matchs joués), arrondi au supérieur.</li>}{definition?.rules.map((r,i)=><RuleText key={i} rule={r}/>)}{definition?.always&&<li>Toujours attribué dès qu’au moins un joueur a disputé un match. Les composantes disponibles sont renormalisées si certaines manquent.</li>}</ul></details></article>
}
export function Awards({data}:{data:League}){const {recognition}=useContext(Context);const [selected,setSelected]=useState(''),[category,setCategory]=useState('Tous');if(!recognition)return <Pending/>;const season=recognition.seasons.find(s=>s.seasonId===selected)||recognition.seasons.find(s=>s.seasonId===recognition.badgeSeasonId)||recognition.seasons[0];return <><Heading title="LAISSE TA TRACE." kicker="AWARDS · LE PALMARÈS COPRO"><Picker label="Saison des awards" value={season?.seasonId??''} onChange={setSelected} options={recognition.seasons.map(s=>({value:s.seasonId,label:s.seasonName}))}/><Picker label="Catégorie des awards" value={category} onChange={setCategory} options={['Tous','Principaux','Banter'].map(x=>({value:x,label:x==='Principaux'?'Awards principaux':x==='Banter'?'Banter Awards':x}))}/></Heading><p className="intro muted">25 trophées. Des seuils à mériter. Une place dans l’histoire.</p>{season?<><div className="recognition-status"><span className="tag">{season.finalized?'PALMARÈS FIGÉ':'SAISON NON CLÔTURÉE'}</span><p>{season.finalized?'Ces trophées sont conservés définitivement, même si les statistiques évoluent.':'Les résultats sont des projections. Les trophées sont attribués automatiquement une seule fois à la fin de la saison.'}</p></div><div className="recognition-grid">{season.awards.filter(a=>category==='Tous'||a.category===category).map(a=><AwardCard key={a.id} award={a} season={season} data={data}/>)}</div></>:<Empty>Créez votre première saison pour lancer les distinctions.</Empty>}<section className="panel recognition-method"><h3>Des distinctions qui se vérifient</h3><p className="muted">{recognition.method}</p><details><summary>Données nécessaires et limites</summary>{recognition.limits.map(l=><p key={l.metric}><strong>{l.affected.join(' · ')}</strong><br/>{l.reason}</p>)}<p>Les données non renseignées ne deviennent jamais des zéros. Un trophée reste non attribué si ses seuils ou son calcul ne peuvent pas être vérifiés.</p></details></section></>}
export function Palmares({playerId}:{playerId:string}){const {recognition}=useContext(Context);if(!recognition)return <Pending/>;const won=recognition.seasons.filter(s=>s.finalized).map(s=>({...s,awards:s.awards.filter(a=>a.winner?.playerIds.includes(playerId))})).filter(s=>s.awards.length);return <section className="panel recognition-palmares"><span className="eyebrow">POUR L’HISTOIRE</span><h2>Palmarès</h2>{won.map(s=><div key={s.seasonId}><h3>{s.seasonName}</h3>{s.awards.map(a=><a className={'palmares-item '+(a.category==='Banter'?'banter':'')} href="/awards" key={a.id}><span>{a.icon}</span><strong>{a.name}</strong>{a.winner!.playerIds.length>1&&<small>{a.winner!.name}</small>}</a>)}</div>)}{!won.length&&<p className="muted">Le prochain chapitre reste à écrire. Seuls les trophées de saisons clôturées entrent au palmarès.</p>}</section>}
export function SeasonHonors({seasonId}:{seasonId:string}){const {recognition}=useContext(Context);if(!recognition)return <Pending/>;const season=recognition.seasons.find(s=>s.seasonId===seasonId);const crown=season?.awards.find(a=>a.id==='copro-or');return <div className="season-honors"><span className="eyebrow">👑 COPRO D’OR · {season?.finalized?'DÉFINITIF':'PROJECTION'}</span><h3>{crown?.winner?.name??'En attente de matchs'}</h3><a href="/awards" className="button">Voir les 25 Awards</a></div>}
