/** Operational definitions used while manually observing a match. */
export const actionCriteria:Record<string,{definition:string;choices:string}>= {
 PASS:{definition:'Un joueur transmet volontairement le ballon à un coéquipier. Une passe est réussie si ce coéquipier reçoit le ballon ; elle est ratée si le ballon sort ou est récupéré par un adversaire.',choices:"Passe clé : crée directement une occasion de tir. Assist : dernière passe avant un but, liée au but enregistré. Marquer une passe comme décisive ne crée pas une assist supplémentaire. Une simple touche de balle ne compte pas comme une passe."},
 SHOT:{definition:'Tentative volontaire de marquer. Un tir cadré entre dans le but ou est arrêté par le gardien ; un tir non cadré manque le but.',choices:"Bloqué : arrêté par un joueur de champ. Montant : touche le poteau ou la barre sans entrer. Pour un but, choisis le passeur ou « Sans passe décisive ». Ajoute les CSC séparément."},
 OWN_GOAL:{definition:'Un joueur envoie involontairement le ballon dans le but de sa propre équipe.',choices:"Attribue le CSC au joueur qui l’a commis. Il compte pour l’équipe adverse, sans ajouter de but personnel, de tir ou d’assist."},
 DRIBBLE:{definition:'Tentative de passer un adversaire avec le ballon sous contrôle.',choices:'Réussi : le joueur passe l’adversaire en conservant le ballon. Raté : l’adversaire empêche le passage. La possession perdue se précise séparément.'},
 DUEL:{definition:'Deux adversaires se disputent directement le contrôle du ballon.',choices:"Choisis gagné ou perdu du point de vue du joueur ciblé, puis au sol ou aérien. Le duel est compté pour les deux joueurs : une seule action suffit."},
 TACKLE:{definition:'Intervention d’un défenseur pour retirer le ballon à son porteur.',choices:"Gagné : le défenseur touche ou dégage le ballon et arrête le porteur. Perdu : le porteur garde le ballon. Précise si le ballon est récupéré, sorti ou gardé par l’adversaire. Choisis faute si l’intervention est sanctionnée."},
 INTERCEPTION:{definition:'Un joueur coupe une passe adverse avant qu’elle atteigne son destinataire.',choices:"Une interception compte aussi comme une récupération. Si l’intercepteur est déjà identifié sur une passe ratée, les compteurs sont ajoutés : inutile de saisir une deuxième action."},
 RECOVERY:{definition:'Un joueur prend le contrôle d’un ballon libre ou récupère la possession après une erreur adverse.',choices:"Choisis la cause observée. Recevoir la passe d’un coéquipier ne compte pas comme une récupération. Une position dans le dernier tiers indique une récupération haute. Les interceptions sont déjà comptées dans les récupérations."},
 BLOCK:{definition:'Un joueur de champ arrête un tir adverse avant qu’il atteigne le but.',choices:"Identifie le tireur si possible. Si le défenseur est déjà lié au tir bloqué, le blocage est compté. Pour une intervention du gardien, choisis un arrêt."},
 CLEARANCE:{definition:'Un joueur éloigne volontairement le ballon d’une zone dangereuse, sans chercher une passe contrôlée.',choices:"Précise pied ou tête. N’ajoute pas de passe réussie pour le même dégagement."},
 TURNOVER:{definition:'Une action du joueur provoque la perte de la possession de son équipe.',choices:"Précise la cause : mauvaise passe, mauvais contrôle, dribble perdu, dépossédé ou sortie. Si la perte est déjà renseignée sur une action, ne la compte pas une deuxième fois."},
 FOUL:{definition:'Une infraction observée et sanctionnée ou clairement signalée pendant le match.',choices:"Commise : le joueur ciblé fait la faute. Subie : il la reçoit. Identifie l’adversaire : une seule action compte la faute commise et la faute subie."},
 TOUCH:{definition:'Contact volontaire et contrôlé du joueur avec le ballon.',choices:'La position observée permet de qualifier une touche dans la surface adverse. Ne pas confondre avec une remise en jeu à la touche.'},
 SAVE:{definition:'Le gardien empêche un tir cadré d’entrer dans le but.',choices:"Capté : le gardien garde le ballon. Repoussé : il le renvoie. Si le gardien est déjà identifié sur le tir cadré, son arrêt est compté. N’ajoute pas une deuxième action pour le même arrêt."},
};
