/** Operational definitions used while manually observing a match. */
export const actionCriteria:Record<string,{definition:string;choices:string}>= {
 PASS:{definition:'Un joueur transmet volontairement le ballon à un coéquipier. Une passe est réussie si ce coéquipier reçoit le ballon ; elle est ratée si le ballon sort ou est récupéré par un adversaire.',choices:'Passe clé : crée directement une occasion de tir. Passe décisive : dernière passe menant au but, attribuée au passeur dans le but enregistré. Une passe marquée décisive seule ne crée pas une passe décisive supplémentaire. Ne pas compter une touche de balle comme une passe.'},
 SHOT:{definition:'Tentative volontaire de marquer. Un tir cadré entre dans le but ou est arrêté par le gardien ; un tir non cadré manque le but.',choices:'Bloqué : stoppé par un joueur de champ. Montant : touche le poteau ou la barre sans entrer. But : sélectionner le passeur ou « Sans passe décisive ». Un CSC se saisit séparément.'},
 OWN_GOAL:{definition:'Un joueur envoie involontairement le ballon dans le but de sa propre équipe.',choices:'Attribuer le CSC à son auteur. Le but est ajouté à l’équipe adverse ; aucun but personnel, tir ou passe décisive n’est ajouté.'},
 DRIBBLE:{definition:'Tentative de passer un adversaire avec le ballon sous contrôle.',choices:'Réussi : le joueur passe l’adversaire en conservant le ballon. Raté : l’adversaire empêche le passage. La possession perdue se précise séparément.'},
 DUEL:{definition:'Deux adversaires se disputent directement le contrôle du ballon.',choices:'Gagné ou perdu du point de vue du joueur ciblé. Préciser au sol ou aérien. Le même duel crédite les deux joueurs : ne pas saisir une seconde ligne pour son adversaire.'},
 TACKLE:{definition:'Intervention d’un défenseur pour retirer le ballon à son porteur.',choices:'Gagné : le défenseur touche ou dégage le ballon et interrompt le porteur. Perdu : le porteur conserve le ballon. Préciser ballon récupéré, sorti ou conservé par l’adversaire ; faute si l’intervention est sanctionnée.'},
 INTERCEPTION:{definition:'Un joueur coupe une passe adverse avant qu’elle atteigne son destinataire.',choices:'Une interception compte aussi comme une récupération. Une passe ratée avec un intercepteur identifié crédite déjà ce joueur ; ne pas la saisir une deuxième fois pour ajouter un compteur.'},
 RECOVERY:{definition:'Un joueur prend le contrôle d’un ballon libre ou récupère la possession après une erreur adverse.',choices:'Préciser la cause observée. Ce n’est pas une simple réception de passe d’un coéquipier. Une position dans le dernier tiers permet de qualifier la récupération haute. Les interceptions comptent déjà dans les récupérations.'},
 BLOCK:{definition:'Un joueur de champ arrête un tir adverse avant qu’il atteigne le but.',choices:'Identifier le tireur si possible. Un tir bloqué avec ce défenseur identifié crédite déjà le blocage ; un arrêt du gardien se saisit comme un arrêt.'},
 CLEARANCE:{definition:'Un joueur éloigne volontairement le ballon d’une zone dangereuse, sans chercher une passe contrôlée.',choices:'Préciser pied ou tête. Ne pas le compter également comme une passe réussie.'},
 TURNOVER:{definition:'Une action du joueur provoque la perte de la possession de son équipe.',choices:'Préciser mauvaise passe, mauvais contrôle, dribble perdu, dépossédé ou sortie. Une possession perdue déjà renseignée sur une action ne doit pas être comptée une seconde fois.'},
 FOUL:{definition:'Une infraction observée et sanctionnée ou clairement signalée pendant le match.',choices:'Commise : le joueur ciblé est l’auteur. Subie : il est la victime. Identifier l’adversaire ; une seule saisie crédite la faute commise et la faute subie.'},
 TOUCH:{definition:'Contact volontaire et contrôlé du joueur avec le ballon.',choices:'La position observée permet de qualifier une touche dans la surface adverse. Ne pas confondre avec une remise en jeu à la touche.'},
 SAVE:{definition:'Le gardien empêche un tir cadré d’entrer dans le but.',choices:'Capté : il conserve le ballon. Repoussé : il le renvoie. Un tir cadré avec un gardien identifié crédite déjà son arrêt ; ne pas ajouter un second compteur pour le même tir.'},
};
