import {withoutRetiredStats} from './model';
import {db,rows,readLeague,identity} from './repository';
import {defaultAwards,candidatesFor,scoreAward,uniqueWinner,eligiblePlayerIds,validateDefinition,type AwardDefinition} from './awards';
import type {League} from './model';
type User={userId:string;email:string}|null;
const email=(value:string)=>value.trim().toLowerCase();
async function requireAdmin(user:User){if(!user||!(await identity(user)).admin)throw Error('Accès administrateur requis.');}
async function voter(user:User){if(!user)return null;const mail=email(user.email);const links=await rows('SELECT * FROM award_identities WHERE email=?',mail);const link=links[0];if(!link||link.user_id&&link.user_id!==user.userId)return null;if(!link.user_id){await db().prepare('UPDATE award_identities SET user_id=? WHERE email=? AND user_id IS NULL').bind(user.userId,mail).run();const bound=await rows('SELECT * FROM award_identities WHERE email=?',mail);if(bound[0]?.user_id!==user.userId)return null}return link.player_id as string}
function parseAward(r:any):AwardDefinition{return{id:r.id,seasonId:r.season_id,name:r.name,kind:r.kind,mode:r.mode,statWeight:r.stat_weight,voteWeight:r.vote_weight,votingOpen:!!r.voting_open,forbidSelf:!!r.forbid_self,candidates:JSON.parse(r.candidates_json),metric:withoutRetiredStats(JSON.parse(r.metric_json))}}
export async function awardGET(user:User){const [league,defs,rawVotes,links,auth]=await Promise.all([readLeague(),rows('SELECT * FROM award_definitions'),rows('SELECT season_id,award_id,voter_player_id,candidate_id FROM award_votes'),rows('SELECT email,user_id,player_id FROM award_identities'),identity(user)]);const playerId=await voter(user);const definitions=defs.map(parseAward);const awards=league.seasons.filter(s=>!s.demo).map(season=>({seasonId:season.id,contribution:season.contribution,pot:Math.round(new Set(league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished').flatMap(m=>m.participants.map(p=>p.playerId))).size*season.contribution*100)/100,awards:defaultAwards(season.id).map(defaultAward=>definitions.find(d=>d.id===defaultAward.id)??defaultAward).concat(definitions.filter(d=>d.seasonId===season.id&&!d.id.startsWith(season.id+':'))).map(award=>{const closed=!award.votingOpen;const votes=rawVotes.filter(v=>v.award_id===award.id&&v.season_id===season.id);const scored=scoreAward(award,league,season,votes.map(v=>({candidateId:v.candidate_id})),closed);return{...award,nominatedCandidates:award.candidates,candidates:candidatesFor(award,league,season),scores:closed?scored:undefined,winner:closed?uniqueWinner(scored):null,myVote:playerId?votes.find(v=>v.voter_player_id===playerId)?.candidate_id??null:null,voteCount:closed?votes.length:undefined}})}));return{awards,playerId,admin:auth.admin,links:auth.admin?links:undefined}}
export async function awardPOST(body:unknown,user:User){if(!body||typeof body!=='object')throw Error('Requête invalide.');const input=body as Record<string,unknown>;const action=input.action;const league=await readLeague();if(action==='link'){await requireAdmin(user);const mail=typeof input.email==='string'?email(input.email):'';const playerId=String(input.playerId??'');if(!/^\S+@\S+\.\S+$/.test(mail)||!league.players.some(p=>p.id===playerId&&!p.demo))throw Error('Compte ou joueur invalide.');await db().prepare('INSERT INTO award_identities(email,user_id,player_id) VALUES(?,NULL,?) ON CONFLICT(email) DO UPDATE SET player_id=excluded.player_id,user_id=NULL').bind(mail,playerId).run();return awardGET(user)}
 if(action==='unlink'){await requireAdmin(user);await db().prepare('DELETE FROM award_identities WHERE email=?').bind(email(String(input.email??''))).run();return awardGET(user)}
 if(action==='save'){await requireAdmin(user);const award=input.award as AwardDefinition;if(!award||typeof award!=='object'||!league.seasons.some(s=>s.id===award.seasonId&&!s.demo))throw Error('Saison invalide.');award.metric=withoutRetiredStats(award.metric??{});validateDefinition(award);if(!award.id||award.id.length>120)throw Error('Identifiant invalide.');const existing=(await rows('SELECT * FROM award_definitions WHERE id=?',award.id))[0];if(existing&&existing.season_id!==award.seasonId)throw Error('Award déjà utilisé.');if(existing?.voting_open&&award.kind!==existing.kind)throw Error('Fermez le vote avant de changer les candidats.');const voteCount=existing?(await rows('SELECT COUNT(*) AS n FROM award_votes WHERE award_id=?',award.id))[0]?.n??0:0;if(voteCount){const prior=parseAward(existing);const frozen=(a:AwardDefinition)=>JSON.stringify({kind:a.kind,mode:a.mode,statWeight:a.statWeight,voteWeight:a.voteWeight,forbidSelf:a.forbidSelf,candidates:a.candidates,metric:a.metric});if(frozen(prior)!==frozen(award))throw Error('Des votes existent : seuls le nom et l’ouverture peuvent changer.');}const season=league.seasons.find(s=>s.id===award.seasonId)!;const eligible=candidatesFor(award,league,season);if(award.candidates.some(c=>!eligible.some(e=>e.id===c.id)))throw Error('Une nomination est inéligible.');if(award.votingOpen&&(award.mode==='automatic'||eligible.length<2))throw Error('Deux nominations et un mode vote sont nécessaires pour ouvrir.');if(existing&&existing.voting_open&&JSON.stringify(award.candidates)!==existing.candidates_json)throw Error('Fermez le vote avant de modifier les nominations.');await db().prepare('INSERT INTO award_definitions(id,season_id,name,kind,mode,stat_weight,vote_weight,voting_open,forbid_self,candidates_json,metric_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,kind=excluded.kind,mode=excluded.mode,stat_weight=excluded.stat_weight,vote_weight=excluded.vote_weight,voting_open=excluded.voting_open,forbid_self=excluded.forbid_self,candidates_json=excluded.candidates_json,metric_json=excluded.metric_json').bind(award.id,award.seasonId,award.name.trim(),award.kind,award.mode,award.statWeight,award.voteWeight,+award.votingOpen,+award.forbidSelf,JSON.stringify(award.candidates),JSON.stringify(award.metric)).run();return awardGET(user)}
 if(action==='vote'){const playerId=await voter(user);if(!playerId)throw Error('Votre compte doit être lié à un joueur par un admin avant de voter.');const awardId=String(input.awardId??''),candidateId=String(input.candidateId??'');const r=(await rows('SELECT * FROM award_definitions WHERE id=?',awardId))[0];if(!r||!r.voting_open||r.mode==='automatic')throw Error('Ce vote est fermé.');const award=parseAward(r);const season=league.seasons.find(s=>s.id===award.seasonId);if(!season||season.demo)throw Error('Saison invalide.');if(!eligiblePlayerIds(league,season).includes(playerId))throw Error('Ce joueur ne remplit pas le seuil de participation.');const candidate=candidatesFor(award,league,season).find(c=>c.id===candidateId);if(!candidate)throw Error('Nomination invalide.');if(award.forbidSelf&&candidate.playerIds.includes(playerId))throw Error('Vous ne pouvez pas voter pour vous-même.');const result=await db().prepare('INSERT INTO award_votes(season_id,award_id,voter_player_id,candidate_id) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM award_definitions WHERE id=? AND voting_open=1) ON CONFLICT(season_id,award_id,voter_player_id) DO NOTHING').bind(season.id,award.id,playerId,candidateId,award.id).run();if(!result.meta.changes)throw Error('Vous avez déjà voté pour cet award.');return awardGET(user)}throw Error('Action inconnue.')}
