import type {League,Match,Player,Season} from './model';
import {aggregate} from './engine.ts';

export type AwardMode='automatic'|'vote'|'hybrid';
export type AwardKind='player'|'duo'|'moment';
export type Candidate={id:string;label:string;playerIds:string[];description?:string};
export type AwardDefinition={id:string;seasonId:string;name:string;kind:AwardKind;mode:AwardMode;statWeight:number;voteWeight:number;votingOpen:boolean;forbidSelf:boolean;candidates:Candidate[];metric:Record<string,number>};
export type AwardScore={candidate:Candidate;statScore:number|null;voteScore:number|null;total:number|null;votes:number;explanation:string[]};
const defaultSpecs:[string,string,AwardKind,Record<string,number>,AwardMode][]=[
 ['player-season','Joueur de la saison / Ballon d’Or','player',{rating:2,goals:1,assists:1,defensiveActions:1,wins:0.5},'hybrid'],
 ['golden-boot','Golden Boot','player',{goals:1},'automatic'],
 ['playmaker','Playmaker','player',{assists:2,keyPasses:1,chancesCreated:1,xa:1},'automatic'],
 ['defensive','Defensive Player','player',{defensiveActions:2,duelsWon:1},'automatic'],
 ['golden-boy','Golden Boy (critères à définir)','player',{},'vote'],
 ['most-improved','Most Improved','player',{improvement:1},'automatic'],
 ['best-duo','Best Duo','duo',{duoWins:1},'automatic'],
 ['moment','Moment de la saison','moment',{},'vote']
];
export function defaultAwards(seasonId:string):AwardDefinition[]{return defaultSpecs.map(([id,name,kind,metric,mode])=>({id:`${seasonId}:${id}`,seasonId,name,kind,metric,mode,statWeight:mode==='hybrid'?.5:mode==='automatic'?1:0,voteWeight:mode==='hybrid'?.5:mode==='vote'?1:0,votingOpen:false,forbidSelf:true,candidates:[]}))}
export function eligiblePlayerIds(league:Pick<League,'players'|'matches'>,season:Season){const matches=league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished');const required=Math.ceil(matches.length*season.minParticipation);return league.players.filter(p=>!p.demo&&!p.archived&&matches.length>0&&matches.filter(m=>m.participants.some(x=>x.playerId===p.id)).length>=required).map(p=>p.id)}
function playerCandidates(players:Player[],ids:string[]):Candidate[]{return ids.map(id=>{const p=players.find(x=>x.id===id)!;return{id,label:p.name,playerIds:[id]}})}
export function candidatesFor(award:AwardDefinition,league:Pick<League,'players'|'matches'>,season:Season):Candidate[]{const eligible=new Set(eligiblePlayerIds(league,season));if(award.kind==='player'){if(award.id.endsWith(':golden-boy')&&!award.candidates.length)return[];if(award.candidates.length)return award.candidates.filter(c=>c.playerIds.length===1&&eligible.has(c.playerIds[0]));return playerCandidates(league.players,[...eligible])}if(award.candidates.length)return award.candidates.filter(c=>c.playerIds.every(id=>eligible.has(id))&&(award.kind!=='duo'||sameTeamGames(league,season,c.playerIds)>=minDuo(league)));if(award.kind==='moment')return league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished').flatMap(m=>m.events.filter(e=>e.type==='GOAL').map(e=>({id:e.id,label:`Match #${m.number} · ${league.players.find(p=>p.id===e.playerId)?.name??'Joueur'} · but`,playerIds:[e.playerId],description:e.timestamp==null?'':`${Math.floor(e.timestamp/60)}e minute`})));
 const ids=[...eligible];const games=league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished');return ids.flatMap((a,i)=>ids.slice(i+1).filter(b=>sameTeamGames(league,season,[a,b])>=minDuo(league)).map(b=>({id:[a,b].sort().join(':'),label:`${league.players.find(p=>p.id===a)?.name} + ${league.players.find(p=>p.id===b)?.name}`,playerIds:[a,b]})))}
function minDuo(league:Pick<League,'matches'>){return (league as League).settings?.minDuo??3}
function sameTeamGames(league:Pick<League,'matches'>,season:Season,ids:string[]){return league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished'&&ids.length===2&&ids.every(id=>m.participants.some(p=>p.playerId===id))&&m.participants.find(p=>p.playerId===ids[0])?.team&&m.participants.find(p=>p.playerId===ids[0])?.team===m.participants.find(p=>p.playerId===ids[1])?.team).length}
function observations(league:Pick<League,'players'|'matches'>,season:Season,c:Candidate):Record<string,number|null>{const matches=league.matches.filter(m=>m.seasonId===season.id&&m.status==='finished');if(c.playerIds.length===2){const together=matches.filter(m=>c.playerIds.every(id=>m.participants.some(p=>p.playerId===id))&&m.participants.find(p=>p.playerId===c.playerIds[0])?.team&&m.participants.find(p=>p.playerId===c.playerIds[0])?.team===m.participants.find(p=>p.playerId===c.playerIds[1])?.team);const wins=together.filter(m=>{const a=m.participants.find(p=>p.playerId===c.playerIds[0]);const b=m.participants.find(p=>p.playerId===c.playerIds[1]);return a?.team&&a.team===b?.team&&(a.team==='A'?m.scoreA!>m.scoreB!:m.scoreB!>m.scoreA!)}).length;return{duoWins:wins}}
 const id=c.playerIds[0];const summary=aggregate(league.players,matches).find(s=>s.player.id===id);if(!summary)return{};const own=matches.filter(m=>m.participants.some(p=>p.playerId===id)).sort((a,b)=>a.date.localeCompare(b.date)||a.number-b.number||a.id.localeCompare(b.id));const half=Math.floor(own.length/2);const rating=(slice:Match[])=>{const vals=slice.map(m=>m.participants.find(p=>p.playerId===id)?.stats.rating).filter((n):n is number=>n!=null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null};const early=rating(own.slice(0,half)),late=rating(own.slice(half));return{...summary.stats,wins:summary.wins,improvement:half>0&&early!=null&&late!=null?late-early:null}}
export function scoreAward(award:AwardDefinition,league:Pick<League,'players'|'matches'>,season:Season,votes:{candidateId:string}[],closed:boolean):AwardScore[]{
 const candidates=candidatesFor(award,league,season);const raw=candidates.map(c=>({c,obs:observations(league,season,c)}));
 const ranges=Object.fromEntries(Object.keys(award.metric).map(key=>{const values=raw.map(x=>x.obs[key]).filter((v):v is number=>v!=null);return[key,{min:Math.min(...values),max:Math.max(...values)}]}));
 const voteCounts=new Map<string,number>();for(const v of votes)if(candidates.some(c=>c.id===v.candidateId))voteCounts.set(v.candidateId,(voteCounts.get(v.candidateId)??0)+1);const maxVotes=Math.max(0,...voteCounts.values());
 return raw.map(x=>{const count=voteCounts.get(x.c.id)??0;const metrics=Object.entries(award.metric).filter(([k,w])=>w>0&&x.obs[k]!=null);const weight=metrics.reduce((n,[,w])=>n+w,0);const statScore=weight?metrics.reduce((n,[k,w])=>{const range=ranges[k];return n+w*(range.max===range.min?100:100*((x.obs[k]??0)-range.min)/(range.max-range.min))},0)/weight:null;
 const voteScore=closed?(maxVotes?100*count/maxVotes:0):null;const total=closed?(award.mode==='automatic'?statScore:maxVotes===0?null:award.mode==='vote'?voteScore:statScore==null?null:award.statWeight*statScore+award.voteWeight*voteScore!):null;
 return{candidate:x.c,statScore:closed?statScore:null,voteScore,total,votes:closed?count:0,explanation:metrics.map(([k])=>`${k}: ${Math.round((x.obs[k]??0)*10)/10}`)}}).sort((a,b)=>closed?(b.total??-Infinity)-(a.total??-Infinity)||a.candidate.label.localeCompare(b.candidate.label):a.candidate.label.localeCompare(b.candidate.label))
}
export function uniqueWinner(scores:AwardScore[]):Candidate|null{return scores[0]?.total!=null&&(scores.length<2||scores[1].total==null||Math.abs(scores[0].total-scores[1].total)>1e-9)?scores[0].candidate:null}
export function validateDefinition(a:AwardDefinition){
 if(!a||typeof a!=='object'||typeof a.id!=='string'||typeof a.seasonId!=='string'||typeof a.name!=='string'||!a.name.trim()||a.name.length>80)throw Error('Award invalide.');
 if(!['player','duo','moment'].includes(a.kind)||!['automatic','vote','hybrid'].includes(a.mode)||typeof a.votingOpen!=='boolean'||typeof a.forbidSelf!=='boolean')throw Error('Type d’award invalide.');
 if(!Number.isFinite(a.statWeight)||!Number.isFinite(a.voteWeight)||a.statWeight<0||a.voteWeight<0||Math.abs(a.statWeight+a.voteWeight-1)>.001)throw Error('Les poids doivent totaliser 100 %.');
 if(a.mode==='automatic'&&(a.statWeight!==1||a.voteWeight!==0)||a.mode==='vote'&&(a.statWeight!==0||a.voteWeight!==1))throw Error('Poids incompatibles avec le mode.');
 if(!a.metric||typeof a.metric!=='object'||Array.isArray(a.metric)||Object.values(a.metric).some(w=>typeof w!=='number'||!Number.isFinite(w)||w<0)||a.mode!=='vote'&&!Object.values(a.metric).some(w=>w>0))throw Error('Statistiques pondérées invalides.');
 if(!Array.isArray(a.candidates)||a.candidates.length>200)throw Error('Nominations invalides.');const seen=new Set<string>();for(const c of a.candidates){if(!c||typeof c.id!=='string'||!c.id||c.id.length>120||seen.has(c.id)||typeof c.label!=='string'||!c.label.trim()||c.label.length>120||!Array.isArray(c.playerIds)||c.playerIds.some(id=>typeof id!=='string'||!id)||new Set(c.playerIds).size!==c.playerIds.length||c.playerIds.length!==(a.kind==='duo'?2:1)||c.description!=null&&typeof c.description!=='string')throw Error('Nomination invalide.');seen.add(c.id)}
}
