import {canonicalEffects,canonicalKeys,isV2,secondaryAssistCredits} from './actions.ts';
import type {Match,MatchEvent} from './model.ts';
import {eventMap,currentMatch} from './model.ts';
export function coordinates(metadata:Record<string,unknown>){const p=(metadata.position??metadata.shotPosition) as {x?:unknown;y?:unknown}|undefined;return p&&typeof p.x==='number'&&typeof p.y==='number'&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=100&&p.y>=0&&p.y<=100?{x:p.x,y:p.y}:null}
export function zone(p:{x:number;y:number}){return {finalThird:p.x>=200/3,dangerZone:p.x>=85&&p.y>=25&&p.y<=75,lane:p.y<100/3?'gauche':p.y>200/3?'droite':'centre',angleToGoal:Math.round(Math.atan2(Math.abs(50-p.y)*.2,Math.max(.001,(100-p.x)*.4))*180/Math.PI),distanceToGoal:Math.round(Math.hypot((100-p.x)*.4,(50-p.y)*.2)*10)/10}}
export function eventKeys(e:MatchEvent){if(isV2(e))return canonicalKeys(e,[]);return [...(eventMap[e.type]??[]),...(e.type==='GOAL'&&e.relatedPlayerId?['assists']:[]),...(e.type==='RECOVERY'&&coordinates(e.metadata)?.x!>=200/3?['highRecoveries']:[])]}
export function projectEvents(input:Match){const m=currentMatch(structuredClone(input)),tracked=new Set(m.trackedKeys);m.events.forEach(e=>eventKeys(e).forEach(k=>tracked.add(k)));const secondary=secondaryAssistCredits(m.events);if(secondary.length)tracked.add('secondaryAssists');m.participants=m.participants.map(p=>({...p,stats:{...p.stats,...Object.fromEntries([...tracked].map(k=>[k,0]))}}));for(const e of m.events){const p=m.participants.find(p=>p.playerId===e.playerId);if(!p)continue;if(isV2(e)){for(const [id,k]of canonicalEffects(e,m.events)){const target=m.participants.find(p=>p.playerId===id);if(target)target.stats[k]=(target.stats[k]??0)+1}const point=coordinates(e.metadata);if(point)e.metadata.zone=zone(point);continue}if(!e.metadata.atomic&&e.timestamp!=null&&['SHOT','PASS_ATTEMPT','DRIBBLE_ATTEMPT','DUEL'].includes(e.type)&&m.events.some(other=>other.id!==e.id&&!other.metadata.atomic&&other.playerId===e.playerId&&other.timestamp===e.timestamp&&({SHOT:['SHOT_ON_TARGET','SHOT_OFF_TARGET','SHOT_BLOCKED','GOAL'],PASS_ATTEMPT:['PASS_COMPLETED','PASS_FAILED'],DRIBBLE_ATTEMPT:['DRIBBLE_COMPLETED','DRIBBLE_FAILED'],DUEL:['DUEL_WON','DUEL_LOST']}[e.type]??[]).includes(other.type)))continue;const keys=eventKeys(e);if(e.type==='GOAL'){for(const k of ['shots','shotsOnTarget'])if(tracked.has(k))keys.push(k)}for(const k of keys){const target=k==='assists'&&e.type==='GOAL'?m.participants.find(p=>p.playerId===e.relatedPlayerId):p;if(target)target.stats[k]=(target.stats[k]??0)+1}const point=coordinates(e.metadata);if(point)e.metadata={...e.metadata,position:point,zone:zone(point)};}for(const credit of secondary){const p=m.participants.find(p=>p.playerId===credit.playerId);if(p)p.stats.secondaryAssists=(p.stats.secondaryAssists??0)+1}m.trackedKeys=[...tracked];if(m.status==='finished'&&tracked.has('goals')){m.scoreA=m.participants.filter(p=>p.team==='A').reduce((s,p)=>s+(p.stats.goals??0),0);m.scoreB=m.participants.filter(p=>p.team==='B').reduce((s,p)=>s+(p.stats.goals??0),0)}return m}
export const offensiveActions=new Set(['PASS','DRIBBLE','GOAL','SHOT','SHOT_ON_TARGET','SHOT_OFF_TARGET','SHOT_BLOCKED','ASSIST','KEY_PASS','DRIBBLE_COMPLETED','CROSS','TOUCH_OPPOSITION_BOX']);
export const defensiveActions=new Set(['SAVE','DUEL','TACKLE','INTERCEPTION','RECOVERY','BLOCK','CLEARANCE','DUEL_WON','DUEL_LOST','POSSESSION_WON_FINAL_THIRD']);
export function positionedEvents(matches:Match[],playerId?:string){return matches.filter(m=>m.status==='finished').flatMap(m=>m.events.filter(e=>!playerId||e.playerId===playerId).map(e=>({...e,matchId:m.id,position:coordinates(e.metadata)}))).filter(e=>e.position!=null)}

export function projectSecondaryAssists(input:Match){const credits=secondaryAssistCredits(input.events);if(!credits.length&&!input.trackedKeys.includes('secondaryAssists'))return input;const counts=new Map<string,number>();for(const c of credits)counts.set(c.playerId,(counts.get(c.playerId)??0)+1);return {...input,trackedKeys:[...new Set([...input.trackedKeys,'secondaryAssists'])],participants:input.participants.map(p=>({...p,stats:{...p.stats,secondaryAssists:counts.get(p.playerId)??0}}))}}
