export type Stats=Record<string,number|null>;
export type Player={id:string;name:string;bio:string;photo:string;archived:boolean;demo:boolean;funFacts:string;attributes:Record<string,number>;version:number};
export type Season={id:string;name:string;start:string;end:string;status:'active'|'inactive'|'finished'|'archived';demo:boolean;contribution:number;winnerId:string|null;minParticipation:number;version:number};
export type Participant={playerId:string;team:'A'|'B'|null;stats:Stats;auto_rating?:number|null;admin_rating?:number|null;final_rating?:number|null;ratingExplanation?:string[]};
export type MatchEvent={id:string;playerId:string;team:'A'|'B';type:string;timestamp:number|null;relatedPlayerId:string|null;metadata:Record<string,unknown>};
export type Match={id:string;seasonId:string;number:number;date:string;duration:number;location:string;status:'scheduled'|'finished'|'cancelled';scoreA:number|null;scoreB:number|null;mvpId:string|null;level:number;video:string;participants:Participant[];events:MatchEvent[];trackedKeys:string[];notes?:string;teamAName?:string;teamBName?:string;version:number};
export type Settings={minRating:number;minRadar:number;minDuo:number;minPasses:number;minAttempts:number;ratingWeights?:Record<string,number>};
export type League={players:Player[];seasons:Season[];matches:Match[];settings:Settings;admin:boolean;bootstrap:boolean;user:string|null};
export const defaultSettings:Settings={minRating:5,minRadar:5,minDuo:5,minPasses:30,minAttempts:10};
export const statGroups:Record<string,Record<string,string>>={
Tir:{goals:'Buts',xg:'Buts attendus (xG)',xgot:'xG cadrés (xGOT)',shots:'Tirs',shotsOnTarget:'Tirs cadrés'},
Passe:{secondaryAssists:'Secondary Assists',assists:'Passes décisives',xa:'Passes décisives attendues (xA)',passesCompleted:'Passes réussies',passesAttempted:'Passes tentées',longPassesCompleted:'Passes longues précises',longPassesAttempted:'Passes longues tentées',chancesCreated:'Occasions créées',keyPasses:'Passes clés',crossesCompleted:'Centres réussis',crossesAttempted:'Centres tentés'},
Possession:{dribblesCompleted:'Dribbles réussis',dribblesAttempted:'Dribbles tentés',duelsWon:'Duels remportés',duelsAttempted:'Duels disputés',aerialDuelsWon:'Duels aériens remportés',aerialDuelsAttempted:'Duels aériens disputés',touches:'Touches',boxTouches:'Touches dans la surface adverse',turnovers:'Ballons perdus',foulsWon:'Fautes subies'},
Défense:{saves:'Arrêts',tackles:'Tacles',interceptions:'Interceptions',blocks:'Tirs bloqués',fouls:'Fautes commises',recoveries:'Récupérations',highRecoveries:'Récupérations dans le dernier tiers',dribbledPast:'Dribbles subis',clearances:'Dégagements',goalsConceded:'Buts encaissés sur le terrain',xgConceded:'xG concédés sur le terrain',},};
export const labels:Record<string,string>={...Object.assign({},...Object.values(statGroups)),rating:'Rating',ga:'G+A',wins:'Victoires',winRate:'Taux de victoire',elo:'ELO',mvp:'MVP',appearances:'Matchs',passPct:'Passes réussies %',longPassPct:'Passes longues %',crossPct:'Centres %',dribblePct:'Dribbles %',duelPct:'Duels %',aerialPct:'Duels aériens %',shotPct:'Tirs cadrés %',conversion:'Conversion %',defensiveActions:'Actions défensives',goalsMinusXg:'Buts − xG'};
export const rawKeys=[...Object.keys(Object.assign({},...Object.values(statGroups))),'rating'];
export const ratios:Record<string,[string,string]>={passPct:['passesCompleted','passesAttempted'],longPassPct:['longPassesCompleted','longPassesAttempted'],crossPct:['crossesCompleted','crossesAttempted'],dribblePct:['dribblesCompleted','dribblesAttempted'],duelPct:['duelsWon','duelsAttempted'],aerialPct:['aerialDuelsWon','aerialDuelsAttempted'],shotPct:['shotsOnTarget','shots'],conversion:['goals','shots']};
export const eventMap:Record<string,string[]>={GOAL:['goals'],ASSIST:['assists'],SHOT:['shots'],SHOT_ON_TARGET:['shots','shotsOnTarget'],SHOT_OFF_TARGET:['shots'],SHOT_BLOCKED:['shots'],PASS_ATTEMPT:['passesAttempted'],PASS_COMPLETED:['passesCompleted','passesAttempted'],PASS_FAILED:['passesAttempted'],LONG_PASS:['longPassesAttempted'],CROSS:['crossesAttempted'],LONG_PASS_ATTEMPT:['longPassesAttempted'],LONG_PASS_COMPLETED:['longPassesCompleted'],CROSS_ATTEMPT:['crossesAttempted'],CROSS_COMPLETED:['crossesCompleted'],KEY_PASS:['keyPasses','chancesCreated'],TOUCH:['touches'],TOUCH_OPPOSITION_BOX:['boxTouches'],DRIBBLE_ATTEMPT:['dribblesAttempted'],DRIBBLE_COMPLETED:['dribblesCompleted','dribblesAttempted'],DRIBBLE_FAILED:['dribblesAttempted'],DUEL:['duelsAttempted'],DUEL_WON:['duelsWon','duelsAttempted'],DUEL_LOST:['duelsAttempted'],AERIAL_DUEL:['aerialDuelsAttempted'],AERIAL_DUEL_WON:['aerialDuelsWon'],TACKLE:['tackles'],INTERCEPTION:['interceptions'],RECOVERY:['recoveries'],CLEARANCE:['clearances'],BLOCK:['blocks'],POSSESSION_WON_FINAL_THIRD:['highRecoveries'],TURNOVER:['turnovers'],FOUL_COMMITTED:['fouls'],FOUL_WON:['foulsWon']};
export const attributes=['overall','finition','creation','passe','percussion','duels','defense'];

export const teamName=(m:Match,side:string)=>side==='A'?(m.teamAName||'Équipe A'):side==='B'?(m.teamBName||'Équipe B'):'À répartir';

export const retiredStats=new Set(['boxShots','npxg','yellowCards','redCards','cleanSheets']);
export const withoutRetiredStats=<T>(stats:Record<string,T>)=>Object.fromEntries(Object.entries(stats).filter(([key])=>!retiredStats.has(key)));
export function currentMatch(m:Match):Match{return {...m,trackedKeys:m.trackedKeys.filter(k=>!retiredStats.has(k)),participants:m.participants.map(p=>({...p,stats:withoutRetiredStats(p.stats)})),events:m.events.filter(e=>!['CARD','YELLOW_CARD','RED_CARD'].includes(e.type)).map(e=>e.type==='FOUL'&&['YELLOW','RED','SECOND_YELLOW'].includes(String(e.metadata.outcome))?{...e,metadata:{...e.metadata,outcome:'SIMPLE'}}:e)}}
