import type {Match,Stats,Participant} from './model.ts';
import {automaticRatingV2,ratingStats} from './rating-v2.ts';
export const ratingConfig={base:6,min:3,max:10,families:{finition:{weight:1,keys:['goals','shotsOnTarget']},creation:{weight:1,keys:['assists','keyPasses','chancesCreated']},passes:{weight:1,keys:['passesCompleted','longPassesCompleted','passPct','longPassPct']},percussion:{weight:1,keys:['dribblesCompleted','boxTouches','foulsWon','dribblePct']},duels:{weight:1,keys:['duelsWon','aerialDuelsWon','duelPct']},defense:{weight:1,keys:['tackles','interceptions','recoveries','blocks','clearances','saves']}},turnoverPenalty:.06};
const mean=(a:number[])=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);
export function automaticRating(stats:Stats,peers:Stats[],weights:Record<string,number>={}){const evidence:string[]=[];const values:{score:number;weight:number}[]=[];for(const [family,config]of Object.entries(ratingConfig.families)){const scores=config.keys.flatMap(k=>{const v=stats[k];if(v==null)return [];const observed=peers.map(p=>p[k]).filter((n):n is number=>n!=null);if(observed.length<3)return [];const typical=mean(observed);const score=typical===0?0:Math.max(-1,Math.min(1,(v-typical)/Math.max(1,typical)));return [score]});if(scores.length&&(weights[family]??config.weight)>0){const score=mean(scores);values.push({score,weight:weights[family]??config.weight});evidence.push(`${family} : ${score>.5?'très au-dessus':score>0?'au-dessus':score<-.5?'en dessous':'proche'} de la moyenne du groupe`);}}
if(!values.length)return{value:null,explanation:['Pas assez de données comparables pour calculer une note.']};const avg=values.reduce((s,v)=>s+v.score*v.weight,0)/values.reduce((s,v)=>s+v.weight,0);const peak=Math.max(...values.map(v=>v.score));const positive=peak>0?.8*peak+.2*Math.max(0,avg):avg;const penalty=Math.min(1,(stats.turnovers??0)*ratingConfig.turnoverPenalty);const value=Math.round(Math.max(ratingConfig.min,Math.min(ratingConfig.max,ratingConfig.base+4*positive-penalty))*10)/10;if(penalty)evidence.push(`Pertes de balle : −${penalty.toFixed(1)}`);evidence.push(`${values.length}/6 familles renseignées ; les données absentes ne sont pas des zéros.`);return {value,explanation:evidence};}
function comparableStats(p:Participant):Stats {
 const scale=p.minutesPlayed!=null&&p.minutesPlayed>0?60/p.minutesPlayed:1;
 const stats:Stats=Object.fromEntries(Object.entries(p.stats).map(([k,v])=>[k,v==null?null:v*scale]));
 for(const [key,success,attempt]of [['passPct','passesCompleted','passesAttempted'],['longPassPct','longPassesCompleted','longPassesAttempted'],['dribblePct','dribblesCompleted','dribblesAttempted'],['duelPct','duelsWon','duelsAttempted']])if(p.stats[success]!=null&&(p.stats[attempt]??0)>=5)stats[key]=100*p.stats[success]!/p.stats[attempt]!;
 return stats;
}
export function legacyRateMatches(matches:Match[],weights:Record<string,number>={}) {
 const peers=matches.filter(m=>m.status==='finished').flatMap(m=>m.participants);
 return matches.map(m=>({...m,participants:m.participants.map(p=>{
  const timed=p.minutesPlayed!=null&&p.minutesPlayed>0;
  const comparable=peers.filter(q=>(q.role??'field')===(p.role??'field')&&(q.minutesPlayed==null||q.minutesPlayed>0)&&(q.minutesPlayed!=null&&q.minutesPlayed>0)===timed);
  const a=m.status==='finished'&&p.minutesPlayed!==0?automaticRating(comparableStats(p),comparable.map(comparableStats),weights):{value:null,explanation:['Temps de jeu nul ou match non terminé.']};
  const override=p.admin_rating??null,final=override??a.value;
  const coverage=(m.analysis?.publishedKeys??(m.analysis?.publishedAt?m.analysis.completeKeys:[]))?.length??0;
  return {...p,auto_rating:a.value,admin_rating:override,final_rating:final,stats:{...p.stats,rating:final},ratingExplanation:[...(override!=null?[`Note administrateur : ${override.toFixed(1)} (calcul automatique : ${a.value??'—'}).`]:[]),...a.explanation,`${timed?'Volumes ramenés à 60 minutes de présence confirmée.':'Temps de jeu inconnu : comparaison des volumes par match avec les autres temps inconnus.'} Rôle : ${p.role==='goalkeeper'?'gardien':p.role==='mixed'?'champ et gardien':'champ'} ; ${comparable.length} observations comparables.`,m.analysis?`${coverage} catégories validées par vidéo ; autres données issues de la feuille de match.`:'Données historiques : couverture vidéo non documentée.','Note dynamique : la référence évolue avec les matchs comparables.']};
 })}));
}
export function rateMatches(matches:Match[],weights:Record<string,number>={},engine:'v1'|'v2'='v2'):Match[] {
 if(engine==='v1')return legacyRateMatches(matches,weights).map(m=>({...m,participants:m.participants.map(p=>({...p,ratingVersion:'v1' as const}))}));
 return matches.map(m=>{
  const stats=ratingStats(m);
  const peers=stats.filter((_,i)=>m.participants[i].team!=null&&m.participants[i].minutesPlayed!==0);
  return {...m,participants:m.participants.map((p,i)=>{
   const a=m.status==='finished'&&p.team!=null&&p.minutesPlayed!==0?automaticRatingV2(stats[i],peers,weights):{value:null,domains:{},coverage:0,explanation:['Temps de jeu nul ou match non terminé.']};
   const override=p.admin_rating??null,final=override??a.value;
   return {...p,auto_rating:a.value,admin_rating:override,final_rating:final,ratingVersion:'v2.0' as const,ratingDomains:a.domains,ratingCoverage:a.coverage,stats:{...p.stats,rating:final},ratingExplanation:[...(override!=null?[`Note administrateur : ${override.toFixed(1)} (calcul automatique : ${a.value??'—'}).`]:[]),...a.explanation]};
  })};
 });
}
export const styleDefinitions=[{name:'Finisseur',reference:'Harry Kane',keys:['goals','shotsOnTarget']},{name:'Créateur',reference:'Kevin De Bruyne',keys:['assists','keyPasses','chancesCreated']},{name:'Métronome',reference:'Toni Kroos',keys:['passesCompleted','longPassesCompleted']},{name:'Percuteur',reference:'Eden Hazard',keys:['dribblesCompleted','boxTouches','foulsWon']},{name:'Duelliste',reference:'N’Golo Kanté',keys:['duelsWon','aerialDuelsWon']},{name:'Intercepteur',reference:'Sergio Busquets',keys:['interceptions','recoveries']},{name:'Stoppeur',reference:'Paolo Maldini',keys:['tackles','blocks','clearances']}];
function computePlayStyles(playerId:string,matches:Match[]){const finished=matches.filter(m=>m.status==='finished').sort((a,b)=>a.date.localeCompare(b.date)||a.number-b.number);const appearances=finished.filter(m=>m.participants.some(p=>p.playerId===playerId));if(appearances.length<3)return [];const ids=[...new Set(finished.flatMap(m=>m.participants.map(p=>p.playerId)))];const profiles=ids.map(id=>{const rows=finished.flatMap(m=>m.participants.filter(p=>p.playerId===id)).slice(-20);const values:Stats={};for(const key of [...new Set(styleDefinitions.flatMap(s=>s.keys))]){const seen=rows.map(p=>p.stats[key]).filter((v):v is number=>v!=null);if(seen.length>=3)values[key]=mean(seen)}return{id,values}});const target=profiles.find(p=>p.id===playerId)!;return styleDefinitions.flatMap(style=>{const evidence=style.keys.flatMap(key=>{const v=target.values[key],peers=profiles.map(p=>p.values[key]).filter((n):n is number=>n!=null);if(v==null||peers.length<3)return [];return[{key,value:v,percentile:100*(peers.filter(n=>n<v).length+.5*peers.filter(n=>n===v).length)/peers.length}]});if(!evidence.length)return [];return[{...style,score:Math.round(mean(evidence.map(e=>e.percentile))),evidence}] }).filter(s=>s.score>=60).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,3)}

export function playStyles(playerId:string,matches:Match[]){const current=computePlayStyles(playerId,matches);const ordered=matches.filter(m=>m.status==='finished'&&m.participants.some(p=>p.playerId===playerId)).sort((a,b)=>a.date.localeCompare(b.date)||a.number-b.number);const previous=computePlayStyles(playerId,matches.filter(m=>m.id!==ordered.at(-1)?.id));if(current.length&&previous.length){const incumbent=current.find(s=>s.name===previous[0].name);if(incumbent&&current[0].score-incumbent.score<8)return [incumbent,...current.filter(s=>s!==incumbent)].slice(0,3)}return current}
