import type {Definition,Rule,Weight} from './recognition.ts';
const g=(key:string,value:number):Rule=>({key,op:'gte',value});const l=(key:string,value:number):Rule=>({key,op:'lte',value});const lt=(key:string,value:number):Rule=>({key,op:'lt',value});const p=(key:string,value:number,low=false):Rule=>({key,op:'gte',value,percentile:true,low});const bottom=(key:string,value:number):Rule=>({key,op:'lte',value,percentile:true});const any=(...any:Rule[]):Rule=>({any});const count=(count:number,...of:Rule[]):Rule=>({count,of});
const w=(key:string,weight:number,low=false):Weight=>({key,weight,low});
function award(id:string,name:string,icon:string,description:string,weights:Weight[],rules:Rule[],ratio=false,category='Principaux'):Definition{return{id,name,icon,description,weights,rules,ratio,category}}
export const awardDefinitions:Definition[]=[
{...award('copro-or','COPRO D’OR','👑',"Le joueur le mieux classé sur l’ensemble de la saison.",[w('rating',50),w('mvpPM',20),w('collective',20),w('matches',10)],[]),always:true},
award('tn-or','TN D’OR','👟','Le meilleur buteur de la saison.',[w('goals',90),w('collective',10)],[g('goals',5),g('goalsPM',.4)],true),
award('maestro','MAESTRO','🎼',"Récompense les assists et les passes qui préparent les buts.",[w('assistsPM',25),w('secondaryAssistsPM',20),w('xaPM',25),w('chancesCreatedPM',20),w('collective',10)],[g('assistsSecondary',4),g('assistsSecondaryPM',.3)],true),
award('bullseye','BULLSEYE','🎯','Le finisseur le plus efficace.',[w('conversion',35),w('shotPct',25),w('goalsMinusXg',25),w('collective',15)],[g('goals',4),g('shots',10),g('conversion',25)],true),
award('ankle-breaker','ANKLE BREAKER','🕺',"Élimine ses adversaires en un contre un, avec volume et réussite.",[w('dribblesCompletedPM',40),w('dribblePct',30),w('foulsWon',15),w('collective',15)],[g('dribblesAttempted',15),g('dribblePct',55)],true),
award('metronome','METRONOME','🎛️',"Donne le tempo avec ses passes et garde le ballon en circulation.",[w('passesAttemptedPM',30),w('passPct',25),w('longPassesCompleted',15),w('lossRatio',15,true),w('collective',15)],[g('passesAttemptedPM',15),g('passPct',75)],true),
award('golden-glue','GOLDEN GLUE','🧲',"Fait le lien entre les coéquipiers, à la passe comme à la récupération.",[w('passesCompleted',20),w('passPct',15),w('secondaryAssists',15),w('recoveries',15),w('lossRatio',15,true),w('collective',20)],[count(4,p('passesCompleted',55),p('passPct',55),p('secondaryAssists',55),p('recoveries',55),p('lossRatio',55,true)),p('collective',60)],true),
award('v8','V8','🏎️',"Enchaîne les touches, les passes, les récupérations et les duels.",[w('touches',20),w('passesAttempted',20),w('recoveries',20),w('duelsWon',15),w('foulsWon',10),w('collective',15)],[count(4,...['touches','passesAttempted','recoveries','duelsWon','foulsWon'].map(k=>p(k,65)))]),
award('mr-propre','MR. PROPRE','🧼',"Récupère, intercepte et coupe les actions adverses.",[w('recoveries',30),w('interceptions',25),w('successfulTackles',20),w('blocks',10),w('collective',15)],[g('recoveriesPM',3),g('interceptionTacklePM',1)],true),
award('lockdown','LOCKDOWN','🔒',"Récompense les performances dans plusieurs aspects de la défense.",[w('duelPct',20),w('interceptions',15),w('tackles',15),w('blocks',10),w('aerialDuelsWon',10),w('dribbledPast',10,true),w('defensiveCollective',10),w('collective',10)],[g('duelPct',55),g('defActionsPM',2)],true),
award('duelist','DUELIST','⚔️',"Gagne beaucoup de duels, avec un taux de réussite élevé.",[w('duelsWonPM',45),w('duelPct',40),w('collective',15)],[g('duelsAttempted',30),g('duelPct',60)],true),
award('glow-up','THE GLOW UP','🚀',"La plus forte progression du rating au cours de la saison.",[w('improvement',80),w('collectiveProgress',20)],[g('matches',8),g('improvement',.5)],true),
award('consistent','MR. CONSISTENT','🧊',"Garde un bon rating avec peu d’écart d’un match à l’autre.",[w('variance',60,true),w('rating',20),w('collective',20)],[g('ratingCount',8),g('rating',6.5),l('std',.75)],true),
award('clutch','CLUTCH GENE','🧬',"Cumule les victoires avec un taux de réussite élevé.",[w('winRate',60),w('wins',40)],[g('winRate',60),g('wins',5)],true),
award('ironman','IRONMAN','🫡',"Récompense la présence en match et les victoires.",[w('matches',70),w('wins',30)],[g('attendance',75)]),
{...award('dynamic-duo','DYNAMIC DUO','🤝',"Le duo le mieux classé sur ses matchs joués ensemble.",[w('winRate',45),w('wins',25),w('rating',20),w('duoGaPM',10)],[g('matches',5),g('winRate',60),g('wins',3)],true),kind:'duo'},
award('bicraveur','BICRAVEUR','🌾',"Les occasions étaient là. Les buts un peu moins : le plus gros écart entre xG et buts marqués.",[w('wastedXg',100)],[g('shots',10),g('wastedXg',2)],false,'Banter'),
award('interstellar','INTERSTELLAR','🌌',"Beaucoup de tirs hors cadre. La NASA suit le dossier.",[w('offTarget',100)],[g('shots',12),lt('shotPct',40)],true,'Banter'),
award('croqueur','CROQUEUR','🐊',"Beaucoup de tirs, peu de buts et des occasions laissées en route.",[w('shots',40),w('conversion',35,true),w('wastedXg',25)],[g('shots',15),lt('conversion',15),g('wastedXg',1)],true,'Banter'),
award('drunk-driving','CONDUITE DE BALLE EN ÉTAT D’IVRESSE','🚔',"Beaucoup de dribbles tentés. Le ballon n’a pas toujours suivi le plan.",[w('failedDribbles',60),w('dribblePct',40,true)],[g('dribblesAttempted',20),lt('dribblePct',45)],true,'Banter'),
award('frere-arrete','FRÈRE ARRÊTE','🛑',"Perd souvent le ballon par rapport au nombre de touches.",[w('lossRatio',100)],[g('turnovers',30),p('lossRatio',85)],true,'Banter'),
award('traffic-cone','TRAFFIC CONE','🚧',"Souvent éliminé dans les duels défensifs.",[w('dribbledPast',60),w('duelPct',40,true)],[g('defensiveDuels',15),lt('defensiveDuelPct',40)],true,'Banter'),
award('casino','CASINO FC','🎰',"Le rating varie beaucoup d’un match à l’autre. Roulette activée.",[w('std',100)],[g('ratingCount',8),g('ratingRange',3)],true,'Banter'),
award('washed','WASHED ALLEGATIONS','🧼',"Le rating baisse nettement entre les deux moitiés de saison.",[w('decline',100)],[g('ratingCount',8),g('decline',.75)],true,'Banter'),
award('main-character','MAIN CHARACTER SYNDROME','🎭',"Prend une grosse part des tirs et des dribbles, avec peu d’occasions créées en retour.",[w('shotShare',40),w('dribbleShare',30),w('assists',-15),w('secondaryChances',-15)],[any(p('shots',80),p('dribblesAttempted',80)),bottom('creation',50)],true,'Banter')
];
const badge=(id:string,name:string,icon:string,category:string,description:string,rules:Rule[]):Definition=>({id,name,icon,category,description,rules,weights:[]});
export const badgeDefinitions:Definition[]=[
badge('aura','1000 AURA','👑','Status',"Un gros rating et des victoires régulières.",[p('rating',90),p('collective',75),p('mvpPM',70)]),
badge('boss','FINAL BOSS','👹','Status',"Pèse à la fois en attaque et en défense.",[p('rating',90),p('mvpPM',90),any(p('gaPM',75),p('defensiveImpact',75)),g('rating',7)]),
badge('locked','LOCKED IN','🔐','Status',"Un bon rating, match après match.",[p('rating',75),bottom('variance',25),g('ratingCount',6)]),
badge('lowkey','LOWKEY CARRY','🤫','Status',"Pèse sur les résultats au-delà des buts et des assists.",[p('rating',75),p('collective',75),bottom('gaPM',50),g('matches',6)]),
badge('demon','DEMON TIME','😈','Finishing',"Enchaîne les buts et les bonnes performances.",[p('gaPM',85),p('goalsPM',75),g('ga',4)]),
badge('aimbot','AIMBOT','🎯','Finishing',"Une grande part de ses tirs trouve le cadre.",[p('shotPct',90),p('conversion',70),g('shots',10)]),
badge('ice','ICE IN MY VEINS','🧊','Finishing',"Marque plus de buts que les xG ne le prévoyaient.",[p('goalsMinusXg',85),g('goals',4),g('goalsMinusXg',1)]),
badge('one-shot','ONE SHOT ONE KILL','💥','Finishing',"Peu de tirs, un gros taux de conversion.",[p('conversion',90),bottom('shotsPM',50),g('goals',3)]),
badge('ghost','GHOST MODE','👻','Finishing',"Touche peu le ballon, mais participe directement aux buts.",[bottom('touchesPM',30),p('gaPM',75),g('ga',3)]),
badge('optic','OPTIC 2000','👓',"Création / Technique","Trouve les passes qui débouchent sur des occasions.",[p('xaPM',85),p('chancesCreatedPM',85),g('chancesCreated',5)]),
badge('baller','CERTIFIED BALLER','🪄',"Création / Technique","Tente beaucoup de dribbles et en réussit une bonne part.",[p('dribblesCompletedPM',80),p('dribblePct',70),g('dribblePct',55),g('dribblesAttempted',15)]),
badge('menace','MENACE II SOCIETY','⚡',"Création / Technique","Percute, obtient des fautes et participe au jeu offensif.",[count(2,p('dribblesCompleted',75),p('foulsWon',75),p('ga',70))]),
badge('sees','HE SEES IT','🔭',"Création / Technique","Trouve ses coéquipiers avec des passes longues.",[p('longPassesCompletedPM',85),p('longPassPct',70),g('longPassesAttempted',10)]),
badge('system','THE SYSTEM','🧠','Control',"Au cœur des passes et de la création d’occasions.",[p('touchesPM',85),p('passesAttemptedPM',85),p('chancesCreated',65),g('passPct',70)]),
badge('magnet','BALL MAGNET','🧲','Control',"Cumule les touches de balle.",[p('touchesPM',90),g('matches',6)]),
badge('controller','THE CONTROLLER','🎛️','Control',"Fait circuler le ballon avec peu de pertes.",[p('passesAttemptedPM',80),p('passPct',80),bottom('lossRatio',30),g('passesAttemptedPM',15)]),
badge('glue','THE GLUE','🧩','Control',"Fait le lien dans le jeu grâce aux passes et aux récupérations.",[count(4,p('passesCompleted',70),p('secondaryAssists',65),p('recoveries',65),p('lossRatio',60,true),p('collective',70))]),
badge('v12','V12','🏎️','Volume',"Un gros volume d’actions dans plusieurs catégories.",[count(4,...['touches','passesAttempted','recoveries','duelsWon','dribblesCompleted','foulsWon'].map(k=>p(k,75))),g('matches',6)]),
badge('two-way','TWO-WAY PLAYER','↔️','Volume',"Contribue en attaque comme en défense.",[p('offensiveImpact',65),p('defensiveImpact',65)]),
badge('vacuum','VACUUM CLEANER','🧹','Defensive',"Cumule les récupérations et les interceptions.",[p('recoveriesPM',85),p('interceptionsPM',70),g('recoveriesPM',3)]),
badge('no-entry','NO ENTRY','⛔','Defensive',"Gagne ses duels et laisse passer peu de dribbleurs.",[p('duelPct',80),bottom('dribbledPastPM',25),g('duelsAttempted',20)]),
badge('hawk','BALL HAWK','🦅','Defensive',"Anticipe les passes et multiplie les interceptions.",[p('interceptionsPM',90),g('interceptions',8)]),
badge('no-fly','NO-FLY ZONE','✈️','Defensive',"Gagne une grande part de ses duels aériens.",[p('aerialDuelsWon',85),p('aerialPct',75),g('aerialDuelsAttempted',10)]),
badge('aura-defender','AURA DEFENDER','🛡️','Defensive',"Son équipe encaisse peu et concède peu de xG pendant sa présence sur le terrain.",[bottom('goalsConcededPM',25),bottom('xgConcededPM',25),p('collective',60),g('matches',6)]),
badge('silent','SILENT CARRY','🥷','Defensive',"Contribue aux résultats avec ses actions défensives.",[p('defensiveImpact',80),p('collective',75),bottom('ga',40),g('matches',6)]),
badge('fraud','FRAUD WATCH','🕵️','Allegations',"Les performances récentes sont en baisse.",[bottom('recentRating',35),p('previousRating',65),g('recentDrop',.6)]),
badge('merchant','xG MERCHANT','🛒','Allegations',"Les xG montent plus vite que les buts.",[p('xg',75),bottom('goalsMinusXg',20),g('xg',3)]),
badge('brick','BRICKLAYER','🧱','Allegations',"Multiplie les tirs, mais en cadre peu.",[p('shots',75),bottom('shotPct',25),g('shots',12)]),
badge('lache','LÂCHE LE BALLON','🛑','Allegations',"Beaucoup de pertes par rapport au nombre de touches.",[p('lossRatio',90),g('turnovers',30)]),
badge('drunk','DRUNK DRIBBLING','🥴','Allegations',"Beaucoup de dribbles tentés, un faible taux de réussite.",[p('dribblesAttempted',75),bottom('dribblePct',25),g('dribblesAttempted',15)]),
badge('traffic','TRAFFIC CONE','🚧','Allegations',"Se fait souvent éliminer dans les duels défensifs.",[p('dribbledPast',80),bottom('duelPct',30),g('defensiveDuels',15)]),
badge('casino-mode','CASINO MODE','🎲','Allegations',"Un rating très variable d’un match à l’autre.",[p('variance',90),g('ratingCount',6)]),
badge('washed-badge','WASHED ALLEGATIONS','📉','Allegations',"Le rating des cinq derniers matchs est en baisse par rapport aux cinq précédents.",[g('recentDrop',.75),g('matches',10)]),
badge('main','MAIN CHARACTER','🎭','Allegations',"Prend une grosse part des tirs et des dribbles, avec peu d’occasions créées.",[p('shotShare',80),p('dribbleShare',80),bottom('creation',50)]),
badge('vibes','NO TOUCHES JUST VIBES','🫥','Allegations',"Peu de touches de balle. Les vibes, elles, ne se comptent pas.",[bottom('touchesPM',10),g('matches',5)])
];
// Explicitly unavailable counters: total duels cannot stand in for defensive duels.
export const recognitionLimits=[{metric:'defensiveDuels',affected:['TRAFFIC CONE (Award)','TRAFFIC CONE (Badge)'],reason:"Les stats actuelles ne distinguent pas les duels défensifs des autres duels. Ces récompenses ne peuvent donc pas être attribuées."},{metric:'successfulTackles',affected:['MR. PROPRE'],reason:"Les tacles réussis sont comptés seulement si chaque tacle est marqué gagné, perdu ou faute dans la timeline. Le total des tacles ne suffit pas."},{metric:'offTarget',affected:['INTERSTELLAR'],reason:"Pour compter les tirs hors cadre, chaque tir doit avoir un résultat renseigné. Soustraire les tirs cadrés du total compterait aussi les tirs bloqués."}];
