import {labels} from './model.ts';
import type {League,Match} from './model.ts';
import {aggregate,metric as summaryMetric,type Summary} from './engine.ts';
export type MetricMap=Record<string,number|null>;
export type CandidateMetrics={id:string;playerIds:string[];name:string;values:MetricMap};
export type Rule={key:string;op:'gte'|'lte'|'lt';value:number;percentile?:boolean;low?:boolean}|{any:Rule[]}|{count:number;of:Rule[]};
export type Weight={key:string;weight:number;low?:boolean};
export type Definition={id:string;name:string;icon:string;description:string;category:string;rules:Rule[];weights:Weight[];ratio?:boolean;always?:boolean;kind?:'duo'};
export type Check={label:string;passed:boolean;actual:number|null;target:number;key:string;op?:'gte'|'lte'|'lt'};
export type BadgeResult={id:string;name:string;icon:string;description:string;category:string;active:boolean;score:number;checks:Check[]};
export type AwardResult={id:string;name:string;icon:string;description:string;category:string;seasonId:string;winner:CandidateMetrics|null;score:number|null;status:'preview'|'final';checks:Check[];reason:string;formula:Weight[]};
export function percentile(value:number|null,values:(number|null)[],inverse=false):number|null{const known=values.filter((v):v is number=>v!=null&&Number.isFinite(v));if(value==null||!known.length)return null;if(known.length===1)return 50;const lower=known.filter(v=>v<value).length,equal=known.filter(v=>v===value).length;const p=100*(lower+(Math.max(1,equal)-1)/2)/(known.length-1);return inverse?100-p:p}
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const sumKnown=(...v:(number|null|undefined)[])=>v.every(n=>n!=null)?v.reduce<number>((s,n)=>s+n!,0):null;
const ratio=(a:number|null,b:number|null)=>a!=null&&b!=null&&b>0?a/b:null;
const ratings=(matches:Match[],id:string)=>matches.map(m=>m.participants.find(p=>p.playerId===id)?.stats.rating).filter((v):v is number=>v!=null);
const win=(m:Match,id:string)=>m.participants.find(p=>p.playerId===id)?.team==='A'?m.scoreA!>m.scoreB!:m.scoreB!>m.scoreA!;
export function minimumAwardMatches(max:number){return Math.max(5,Math.ceil(.35*max))}
export function minimumBadgeMatches(max:number){return Math.max(4,Math.ceil(.25*max))}
export const metricLabels:Record<string,string>={...labels,attendance:'Présence relative %',secondaryChances:'Secondary Assists + occasions créées',matches:'Matchs joués',wins:'Victoires',winRate:'Victoires %',rating:'Rating moyen',mvpPM:'MVP / match',collective:'Collective Score',defensiveCollective:'Defensive Collective Score',offensiveImpact:'Offensive Impact',defensiveImpact:'Defensive Impact',creation:'Assists + Secondary Assists + occasions créées',assistsSecondary:'Assists + Secondary Assists',assistsSecondaryPM:'Assists + Secondary Assists / match',lossRatio:'Pertes / touches',variance:'Variance du rating',std:'Écart-type du rating',ratingCount:'Matchs notés',ratingRange:'Écart meilleur / pire rating',improvement:'Progression du rating',decline:'Baisse du rating',collectiveProgress:'Progression collective',recentRating:'Rating des 5 derniers matchs',previousRating:'Rating des 5 précédents',recentDrop:'Baisse récente du rating',shotShare:'Part des tirs de l’équipe',dribbleShare:'Part des dribbles de l’équipe',wastedXg:'xG − buts',offTarget:'Tirs non cadrés observés',failedDribbles:'Dribbles ratés',successfulTackles:'Tacles réussis observés',defensiveDuels:'Duels défensifs observés',defensiveDuelPct:'Duels défensifs gagnés %',defActionsPM:'Tacles + interceptions + blocs / match',interceptionTacklePM:'Interceptions + tacles réussis / match',duoGaPM:'Buts + assists + secondary assists du duo / match'};
export const metricName=(key:string):string=>metricLabels[key]??(key.endsWith('PM')?metricName(key.slice(0,-2))+' / match':key);
function share(s:Summary,key:string){let own=0,total=0,n=0;for(const f of s.form){const team=f.match.participants.filter(p=>p.team===f.participant.team);if(team.some(p=>p.stats[key]==null))return null;own+=f.participant.stats[key]!;total+=team.reduce((a,p)=>a+p.stats[key]!,0);n++}return n?ratio(own,total):null}
function observedEventTotal(s:Summary,key:string,types:string[],qualifies:(e:Match['events'][number])=>boolean){const rows=s.form.filter(f=>f.participant.stats[key]!=null);if(!rows.length)return null;let total=0;for(const f of rows){const events=f.match.events.filter(e=>e.playerId===s.player.id&&types.includes(e.type));if(events.length!==f.participant.stats[key]||events.some(e=>e.metadata.schemaVersion!==2||!(e.type==='SHOT'?['GOAL','ON_TARGET','OFF_TARGET','BLOCKED','WOODWORK']:['WON','LOST','FOUL']).includes(String(e.metadata.outcome))))return null;total+=events.filter(qualifies).length}return total}
function rawCandidate(s:Summary):CandidateMetrics{
 const v:MetricMap={...s.stats,matches:s.appearances,wins:s.wins,winRate:s.stats.winRate,rating:s.stats.rating,mvpPM:s.appearances?s.mvp/s.appearances:null};
 for(const key of Object.keys(s.stats))v[key+'PM']=summaryMetric(s,key,true);
 // Composite ratios only combine observations from the same games.
 const paired=(keys:string[],fn:(values:number[])=>number)=>{const rows=s.form.filter(f=>keys.every(k=>f.participant.stats[k]!=null));return rows.length?{total:rows.reduce((a,f)=>a+fn(keys.map(k=>f.participant.stats[k]!)),0),count:rows.length}:null};
 const ga=paired(['goals','assists'],v=>v[0]+v[1]);v.ga=ga?.total??null;v.gaPM=ga?ga.total/ga.count:null;
 const ap=paired(['assists','secondaryAssists'],v=>v[0]+v[1]);v.assistsSecondary=ap?.total??null;v.assistsSecondaryPM=ap?ap.total/ap.count:null;v.secondaryChances=paired(['secondaryAssists','chancesCreated'],v=>v[0]+v[1])?.total??null;v.creation=paired(['assists','secondaryAssists','chancesCreated'],v=>v[0]+v[1]+v[2])?.total??null;const losses=paired(['turnovers','touches'],v=>v[0]),touches=paired(['turnovers','touches'],v=>v[1]);v.lossRatio=ratio(losses?.total??null,touches?.total??null);v.wastedXg=v.goalsMinusXg==null?null:-v.goalsMinusXg;v.failedDribbles=paired(['dribblesAttempted','dribblesCompleted'],v=>v[0]-v[1])?.total??null;
 v.shotShare=share(s,'shots');v.dribbleShare=share(s,'dribblesAttempted');v.offTarget=observedEventTotal(s,'shots',['SHOT'],e=>e.metadata.outcome==='OFF_TARGET');v.successfulTackles=observedEventTotal(s,'tackles',['TACKLE'],e=>e.metadata.outcome==='WON');v.successfulTacklesPM=ratio(v.successfulTackles,s.form.filter(f=>f.participant.stats.tackles!=null).length);v.interceptionTacklePM=sumKnown(v.interceptionsPM,v.successfulTacklesPM);v.defensiveDuels=null;v.defensiveDuelPct=null;v.defActionsPM=sumKnown(v.tacklesPM,v.interceptionsPM,v.blocksPM);
 const games=[...s.form].reverse().map(f=>f.match),r=ratings(games,s.player.id),avg=mean(r);v.ratingCount=r.length;v.variance=avg!=null&&r.length>=2?mean(r.map(x=>(x-avg)**2)):null;v.std=v.variance==null?null:Math.sqrt(v.variance);v.ratingRange=r.length?Math.max(...r)-Math.min(...r):null;
 const half=Math.floor(games.length/2),early=games.slice(0,half),late=games.slice(half),er=ratings(early,s.player.id),lr=ratings(late,s.player.id);const eMean=er.length===early.length?mean(er):null,lMean=lr.length===late.length?mean(lr):null;v.improvement=eMean!=null&&lMean!=null?lMean-eMean:null;v.decline=v.improvement==null?null:-v.improvement;
 const last=ratings(games.slice(-5),s.player.id),previous=ratings(games.slice(-10,-5),s.player.id);v.recentRating=last.length===5?mean(last):null;v.previousRating=previous.length===5?mean(previous):null;v.recentDrop=v.recentRating!=null&&v.previousRating!=null?v.previousRating-v.recentRating:null;
 for(const [prefix,list]of [['early',early],['late',late]] as const){v[prefix+'Wins']=list.filter(m=>win(m,s.player.id)).length;v[prefix+'WinRate']=list.length?100*v[prefix+'Wins']!/list.length:null}
 return{id:s.player.id,playerIds:[s.player.id],name:s.player.name,values:v};
}
export function metricPercentile(c:CandidateMetrics,key:string,population:CandidateMetrics[],low=false){return percentile(c.values[key]??null,population.map(p=>p.values[key]??null),low)}
const weighted=(c:CandidateMetrics,pop:CandidateMetrics[],weights:Weight[],partial=false)=>{let total=0,w=0;for(const part of weights){const p=metricPercentile(c,part.key,pop,part.low);if(p==null){if(!partial)return null;continue}total+=part.weight*p;w+=Math.abs(part.weight)}return w?total/w:null};
export function candidates(league:Pick<League,'players'|'matches'>,seasonId?:string){const ms=league.matches.filter(m=>m.status==='finished'&&(!seasonId||m.seasonId===seasonId));const rows=aggregate(league.players,ms).filter(s=>s.appearances>0&&!s.player.demo).map(rawCandidate);const max=Math.max(0,...rows.map(c=>c.values.matches??0));for(const c of rows){c.values.attendance=max?100*c.values.matches!/max:null;c.values.collective=weighted(c,rows,[{key:'winRate',weight:.6},{key:'wins',weight:.4}]);c.values.defensiveCollective=weighted(c,rows,[{key:'goalsConcededPM',weight:.5,low:true},{key:'xgConcededPM',weight:.5,low:true}]);c.values.offensiveImpact=weighted(c,rows,[{key:'ga',weight:2},{key:'xa',weight:1},{key:'chancesCreated',weight:1},{key:'dribblesCompleted',weight:2}]);c.values.defensiveImpact=weighted(c,rows,[{key:'recoveries',weight:1},{key:'interceptions',weight:1},{key:'duelsWon',weight:1},{key:'tackles',weight:1}]);const early=weighted(c,rows,[{key:'earlyWinRate',weight:.6},{key:'earlyWins',weight:.4}]),late=weighted(c,rows,[{key:'lateWinRate',weight:.6},{key:'lateWins',weight:.4}]);c.values.collectiveProgress=early!=null&&late!=null?late-early:null}return rows}
export function evaluateRule(rule:Rule,c:CandidateMetrics,pop:CandidateMetrics[]):{passed:boolean;checks:Check[]}{if('any'in rule||'of'in rule){const list='any'in rule?rule.any:rule.of,minimum='any'in rule?1:rule.count;const checks=list.map(r=>evaluateRule(r,c,pop));return{passed:checks.filter(r=>r.passed).length>=minimum,checks:checks.flatMap(r=>r.checks)}}const actual=rule.percentile?metricPercentile(c,rule.key,pop,rule.low):c.values[rule.key]??null;return{passed:actual!=null&&(rule.op==='gte'?actual>=rule.value:rule.op==='lte'?actual<=rule.value:actual<rule.value),checks:[{key:rule.key,label:metricName(rule.key)+(rule.percentile?' · percentile'+(rule.low?' inversé':''):''),actual,target:rule.value,op:rule.op,passed:actual!=null&&(rule.op==='gte'?actual>=rule.value:rule.op==='lte'?actual<=rule.value:actual<rule.value)}]}}
export function evaluateBadges(c:CandidateMetrics,pop:CandidateMetrics[],definitions:Definition[]):BadgeResult[]{const min=minimumBadgeMatches(Math.max(0,...pop.map(p=>p.values.matches??0)));return definitions.map(d=>{const results=[evaluateRule({key:'matches',op:'gte',value:min},c,pop),...d.rules.map(r=>evaluateRule(r,c,pop))];const checks=results.flatMap(r=>r.checks),active=pop.length>=3&&results.every(r=>r.passed);const percentiles=checks.filter(x=>x.label.includes('percentile')&&x.actual!=null).map(x=>{const rule=findRule(d.rules,x.key);return rule&&rule.op!=='gte'?100-x.actual!:x.actual!});const absolute=checks.filter(x=>!x.label.includes('percentile')&&!['matches','ratingCount'].includes(x.key)&&x.actual!=null).map(x=>Math.min(100,Math.max(0,x.op==='gte'?50*x.actual!/x.target:50*x.target/Math.max(.001,x.actual!))));const score=mean(percentiles)??mean(absolute)??0;return{id:d.id,name:d.name,icon:d.icon,description:d.description,category:d.category,active,score:Math.round(score),checks}})}
function findRule(rules:Rule[],key:string):Extract<Rule,{key:string}>|undefined{for(const r of rules){if('key'in r&&r.key===key)return r;if('any'in r||'of'in r){const found=findRule('any'in r?r.any:r.of,key);if(found)return found}}}
export function mainBadges(badges:BadgeResult[]){const sorted=badges.filter(b=>b.active).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));const out:BadgeResult[]=[];for(const b of sorted){if(b.category==='Allegations'&&out.some(x=>x.category==='Allegations'))continue;out.push(b);if(out.length===3)break}return out}
export function duoCandidates(league:Pick<League,'players'|'matches'>,seasonId:string){const ps=league.players.filter(p=>!p.demo);const result:CandidateMetrics[]=[];for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const ids=[ps[i].id,ps[j].id],games=league.matches.filter(m=>m.seasonId===seasonId&&m.status==='finished'&&m.participants.some(p=>p.playerId===ids[0]&&p.team&&m.participants.some(q=>q.playerId===ids[1]&&q.team===p.team)));if(!games.length)continue;const wins=games.filter(m=>win(m,ids[0])).length,r=games.flatMap(m=>ids.map(id=>m.participants.find(p=>p.playerId===id)!.stats.rating)),ga=games.flatMap(m=>ids.map(id=>{const p=m.participants.find(p=>p.playerId===id)!;return sumKnown(p.stats.goals,p.stats.assists,p.stats.secondaryAssists)}));result.push({id:ids.join(':'),playerIds:ids,name:ps[i].name+' + '+ps[j].name,values:{matches:games.length,wins,winRate:100*wins/games.length,rating:r.every(x=>x!=null)?mean(r as number[]):null,duoGaPM:ga.every(x=>x!=null)?ga.reduce<number>((s,x)=>s+x!,0)/games.length:null}})}return result}
function ruleKeys(r:Rule):string[]{return 'key'in r?[r.key]:('any'in r?r.any:r.of).flatMap(ruleKeys)}
export function evaluateAwards(league:Pick<League,'players'|'matches'>,seasonId:string,definitions:Definition[]):AwardResult[]{const rows=candidates(league,seasonId),max=Math.max(0,...rows.map(c=>c.values.matches??0)),min=minimumAwardMatches(max);return definitions.map(d=>{const all=d.kind==='duo'?duoCandidates(league,seasonId):rows;const pop=d.ratio?all.filter(c=>(c.values.matches??0)>=min):all;const ranked=all.map(c=>{const rules=[...(d.ratio?[{key:'matches',op:'gte',value:min} as Rule]:[]),...d.rules];const result=rules.map(r=>evaluateRule(r,c,pop));const score=weighted(c,pop,d.weights,d.always);return{c,eligible:result.every(x=>x.passed),checks:result.flatMap(x=>x.checks),score}}).filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score!-a.score!||(b.c.values.rating??-Infinity)-(a.c.values.rating??-Infinity)||(b.c.values.wins??0)-(a.c.values.wins??0)||(b.c.values.matches??0)-(a.c.values.matches??0)||a.c.id.localeCompare(b.c.id));const winner=ranked[0];const missing=[...new Set([...d.weights.map(w=>w.key),...d.rules.flatMap(ruleKeys)])].filter(key=>all.length>0&&all.every(c=>c.values[key]==null));const reason=winner?(ranked[1]&&Math.abs(winner.score!-ranked[1].score!)<1e-9?'Égalité départagée par rating, victoires, présences puis identifiant stable.':'Seuils de mérite atteints.'):missing.length?'Données manquantes : '+missing.map(metricName).join(', ')+'.':'Seuils de mérite non atteints.';return{id:d.id,name:d.name,icon:d.icon,description:d.description,category:d.category,seasonId,winner:winner?.c??null,score:winner?.score??null,status:'preview',checks:winner?.checks??[],reason,formula:d.weights}})}
