import {publishAnalysis,publicMatch} from './match-analysis';
import {projectSecondaryAssists} from './events';
import {currentMatch} from './model';
import {projectEvents} from './events';
import {rateMatches} from './performance';
import {db} from './server/database';
export {db} from './server/database';
import type {League,Match,Player,Season} from './model';
import {defaultSettings,eventMap,teamName} from './model';
import {playerSchema,seasonSchema,matchSchema} from './validation';
export async function rows(sql:string,...args:unknown[]){return (await db().prepare(sql).bind(...args).all()).results as any[]}
export async function identity(user:{userId:string;email:string;admin?:boolean}|null){return {admin:!!user?.admin,bootstrap:false,user:user?.email??null}}
export async function readLeague(options:{drafts?:boolean}={}):Promise<Omit<League,'admin'|'bootstrap'|'user'>>{const [p,a,s,m,mp,st,e,v,aw,settings,teams]=await Promise.all(['players','player_attributes','seasons','matches','match_players','match_player_stats','match_events','videos','season_awards','settings','teams'].map(t=>rows('SELECT * FROM '+t)));const realSeasons=s.filter(r=>!r.demo),realPlayers=p.filter(r=>!r.demo);return{players:realPlayers.map(r=>({id:r.id,name:r.name,bio:r.bio,photo:r.photo,funFacts:r.fun_facts,archived:!!r.archived,demo:!!r.demo,version:r.version,attributes:JSON.parse(a.find(x=>x.player_id===r.id)?.data??'{}')})),seasons:realSeasons.map(r=>({id:r.id,name:r.name,start:r.start,end:r.end,status:r.status,demo:!!r.demo,contribution:r.contribution,minParticipation:r.min_participation,winnerId:aw.find(a=>a.season_id===r.id)?.player_id??null,version:r.version})),matches:rateMatches(m.filter(r=>realSeasons.some(s=>s.id===r.season_id)).map(r=>({id:r.id,seasonId:r.season_id,number:r.number,date:r.date,duration:r.duration,location:r.location,status:r.status,scoreA:r.score_a,scoreB:r.score_b,mvpId:r.mvp_id,level:r.level,version:r.version,notes:r.notes,analysis:r.analysis?JSON.parse(r.analysis):undefined,teamAName:teams.find(t=>t.match_id===r.id&&t.side==='A')?.name||'Équipe A',teamBName:teams.find(t=>t.match_id===r.id&&t.side==='B')?.name||'Équipe B',trackedKeys:JSON.parse(r.tracked_keys),video:v.find(v=>v.match_id===r.id)?.url??'',participants:mp.filter(x=>x.match_id===r.id).map(x=>({playerId:x.player_id,team:x.team,stats:Object.fromEntries(Object.entries(JSON.parse(st.find(y=>y.match_id===r.id&&y.player_id===x.player_id)?.data??'{}')).filter(([k])=>!['admin_rating','minutes_played','role'].includes(k))) as any,minutesPlayed:JSON.parse(st.find(y=>y.match_id===r.id&&y.player_id===x.player_id)?.data??'{}').minutes_played??null,role:JSON.parse(st.find(y=>y.match_id===r.id&&y.player_id===x.player_id)?.data??'{}').role??'field',admin_rating:JSON.parse(st.find(y=>y.match_id===r.id&&y.player_id===x.player_id)?.data??'{}').admin_rating??null})),events:e.filter(x=>x.match_id===r.id).map(x=>({id:x.id,playerId:x.player_id,team:x.team,type:x.event_type,timestamp:x.timestamp,relatedPlayerId:x.related_player_id,metadata:JSON.parse(x.metadata)}))})).map(currentMatch).map(projectSecondaryAssists).map(m=>options.drafts?m:publicMatch(m)),JSON.parse(settings.find(s=>s.id==='thresholds')?.data??'{}').ratingWeights??{},JSON.parse(settings.find(s=>s.id==='thresholds')?.data??'{}').ratingEngine??'v2'),settings:{...defaultSettings,...JSON.parse(settings.find(s=>s.id==='thresholds')?.data??'{}')}}}
export async function savePlayer(input:unknown){const p=playerSchema.parse(input);const token=crypto.randomUUID();const q=db().prepare('INSERT INTO players(id,name,bio,photo,fun_facts,archived,demo,version,edit_token) VALUES(?,?,?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,bio=excluded.bio,photo=excluded.photo,fun_facts=excluded.fun_facts,archived=excluded.archived,version=players.version+1,edit_token=excluded.edit_token WHERE players.version=? RETURNING version').bind(p.id,p.name,p.bio,p.photo,p.funFacts,+p.archived,+p.demo,token,p.version); // Attribute writes use the unique mutation token.
const result=await db().batch([q,db().prepare('INSERT INTO player_attributes(player_id,data) SELECT ?,? WHERE EXISTS(SELECT 1 FROM players WHERE id=? AND edit_token=?) ON CONFLICT(player_id) DO UPDATE SET data=excluded.data').bind(p.id,JSON.stringify(p.attributes),p.id,token)]);if(!result[0].results.length)throw Error("Conflit de modification : une version plus récente a déjà été enregistrée. Recharge la page avant de réessayer.");return p.id}
export async function saveSeason(input:unknown){const s=seasonSchema.parse(input);const token=crypto.randomUUID();if(s.winnerId){const league=await readLeague();const matches=league.matches.filter(m=>m.seasonId===s.id&&m.status==='finished');const count=matches.filter(m=>m.participants.some(p=>p.playerId===s.winnerId)).length;if(!matches.length||count<Math.ceil(matches.length*s.minParticipation))throw Error('Joueur non éligible à la récompense.');if(s.status==='active')throw Error("Termine la saison avant de confirmer son joueur gagnant.");}const result=await db().batch([db().prepare('INSERT INTO seasons(id,name,start,end,status,demo,contribution,min_participation,version,edit_token) VALUES(?,?,?,?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,start=excluded.start,end=excluded.end,status=excluded.status,contribution=excluded.contribution,min_participation=excluded.min_participation,version=seasons.version+1,edit_token=excluded.edit_token WHERE seasons.version=? RETURNING version').bind(s.id,s.name,s.start,s.end,s.status,+s.demo,s.contribution,s.minParticipation,token,s.version),db().prepare('DELETE FROM season_awards WHERE season_id=? AND EXISTS(SELECT 1 FROM seasons WHERE id=? AND edit_token=?)').bind(s.id,s.id,token),...(s.winnerId?[db().prepare('INSERT INTO season_awards(season_id,player_id) SELECT ?,? WHERE EXISTS(SELECT 1 FROM seasons WHERE id=? AND edit_token=?)').bind(s.id,s.winnerId,s.id,token)]:[])]);if(!result[0].results.length)throw Error("Conflit de modification : une version plus récente a déjà été enregistrée. Recharge la page avant de réessayer.");return s.id}
export async function saveMatch(input:unknown){let m=matchSchema.parse(input) as Match;const current=await rows('SELECT id,version,analysis FROM matches WHERE id=?',m.id);if((current[0]?.version??0)!==m.version)throw Error("Conflit de modification : une version plus récente a déjà été enregistrée. Recharge la page avant de réessayer.");const season=(await rows('SELECT * FROM seasons WHERE id=?',m.seasonId))[0];if(!season)throw Error('Saison inconnue.');const day=m.date.slice(0,10);if(day&&((season.start&&day<season.start)||(season.end&&day>season.end)))throw Error('La date est hors de la saison choisie.');for(const p of m.participants){const player=(await rows('SELECT * FROM players WHERE id=?',p.playerId))[0];if(!player||!!player.demo!==!!season.demo)throw Error("Les joueurs de démo et les joueurs réels doivent rester dans leurs saisons respectives.");}
if(current[0]?.analysis&&!m.analysis)throw Error("L’état de l’analyse manque. Recharge le match.");
if(m.analysis){
 const prior=current[0]?.analysis?JSON.parse(current[0].analysis):null;
 const storedEvents=prior?.publishedEvents??(current.length?(await rows('SELECT * FROM match_events WHERE match_id=?',m.id)).map(e=>({id:e.id,playerId:e.player_id,team:e.team,type:e.event_type,timestamp:e.timestamp,relatedPlayerId:e.related_player_id,metadata:JSON.parse(e.metadata)})):[]);
 m.analysis={...m.analysis,publishedEvents:storedEvents,publishedKeys:prior?.publishedKeys??(current.length?m.trackedKeys:[]),publishedRanges:prior?.publishedRanges,publishedAt:prior?.publishedAt};
 if(m.analysis.status==='validated')m=publishAnalysis(m);
 else if(prior?.publishedKeys?.length){const saved=await rows('SELECT * FROM match_player_stats WHERE match_id=?',m.id);m.participants=m.participants.map(p=>{const previous=JSON.parse(saved.find(s=>s.player_id===p.playerId)?.data??'{}');return {...p,stats:{...p.stats,...Object.fromEntries(prior.publishedKeys.map((k:string)=>[k,previous[k]??null]))}}});}
}else m=projectEvents(m);
matchSchema.parse(m);if(m.status==='finished'&&!m.analysis){for(const side of ['A','B']){const team=m.participants.filter(p=>p.team===side);const goals=team.reduce((s,p)=>s+(p.stats.goals??0),0)+m.participants.filter(p=>p.team===(side==='A'?'B':'A')).reduce((s,p)=>s+(p.stats.ownGoals??0),0);const score=side==='A'?m.scoreA!:m.scoreB!;if(goals>score||(team.every(p=>p.stats.goals!=null)&&goals!==score))throw Error('Le total des buts saisis doit correspondre au score de '+teamName(m,side)+'.')}}const token=crypto.randomUUID();const queries=[db().prepare('INSERT INTO matches(id,season_id,number,date,duration,location,status,score_a,score_b,mvp_id,level,tracked_keys,notes,analysis,version,edit_token) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET season_id=excluded.season_id,number=excluded.number,date=excluded.date,duration=excluded.duration,location=excluded.location,status=excluded.status,score_a=excluded.score_a,score_b=excluded.score_b,mvp_id=excluded.mvp_id,level=excluded.level,tracked_keys=excluded.tracked_keys,notes=excluded.notes,analysis=excluded.analysis,version=matches.version+1,edit_token=excluded.edit_token WHERE matches.version=? RETURNING version').bind(m.id,m.seasonId,m.number,m.date,m.duration,m.location,m.status,m.scoreA,m.scoreB,m.mvpId,m.level,JSON.stringify(m.trackedKeys),m.notes??'',m.analysis?JSON.stringify(m.analysis):null,token,m.version)];const guard='EXISTS(SELECT 1 FROM matches WHERE id=? AND edit_token=?)';for(const table of ['match_player_stats','match_events','match_players','teams','videos'])queries.push(db().prepare(`DELETE FROM ${table} WHERE match_id=? AND ${guard}`).bind(m.id,m.id,token));for(const side of ['A','B'])queries.push(db().prepare(`INSERT INTO teams(id,match_id,side,name) SELECT ?,?,?,? WHERE ${guard}`).bind(m.id+'-'+side,m.id,side,teamName(m,side),m.id,token));for(const p of m.participants){queries.push(db().prepare(`INSERT INTO match_players(match_id,player_id,team) SELECT ?,?,? WHERE ${guard}`).bind(m.id,p.playerId,p.team,m.id,token));queries.push(db().prepare(`INSERT INTO match_player_stats(match_id,player_id,data) SELECT ?,?,? WHERE ${guard}`).bind(m.id,p.playerId,JSON.stringify({...p.stats,admin_rating:p.admin_rating??null,minutes_played:p.minutesPlayed??null,role:p.role??'field'}),m.id,token))}for(const e of m.events)queries.push(db().prepare(`INSERT INTO match_events(id,match_id,player_id,team,event_type,timestamp,related_player_id,metadata) SELECT ?,?,?,?,?,?,?,? WHERE ${guard}`).bind(e.id,m.id,e.playerId,e.team,e.type,e.timestamp,e.relatedPlayerId,JSON.stringify(e.metadata),m.id,token));if(m.video)queries.push(db().prepare(`INSERT INTO videos(match_id,url) SELECT ?,? WHERE ${guard}`).bind(m.id,m.video,m.id,token));const result=await db().batch(queries);if(!result[0].results.length)throw Error("Conflit de modification : une version plus récente a déjà été enregistrée. Recharge la page avant de réessayer.");return m.id}
