import {currentMatch} from './model';
import {actionDefinitions,isV2} from './actions';
import {z} from 'zod';
import {rawKeys,attributes,eventMap} from './model';
import {youtubeId} from './engine';
const id=z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/);const nullableId=id.nullable();
const stats=z.record(z.number().finite().min(0).max(100000).nullable()).superRefine((s,ctx)=>{for(const [k,v]of Object.entries(s)){if(!rawKeys.includes(k))ctx.addIssue({code:'custom',message:'Statistique inconnue : '+k});if(k==='rating'&&v!=null&&v>10)ctx.addIssue({code:'custom',message:'Rating entre 0 et 10'});if(v!=null&&!['rating','xg','xa','xgot','xgConceded'].includes(k)&&!Number.isInteger(v))ctx.addIssue({code:'custom',message:'Entier attendu : '+k})}for(const [a,b]of [['passesCompleted','passesAttempted'],['longPassesCompleted','longPassesAttempted'],['crossesCompleted','crossesAttempted'],['dribblesCompleted','dribblesAttempted'],['duelsWon','duelsAttempted'],['aerialDuelsWon','aerialDuelsAttempted'],['shotsOnTarget','shots'],['goals','shotsOnTarget']])if(s[a]!=null&&s[b]!=null&&s[a]!>s[b]!)ctx.addIssue({code:'custom',message:a+' ne peut pas dépasser '+b})});
export const playerSchema=z.object({id,name:z.string().trim().min(1).max(50),bio:z.string().max(1000).default(''),photo:z.string().max(300).regex(/^$|^\/api\/photos\/[a-zA-Z0-9_.-]+$/).default(''),funFacts:z.string().max(2000).default(''),archived:z.boolean().default(false),demo:z.literal(false).default(false),attributes:z.record(z.number().min(0).max(100)).refine(a=>Object.keys(a).every(k=>attributes.includes(k))).default({}),version:z.number().int().min(0)});
export const seasonSchema=z.object({id,name:z.string().trim().min(1).max(100),start:z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)]),end:z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)]),status:z.enum(['active','inactive','finished','archived']),demo:z.literal(false).default(false),contribution:z.number().min(0).max(1000),minParticipation:z.number().min(0).max(1),winnerId:nullableId,version:z.number().int().min(0)}).refine(s=>!s.start||!s.end||s.start<=s.end,'La fin précède le début de saison.');
const activeMatchSchema=z.object({id,seasonId:id,number:z.number().int().min(1),date:z.union([z.literal(''),z.string().datetime()]),duration:z.number().int().min(0).max(300),location:z.string().trim().max(300),status:z.enum(['scheduled','finished','cancelled']),scoreA:z.number().int().min(0).max(999).nullable(),scoreB:z.number().int().min(0).max(999).nullable(),mvpId:nullableId,level:z.number().int().min(1).max(3),video:z.string().max(500).refine(s=>!s||!!youtubeId(s)||/^\/api\/videos\/[a-zA-Z0-9_.-]+$/.test(s),'URL YouTube invalide'),teamAName:z.string().trim().min(1).max(60).default('Équipe A'),teamBName:z.string().trim().min(1).max(60).default('Équipe B'),participants:z.array(z.object({playerId:id,team:z.enum(['A','B']).nullable(),stats,admin_rating:z.number().min(3).max(10).nullable().optional()})).max(20),events:z.array(z.object({id,playerId:id,team:z.enum(['A','B']),type:z.string().refine(t=>t in eventMap||t in actionDefinitions),timestamp:z.number().min(0).max(86400).nullable(),relatedPlayerId:nullableId,metadata:z.record(z.unknown()).default({}).superRefine((v,c)=>{for(const key of ['position','endPosition']){const p=v[key] as any;if(p!=null&&(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>100||p.y<0||p.y>100))c.addIssue({code:'custom',message:'Coordonnées entre 0 et 100 requises'});}})})).max(3000),notes:z.string().max(5000).default(''),trackedKeys:z.array(z.string().refine(k=>rawKeys.includes(k))).max(70),version:z.number().int().min(0)}).superRefine((m,c)=>{const fail=(message:string)=>c.addIssue({code:'custom',message});if(m.status==='scheduled'&&(!m.date||m.duration<1||!m.location))fail('Date, durée et lieu requis pour un match à venir.');if(new Set(m.participants.map(p=>p.playerId)).size!==m.participants.length)fail('Un joueur ne peut être inscrit deux fois.');if(new Set(m.events.map(e=>e.id)).size!==m.events.length)fail('Événement dupliqué.');if(m.mvpId&&!m.participants.some(p=>p.playerId===m.mvpId))fail('Le MVP doit participer au match.');if(m.status==='finished'&&(m.scoreA==null||m.scoreB==null||!m.participants.some(p=>p.team==='A')||!m.participants.some(p=>p.team==='B')||m.participants.some(p=>!p.team)))fail('Score et deux équipes complètes requis.');for(const e of m.events){const p=m.participants.find(p=>p.playerId===e.playerId);
if(isV2(e)){
const d=actionDefinitions[e.type],v=e.metadata,o=v.outcome,t=v.tags;
if(!d)fail('Action inconnue');else{if(d.outcomes.length&&!d.outcomes.includes(String(o)))fail('Résultat invalide');if(!Array.isArray(t)||t.some(x=>typeof x!=='string'||!d.tags.includes(x)))fail('Tags invalides');}
if(typeof v.sequenceId!=='string'||v.sequenceId.length>100||!v.sequenceId)fail('Séquence requise');
const opponent=m.participants.find(q=>q.playerId===v.opponentPlayerId);
if(v.opponentPlayerId&&(!opponent||opponent.team===e.team))fail('Adversaire invalide');
if(['DUEL','DRIBBLE','TACKLE','FOUL'].includes(e.type)&&!opponent)fail('Choisissez un adversaire');
if(e.type==='PASS'&&!e.relatedPlayerId)fail('Choisissez un receveur');
if(e.type==='SHOT'&&o==='BLOCKED'&&!opponent)fail('Choisissez le défenseur');
if(e.type==='PASS'&&o==='FAILED'&&Array.isArray(t)&&t.includes('ASSIST'))fail('Une passe ratée ne peut être décisive');
if(v.linkedEventId){const linked=m.events.find(x=>x.id===v.linkedEventId);if(!linked||linked.id===e.id)fail('Action liée introuvable');else if(e.type==='SHOT'){if(linked.type!=='PASS'||linked.playerId!==e.relatedPlayerId||linked.relatedPlayerId!==e.playerId||linked.metadata.outcome!=='COMPLETED'||o!=='GOAL')fail('Passe liée incompatible');}else if(['SAVE','BLOCK'].includes(e.type)){if(linked.type!=='SHOT'||linked.playerId!==v.opponentPlayerId||linked.team===e.team||linked.metadata.outcome!==(e.type==='SAVE'?'ON_TARGET':'BLOCKED'))fail('Tir lié incompatible');}else fail('Lien non applicable');}
if(v.scene){const scene=v.scene as any;if(!scene.players||typeof scene.players!=='object')fail('Scène invalide');else for(const [id,point]of Object.entries(scene.players)){const q=point as any;if(!m.participants.some(p=>p.playerId===id)||!q||!Number.isFinite(q.x)||!Number.isFinite(q.y)||q.x<0||q.x>100||q.y<0||q.y>100)fail('Position de scène invalide');}const b=scene.ball;if(b&&(!Number.isFinite(b.x)||!Number.isFinite(b.y)||b.x<0||b.x>100||b.y<0||b.y>100))fail('Ballon invalide');}
}
if(!p||p.team!==e.team)fail('Événement : joueur absent ou mauvaise équipe.');if(e.relatedPlayerId&&(!m.participants.some(p=>p.playerId===e.relatedPlayerId&&p.team===e.team)||e.relatedPlayerId===e.playerId))fail('Association invalide.')}});

export const matchSchema=z.preprocess(input=>{const m=input as any;return m&&Array.isArray(m.participants)&&m.participants.every((p:any)=>p&&p.stats)&&Array.isArray(m.events)&&m.events.every((e:any)=>e&&e.metadata)&&Array.isArray(m.trackedKeys)?currentMatch(m):input},activeMatchSchema);
